# Generated by Django 3.1.2 on 2020-11-06 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0013_auto_20201106_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Plan Name')),
                ('limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquiries.inquiryplan')),
            ],
        ),
    ]
