# Generated by Django 3.1.2 on 2020-11-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inquiryplan',
            name='limit',
            field=models.PositiveIntegerField(),
        ),
    ]
