# Generated by Django 3.2 on 2022-07-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0001_squashed_0010_auto_20210104_2255"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiryrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
