# Generated by Django 3.1.2 on 2020-11-08 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquiries', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInquiry',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('counter', models.PositiveIntegerField(default=0, help_text='Current number of used inquiries.', verbose_name='Current counter')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquiries.inquiryplan')),
            ],
        ),
        migrations.AddField(
            model_name='inquiryrequest',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_request_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquiryrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_request_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='inquiryplan',
            unique_together={('name', 'limit')},
        ),
    ]
