# Generated by Django 3.1.2 on 2020-11-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_auto_20201106_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryplan',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
