# Generated by Django 3.2.21 on 2023-10-24 15:17

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.state import StateApps

from inquiries.models import InquiryPlan
from inquiries.plans import basic_plan, premium_plan


def get_new_plans(apps: StateApps) -> (InquiryPlan, InquiryPlan):
    """Get new plans."""
    InquiryPlan = apps.get_model("inquiries", "InquiryPlan")
    return (
        InquiryPlan.objects.get_or_create(**basic_plan.dict())[0],
        InquiryPlan.objects.get_or_create(**premium_plan.dict())[0],
    )


def migrate_all_inquiries_plan_to_basic(apps: StateApps, *_) -> None:
    """Migrate all inquiry plan to basic. Create UserInquiry if not exists."""
    User = apps.get_model("users", "User")
    UserInquiry = apps.get_model("inquiries", "UserInquiry")

    basic_inquiry_plan, _ = get_new_plans(apps)

    for user in User.objects.all():
        user_inquiry, created = UserInquiry.objects.get_or_create(
            user=user, defaults={"plan": basic_inquiry_plan}
        )
        if not created:
            user_inquiry.plan = basic_inquiry_plan
            user_inquiry.save()


def delete_old_inquiry_plans(apps: StateApps, *_) -> None:
    """Delete all old InquiryPlans."""
    InquiryPlan = apps.get_model("inquiries", "InquiryPlan")

    basic_inquiry_plan, premium_inquiry_plan = get_new_plans(apps)
    InquiryPlan.objects.all().exclude(
        pk__in=[basic_inquiry_plan.pk, premium_inquiry_plan.pk]
    ).delete()


def create_new_inquiry_plans(apps: StateApps, *_) -> None:
    """Create new InquiryPlans: basic and premium."""
    get_new_plans(apps)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_auto_20230918_0219"),
        ("inquiries", "0002_alter_inquiryrequest_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="InquiryContact",
            fields=[
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Numer telefonu",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="inquiry_contact",
                        serialize=False,
                        to="users.user",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="inquiryrequest",
            name="category",
        ),
        migrations.RunPython(create_new_inquiry_plans),
        migrations.RunPython(migrate_all_inquiries_plan_to_basic),
        migrations.RunPython(delete_old_inquiry_plans),
    ]
