# Generated by Django 3.1.2 on 2020-11-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_inquiryplan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryplan',
            name='sort',
            field=models.IntegerField(default=1, help_text='Used to sort plans low numbers threaded as lowest plans.', verbose_name='Soring'),
        ),
        migrations.AlterField(
            model_name='inquiryplan',
            name='description',
            field=models.TextField(blank=True, help_text='Short description what is rationale behind plan.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='inquiryplan',
            name='name',
            field=models.CharField(help_text='Plan name', max_length=255, verbose_name='Plan Name'),
        ),
    ]
