# Generated by Django 3.2.21 on 2023-10-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_auto_20231024_1717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestType',
        ),
    ]
