# Generated by Django 3.1.2 on 2020-12-04 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0004_requesttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiryrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
