# Generated by Django 3.2.23 on 2023-11-07 19:25

import django.db.models.deletion
from django.db import migrations, models

from inquiries.models import InquiryLogMessage as _InquiryLogMessage


def create_initial_messages(apps, *_) -> None:
    """Create initial messages for logs"""
    InquiryLogMessage: _InquiryLogMessage = apps.get_model(
        "inquiries", "InquiryLogMessage"
    )
    InquiryLogMessage.objects.get_or_create(
        body="<> zaakceptował twoje zapytanie.",
        message_type=_InquiryLogMessage.MessageType.ACCEPTED,
    )
    InquiryLogMessage.objects.get_or_create(
        body="<> odrzucił twoje zapytanie.",
        message_type=_InquiryLogMessage.MessageType.REJECTED,
    )
    InquiryLogMessage.objects.get_or_create(
        body="<> nie odpowiedział na twoje zapytanie. W zamian dodajemy Ci 1 nowe zapytanie, abyś mógł dalej odkrywać rynek transferowy.",
        message_type=_InquiryLogMessage.MessageType.OUTDATED,
    )
    InquiryLogMessage.objects.get_or_create(
        body="<> wysłał Ci nowe zapytanie.",
        message_type=_InquiryLogMessage.MessageType.NEW,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0004_delete_requesttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="InquiryLogMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Message should include '<>' as placeholder for user related with log."
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("ACCEPTED_INQUIRY", "Accepted inquiry"),
                            ("REJECTED_INQUIRY", "Rejected inquiry"),
                            ("NEW_INQUIRY", "New inquiry"),
                            ("OUTDATED_INQUIRY", "Outdated inquiry"),
                            ("UNDEFINED_INQUIRY", "Undefined inquiry"),
                        ],
                        default="UNDEFINED_INQUIRY",
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserInquiryLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "log_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="inquiries.userinquiry",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs",
                        to="inquiries.inquirylogmessage",
                    ),
                ),
                (
                    "ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inquiries.inquiryrequest",
                    ),
                ),
                (
                    "related_with",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_logs",
                        to="inquiries.userinquiry",
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_initial_messages),
    ]
