# Generated by Django 3.1.2 on 2020-11-07 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201106_1939'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquiries', '0004_auto_20201106_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMField(default='NEW', max_length=50)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_request_recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_request_recipient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInquiry',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('counter', models.PositiveIntegerField(default=0, help_text='Current number of used inquiries.', verbose_name='Current counter')),
            ],
        ),
        migrations.AddField(
            model_name='inquiryplan',
            name='default',
            field=models.BooleanField(default=False, help_text='Defines if this is default plan selected during account creation.', verbose_name='Default Plan'),
        ),
        migrations.AlterField(
            model_name='inquiryplan',
            name='description',
            field=models.TextField(blank=True, help_text='Short description what is rationale behind plan. Used only for internal purpose.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='inquiryplan',
            name='limit',
            field=models.PositiveIntegerField(help_text='Limit how many actions are allowed', verbose_name='Plan limit'),
        ),
        migrations.AlterField(
            model_name='inquiryplan',
            name='sort',
            field=models.PositiveIntegerField(default=0, help_text='Used to sort plans low numbers threaded as lowest plans. Default=0 which means this is not set.', verbose_name='Soring'),
        ),
        migrations.AlterUniqueTogether(
            name='inquiryplan',
            unique_together={('name', 'limit')},
        ),
        migrations.DeleteModel(
            name='Inquiry',
        ),
        migrations.AddField(
            model_name='userinquiry',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquiries.inquiryplan'),
        ),
    ]
