# Generated by Django 3.1.2 on 2020-12-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0005_auto_20201204_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryrequest',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
