# Generated by Django 3.2.23 on 2023-11-08 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0005_inquirylogmessage_userinquirylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinquirylog',
            name='ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inquiries.inquiryrequest'),
        ),
    ]
