# Generated by Django 3.2.23 on 2023-11-13 16:53

from django.db import migrations, models

from inquiries.models import InquiryLogMessage as _InquiryLogMessage


def create_initial_email_messages(apps, *_):
    """Create initial email messages with valid formating."""
    InquiryLogMessage: _InquiryLogMessage = apps.get_model(
        "inquiries", "InquiryLogMessage"
    )

    accepted_inquiry = InquiryLogMessage.objects.get(
        message_type=_InquiryLogMessage.MessageType.ACCEPTED
    )
    accepted_inquiry.email_title = (
        "#r# #zaakceptował|zaakceptowała# Twoje zapytanie o piłkarski kontakt!"
    )
    accepted_inquiry.email_body = """Witaj, gratulujemy!

Twoje zapytanie o kontakt zostało zaakceptowane przez #rb#!
Odwiedź swój profil na PlayMaker.pro lub kliknij w poniższy link żeby zobaczyć dane kontaktowe:
https://playmaker.pro/xyz/
Do zobaczenia na PlayMaker.pro!

Pozdrawiamy,
Zespól PlayMaker.pro

Wiadomość została wygenerowa automatycznie. Prosimy na nią nie odpowiadać."""
    accepted_inquiry.send_mail = True
    accepted_inquiry.save()

    rejected_inquiry = InquiryLogMessage.objects.get(
        message_type=_InquiryLogMessage.MessageType.REJECTED
    )
    rejected_inquiry.email_title = (
        "#r# #odrzucił|odrzuciła# Twoje zapytanie o piłkarski kontakt!"
    )
    rejected_inquiry.email_body = """Witaj, 

Twoje zapytanie o kontakt zostało odrzucone przez #rb#. 

Pozdrawiamy, 
Zespół PlayMaker.pro

Wiadomość została wygenerowana automatycznie. Prosimy na nią nie odpowiadać."""
    rejected_inquiry.send_mail = True
    rejected_inquiry.save()

    new_inquiry = InquiryLogMessage.objects.get(
        message_type=_InquiryLogMessage.MessageType.NEW
    )
    new_inquiry.email_title = "Masz nowe zapytanie o piłkarski kontakt!"
    new_inquiry.email_body = """Witaj, 

#Otrzymałeś|Otrzymałaś# zapytanie o kontakt wysłane przez #rb#! 
Odwiedź swój profil na PlayMaker.pro lub kliknij w poniższy link żeby podjąć decyzję o kontakcie: 
https://playmaker.pro/xyz/ 

Do zobaczenia na PlayMaker.pro!     

Pozdrawiamy,
Zespół PlayMaker.pro

Wiadomość została wygenerowana automatycznie. Prosimy na nią nie odpowiadać."""
    new_inquiry.send_mail = True
    new_inquiry.save()


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0006_alter_userinquirylog_ref"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inquirylogmessage",
            old_name="body",
            new_name="log_body",
        ),
        migrations.AddField(
            model_name="inquirylogmessage",
            name="send_mail",
            field=models.BooleanField(
                default=False,
                help_text="Should email be sent automatically when log is created?",
            ),
        ),
        migrations.AlterField(
            model_name="inquirylogmessage",
            name="log_body",
            field=models.TextField(
                blank=True,
                help_text="Message should include '<>' as placeholder for user related with log.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inquirylogmessage",
            name="email_body",
            field=models.TextField(
                blank=True,
                help_text="Type '#male_form|female_form#' - to mark something that should be determined by gender (e.g. #Otrzymałeś|Otrzymałaś#). <> - to include user related with log. '#r#' to include user related with log with role. '#rb#' to include user related with log with role in objective case (biernik).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inquirylogmessage",
            name="email_title",
            field=models.TextField(
                blank=True,
                help_text="Type '#male_form|female_form#' - to mark something that should be determined by gender (e.g. #Otrzymałeś|Otrzymałaś#). <> - to include user related with log. '#r#' to include user related with log with role. '#rb#' to include user related with log with role in objective case (biernik).",
                null=True,
            ),
        ),
        migrations.RunPython(create_initial_email_messages),
    ]
