# Generated by Django 3.1.2 on 2020-12-07 10:47

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0006_inquiryrequest_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryrequest',
            name='status',
            field=django_fsm.FSMField(choices=[('NOWE', 'NOWE'), ('WYSŁANO', 'WYSŁANO'), ('PRZECZYTANE', 'PRZECZYTANE'), ('ZAAKCEPTOWANE', 'ZAAKCEPTOWANE'), ('ODRZUCONE', 'ODRZUCONE')], default='NOWE', max_length=50),
        ),
    ]
