# Generated by Django 3.2.23 on 2023-11-23 14:47

from django.db import migrations, models

from inquiries.models import InquiryLogMessage as _InquiryLogMessage


def create_mail_template_for_outdated_inquiry(apps, schema_editor):
    """Add email template for outdated inquiry."""
    InquiryLogMessage = apps.get_model("inquiries", "InquiryLogMessage")

    outdated_inquiry: _InquiryLogMessage = InquiryLogMessage.objects.get(
        log_type=_InquiryLogMessage.MessageType.OUTDATED
    )
    outdated_inquiry.email_title = "Zwiększamy Twoją pulę zapytań o piłkarski kontakt!"
    outdated_inquiry.email_body = """Witaj!

Wygląda na to, że część Twoich zapytań o kontakt nie została odczytana przez odbiorców.
W związku z tym zwiększamy Twoją pulę zapytań dostępnych do wykorzystania do końca najbliższego okna transferowego.

Odwiedź swój profil na PlayMaker.pro lub kliknij w poniższy link i odkrywaj rynek transferowy:
#url#

Jeżeli po kliknięciu link się nie otworzy, skopiuj go, wklej w pole adresu przeglądarki i przejdź do wskazanej strony.

Pozdrawiamy,
Zespół PlayMaker.pro

Wiadomość została wygenerowana automatycznie. Prosimy na nią nie odpowiadać.
W przypadku pytań, jesteśmy dostępni pod adresem: biuro@playmaker.pro"""
    outdated_inquiry.send_mail = True
    outdated_inquiry.save()


def create_reminder_inquiry_log(apps, schema_editor) -> None:
    """
    Create new type of InquiryLogMessage - OUTDATED_REMINDER.
    For users that didn't respond to inquiry.
    """
    InquiryLogMessage: _InquiryLogMessage = apps.get_model(
        "inquiries", "InquiryLogMessage"
    )

    InquiryLogMessage.objects.create(
        log_type=_InquiryLogMessage.MessageType.OUTDATED_REMINDER,
        log_body="Zapytanie o kontakt od <> czeka na Twoją odpowiedź.",
        email_title="Masz zapytanie o piłkarski kontakt czekające na decyzję.",
        email_body="""Witaj!

Zapytanie o kontakt wysłane przez #rb# nadal czeka na Twoją odpowiedź.
Odwiedź swój profil na PlayMaker.pro lub kliknij w poniższy link żeby podjąć decyzję o kontakcie:
#url#

Do zobaczenia na PlayMaker.pro!

Pozdrawiamy,
Zespół PlayMaker.pro

Wiadomość została wygenerowana automatycznie. Prosimy na nią nie odpowiadać.""",
        send_mail=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0007_created_mail_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquirylogmessage",
            name="email_body",
            field=models.TextField(
                blank=True,
                help_text="Type '#male_form|female_form#' - to mark something that should be determined by gender (e.g. #Otrzymałeś|Otrzymałaś#).\n<> - to include user related with log.\n'#r#' to include user related with log with role.\n'#rb#' to include user related with log with role in objective case (biernik).\n#url# - to include additional url.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inquirylogmessage",
            name="email_title",
            field=models.TextField(
                blank=True,
                help_text="Type '#male_form|female_form#' - to mark something that should be determined by gender (e.g. #Otrzymałeś|Otrzymałaś#).\n<> - to include user related with log.\n'#r#' to include user related with log with role.\n'#rb#' to include user related with log with role in objective case (biernik).\n#url# - to include additional url.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inquirylogmessage",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("ACCEPTED_INQUIRY", "Accepted inquiry"),
                    ("REJECTED_INQUIRY", "Rejected inquiry"),
                    ("NEW_INQUIRY", "New inquiry"),
                    ("OUTDATED_INQUIRY", "Outdated inquiry"),
                    ("UNDEFINED_INQUIRY", "Undefined inquiry"),
                    ("OUTDATED_REMINDER", "Reminder about outdated inquiry"),
                ],
                default="UNDEFINED_INQUIRY",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.RunPython(create_reminder_inquiry_log),
        migrations.RunPython(create_mail_template_for_outdated_inquiry),
    ]
