# Generated by Django 3.1.2 on 2020-12-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0007_auto_20201207_1147"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiryrequest",
            name="body_recipient",
            field=models.TextField(blank=True, null=True),
        ),
    ]
