# Generated by Django 3.1.2 on 2021-01-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0008_inquiryrequest_body_recipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiryrequest",
            name="category",
            field=models.CharField(
                choices=[("user", "user"), ("team", "team")],
                default="user",
                max_length=255,
            ),
        ),
    ]
