# Generated by Django 3.2 on 2024-01-16 16:48

from django.db import migrations

from inquiries.models import InquiryLogMessage
from utils.constants import INQUIRY_CONTACT_URL


def update_email_urls(apps, schema_editor) -> None:
    """
    Updates the email URLs in InquiryLogMessage instances for specified log types.

    This function fetches InquiryLogMessage instances with specified log types and
    updates their email_body field to replace the old URL with the new one.
    """
    # Define the new URL
    new_url = INQUIRY_CONTACT_URL

    # List of log types to update
    log_types_to_update = [
        InquiryLogMessage.MessageType.ACCEPTED,
        InquiryLogMessage.MessageType.NEW,
    ]

    # Fetch and update messages for each log type
    for log_type in log_types_to_update:
        for message in InquiryLogMessage.objects.filter(log_type=log_type):
            message.email_body = message.email_body.replace(
                "https://playmaker.pro/xyz/", new_url
            )
            message.save()


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0008_auto_20231123_1547"),
    ]

    operations = [migrations.RunPython(update_email_urls)]
