# Generated by Django 3.2 on 2024-01-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0008_auto_20231123_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquirycontact',
            name='dial_code',
            field=models.IntegerField(blank=True, help_text='Country dial code for the phone number.', null=True, verbose_name='Dial Code'),
        ),
    ]
