# Generated by Django 3.2 on 2024-01-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0009_inquirycontact_dial_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquirycontact',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
