# Generated by Django 3.2 on 2024-01-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0009_auto_20240116_1748'),
        ('inquiries', '0010_rename_phone_inquirycontact_phone_number'),
    ]

    operations = [
    ]
