# Generated by Django 3.2.23 on 2024-01-21 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0010_rename_phone_inquirycontact_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inquiryrequest",
            name="body",
        ),
        migrations.RemoveField(
            model_name="inquiryrequest",
            name="body_recipient",
        ),
        migrations.DeleteModel(
            name="InquiryContact",
        ),
    ]
