# Generated by Django 3.2.23 on 2024-01-21 20:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0011_auto_20240121_1554"),
        ("inquiries", "0011_merge_20240120_1617"),
    ]

    operations = []
