# Generated by Django 3.2.23 on 2024-01-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0011_merge_20240120_1617"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiryplan",
            name="type_ref",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BASIC", "BASIC"),
                    ("PREMIUM_INQUIRIES_5", "PREMIUM_INQUIRIES_5"),
                    ("PREMIUM_INQUIRIES_10", "PREMIUM_INQUIRIES_10"),
                    ("PREMIUM_INQUIRIES_25", "PREMIUM_INQUIRIES_25"),
                ],
                help_text="Defines if this is premium plan and what type of premium plan it is.",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
