# Generated by Django 3.2.23 on 2024-01-30 17:23

from django.db import migrations

from inquiries.schemas import InquiryPlanTypeRef as _InquiryPlanTypeRef


def delete_premium_plan(apps, schema_editor):
    """Delete default premium plan (unused)."""
    InquiryPlan = apps.get_model("inquiries", "InquiryPlan")

    InquiryPlan.objects.filter(
        name="Premium", description="Premium plan", limit=10
    ).delete()


def mark_basic_type_ref(apps, schema_editor):
    """Mark the basic plan type_ref field."""
    InquiryPlan = apps.get_model("inquiries", "InquiryPlan")

    basic_plan = InquiryPlan.objects.filter(name="Basic", default=True).first()
    if basic_plan:
        basic_plan.type_ref = _InquiryPlanTypeRef.BASIC
        basic_plan.save()


def create_initial_premium_plans(apps, schema_editor):
    """Create initial premium plans."""
    InquiryPlan = apps.get_model("inquiries", "InquiryPlan")

    InquiryPlan.objects.get_or_create(
        name="Premium 5",
        description="Additional 5 inquiries",
        limit=5,
        type_ref="PREMIUM_INQUIRIES_5",
    )
    InquiryPlan.objects.get_or_create(
        name="Premium 10",
        description="Additional 10 inquiries",
        limit=10,
        type_ref="PREMIUM_INQUIRIES_10",
    )
    InquiryPlan.objects.get_or_create(
        name="Premium 25",
        description="Additional 25 inquiries",
        limit=25,
        type_ref="PREMIUM_INQUIRIES_25",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0012_inquiryplan_type_ref"),
    ]

    operations = [
        migrations.RunPython(
            delete_premium_plan, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            mark_basic_type_ref, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            create_initial_premium_plans, reverse_code=migrations.RunPython.noop
        ),
    ]
