# Generated by Django 3.2.23 on 2024-02-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0013_auto_20240130_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinquiry',
            name='limit',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
