# Generated by Django 3.2.23 on 2024-02-09 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0012_merge_20240121_2155'),
        ('inquiries', '0014_userinquiry_limit'),
    ]

    operations = [
    ]
