# Generated by Django 3.2 on 2024-02-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0015_merge_0012_merge_20240121_2155_0014_userinquiry_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryrequest',
            name='is_read_by_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiryrequest',
            name='is_read_by_sender',
            field=models.BooleanField(default=False),
        ),
    ]
