# Generated by Django 3.2.25 on 2024-11-21 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0016_auto_20240218_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinquiry',
            old_name='limit',
            new_name='limit_raw',
        ),
    ]
