# Generated by Django 3.2.25 on 2024-12-31 02:18

from django.db import migrations, models

from inquiries.schemas import InquiryPlanTypeRef


def delete_old_objects(apps, schema_editor):
    InquiryPlan = apps.get_model("inquiries", "InquiryPlan")

    InquiryPlan.objects.all().delete()


def create_new_objects(apps, schema_editor):
    InquiryPlan = apps.get_model("inquiries", "InquiryPlan")

    for inquiry_plan_ref in InquiryPlanTypeRef:
        data = {
            "type_ref": inquiry_plan_ref,
            "limit": inquiry_plan_ref.inquiry_count,
            "name": (
                f"Premium {inquiry_plan_ref.inquiry_count} zapytania"
                if inquiry_plan_ref != "BASIC"
                else "Podstawowy plan"
            ),
            "description": f"Dodatkowe {inquiry_plan_ref.inquiry_count} zapytań dostępne dla profilów premium"
            if inquiry_plan_ref != "BASIC"
            else "Podstawowy plan",
        }
        if inquiry_plan_ref == "BASIC":
            inquiry_plan = InquiryPlan.objects.create(default=True, **data)
        else:
            inquiry_plan = InquiryPlan.objects.create(**data)


def reset_all_inquiry_plans(apps, schema_editor):
    UserInquiry = apps.get_model("inquiries", "UserInquiry")
    InquiryPlan = apps.get_model("inquiries", "InquiryPlan")

    for user_inquiry in UserInquiry.objects.all():
        user_inquiry.plan = InquiryPlan.objects.get(default=True)
        user_inquiry.counter_raw = 0
        user_inquiry.limit_raw = user_inquiry.plan.limit
        user_inquiry.save()


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0017_rename_limit_userinquiry_limit_raw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiryplan",
            name="type_ref",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BASIC", "BASIC"),
                    ("PREMIUM_INQUIRIES_L", "PREMIUM_INQUIRIES_L"),
                    ("PREMIUM_INQUIRIES_XL", "PREMIUM_INQUIRIES_XL"),
                    ("PREMIUM_INQUIRIES_XXL", "PREMIUM_INQUIRIES_XXL"),
                ],
                help_text="Defines if this is premium plan and what type of premium plan it is.",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.RenameField(
            model_name="userinquiry",
            old_name="counter",
            new_name="counter_raw",
        ),
        migrations.AlterField(
            model_name="userinquiry",
            name="limit_raw",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.RunPython(
            delete_old_objects, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            create_new_objects, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            reset_all_inquiry_plans, reverse_code=migrations.RunPython.noop
        ),
    ]
