# Generated by Django 3.2.25 on 2024-12-31 02:18

import django.db.models.deletion
from django.db import migrations, models


def delete_old_objects(apps, schema_editor):
    InquiryPlan = apps.get_model("inquiries", "InquiryPlan")

    InquiryPlan.objects.all().delete()


def create_new_objects(apps, schema_editor):
    InquiryPlan = apps.get_model("inquiries", "InquiryPlan")

    # Hardcoded list of plan types that existed at the time of this migration
    # DO NOT use InquiryPlanTypeRef enum here as it may have new values added later
    plans_to_create = [
        {"type_ref": "BASIC", "limit": 2, "name": "Podstawowy plan", "description": "Podstawowy plan", "default": True},
        {"type_ref": "PREMIUM_INQUIRIES_L", "limit": 3, "name": "Premium 3 zapytania", "description": "Dodatkowe 3 zapytań dostępne dla profilów premium", "default": False},
        {"type_ref": "PREMIUM_INQUIRIES_XL", "limit": 5, "name": "Premium 5 zapytania", "description": "Dodatkowe 5 zapytań dostępne dla profilów premium", "default": False},
        {"type_ref": "PREMIUM_INQUIRIES_XXL", "limit": 10, "name": "Premium 10 zapytania", "description": "Dodatkowe 10 zapytań dostępne dla profilów premium", "default": False},
    ]

    for plan_data in plans_to_create:
        InquiryPlan.objects.create(**plan_data)


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0017_rename_limit_userinquiry_limit_raw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiryplan",
            name="type_ref",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BASIC", "BASIC"),
                    ("PREMIUM_INQUIRIES_L", "PREMIUM_INQUIRIES_L"),
                    ("PREMIUM_INQUIRIES_XL", "PREMIUM_INQUIRIES_XL"),
                    ("PREMIUM_INQUIRIES_XXL", "PREMIUM_INQUIRIES_XXL"),
                ],
                help_text="Defines if this is premium plan and what type of premium plan it is.",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="userinquiry",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inquiries.inquiryplan",
            ),
        ),
        migrations.RenameField(
            model_name="userinquiry",
            old_name="counter",
            new_name="counter_raw",
        ),
        migrations.AlterField(
            model_name="userinquiry",
            name="limit_raw",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.RunPython(
            delete_old_objects, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            create_new_objects, reverse_code=migrations.RunPython.noop
        ),
    ]
