# Generated by Django 3.2.25 on 2025-07-07 19:47

from django.db import migrations, models, transaction

from django.template.loader import render_to_string

def clear_email_body_html(apps, schema_editor):
    InquiryLogMessage = apps.get_model('inquiries', 'InquiryLogMessage')
    InquiryLogMessage.objects.update(email_body_html=None)


def populate_email_body_html(apps, schema_editor):
    InquiryLogMessage = apps.get_model('inquiries', 'InquiryLogMessage')

    with transaction.atomic():
        for log in InquiryLogMessage.objects.all():
            try:
                template_name = f"inquiries/emails/{log.log_type}.html"

                rendered_html = render_to_string(template_name)
                log.email_body_html = rendered_html
                log.save(update_fields=["email_body_html"])

            except Exception as e:

                raise Exception(f"Failed to render template for log {log.pk}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0019_auto_20250110_2311'),
    ]

    operations = [
        # 1. Add nullable field first
        migrations.AddField(
            model_name='inquirylogmessage',
            name='email_body_html',
            field=models.TextField(
                blank=True,
                null=True,
                help_text='HTML version of the email body. Supports HTML tags like <strong>, <a>, etc.'
            ),
        ),
        # 2. Populate the field with a reversible RunPython
        migrations.RunPython(populate_email_body_html, clear_email_body_html),
        # 3. Make the field non-nullable after data is populated
        migrations.AlterField(
            model_name='inquirylogmessage',
            name='email_body_html',
            field=models.TextField(
                blank=False,
                null=False,
                help_text='HTML version of the email body. Supports HTML tags like <strong>, <a>, etc.'
            ),
        ),
    ]
