# Generated by Django 3.2.25 on 2025-06-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0019_auto_20250110_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryrequest',
            name='anonymous_recipient',
            field=models.BooleanField(default=False),
        ),
    ]
