# Generated by Django 3.2.25 on 2025-08-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0020_inquiryrequest_anonymous_recipient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinquirylog",
            name="message",
        ),
        migrations.AddField(
            model_name="userinquiry",
            name="_last_limit_notification",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="userinquirylog",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("ACCEPTED_INQUIRY", "Accepted inquiry"),
                    ("REJECTED_INQUIRY", "Rejected inquiry"),
                    ("NEW_INQUIRY", "New inquiry"),
                    ("OUTDATED_INQUIRY", "Outdated inquiry"),
                    ("UNDEFINED_INQUIRY", "Undefined inquiry"),
                    ("OUTDATED_REMINDER", "Reminder about outdated inquiry"),
                ],
                default="UNDEFINED_INQUIRY",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="InquiryLogMessage",
        ),
    ]
