# Generated by Django 3.2.25 on 2025-07-17 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0020_auto_20250713_1235'),
        ('inquiries', '0020_inquiryrequest_anonymous_recipient'),
    ]

    operations = [
    ]
