# Generated by Django 3.2.25 on 2025-09-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0021_auto_20250802_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinquirylog',
            name='log_type',
            field=models.CharField(choices=[('ACCEPTED_INQUIRY', 'Accepted inquiry'), ('REJECTED_INQUIRY', 'Rejected inquiry'), ('NEW_INQUIRY', 'New inquiry'), ('OUTDATED_INQUIRY', 'Outdated inquiry'), ('UNDEFINED_INQUIRY', 'Undefined inquiry'), ('OUTDATED_REMINDER', 'Reminder about outdated inquiry'), ('NO_RESPONSE_REMINDER', 'No response reminder after 7 days')], default='UNDEFINED_INQUIRY', max_length=20),
        ),
    ]
