# Generated by Django 3.2.25 on 2025-09-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0022_alter_userinquirylog_log_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryrequest',
            name='recipient_anonymous_uuid',
            field=models.UUIDField(blank=True, help_text='Stores the anonymous UUID for recipient when anonymous_recipient=True. Preserves historical anonymity even if transfer objects are deleted.', null=True),
        ),
    ]
