# Generated by Django 3.2.23 on 2023-12-27 14:06

import uuid

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models

from payments.models import TransactionType as _TransactionType


def create_initial_transaction_types(apps, schema_editor) -> None:
    """Create initial transaction types for inquiries"""
    TransactionType = apps.get_model("payments", "TransactionType")
    TransactionType.objects.get_or_create(
        name="PREMIUM_INQUIRY_5",
        name_readable="5 zapytań",
        price=19.99,
        ref=_TransactionType.TransactionTypeRef.INQUIRIES,
    )
    TransactionType.objects.get_or_create(
        name="PREMIUM_INQUIRY_10",
        name_readable="10 zapytań",
        price=34.99,
        ref=_TransactionType.TransactionTypeRef.INQUIRIES,
    )
    TransactionType.objects.get_or_create(
        name="PREMIUM_INQUIRY_25",
        name_readable="25 zapytań",
        price=69.99,
        ref=_TransactionType.TransactionTypeRef.INQUIRIES,
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("name_readable", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "ref",
                    models.CharField(
                        choices=[("INQUIRIES", "INQUIRIES")], max_length=30
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_status",
                    django_fsm.FSMField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("SUCCESS", "SUCCESS"),
                            ("FAILED", "FAILED"),
                            ("OUTDATED", "OUTDATED"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("TRANSFER", "TRANSFER"), ("BLIK", "BLIK")],
                        max_length=30,
                    ),
                ),
                (
                    "error",
                    models.CharField(
                        blank=True,
                        choices=[("OVERPAID", "OVERPAID"), ("UNDERPAID", "UNDERPAID")],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payments.transactiontype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            create_initial_transaction_types, reverse_code=migrations.RunPython.noop
        ),
    ]
