# Generated by Django 3.2.23 on 2024-01-24 17:54

import uuid

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models

from inquiries.schemas import InquiryPlanTypeRef as _InquiryPlanTypeRef


def create_initial_inquiry_transaction_types(apps, schema_editor) -> None:
    """Create initial transaction types."""
    TransactionType = apps.get_model("payments", "TransactionType")

    TransactionType.objects.get_or_create(
        ref="INQUIRIES",
        name=_InquiryPlanTypeRef.PREMIUM5,
        name_readable="5 zapytań",
        price=19.99,
    )
    TransactionType.objects.get_or_create(
        ref="INQUIRIES",
        name=_InquiryPlanTypeRef.PREMIUM10,
        name_readable="10 zapytań",
        price=34.99,
    )
    TransactionType.objects.get_or_create(
        ref="INQUIRIES",
        name=_InquiryPlanTypeRef.PREMIUM25,
        name_readable="25 zapytań",
        price=69.99,
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("name_readable", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "ref",
                    models.CharField(
                        choices=[("INQUIRIES", "INQUIRIES")], max_length=30
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_status",
                    django_fsm.FSMField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("SUCCESS", "SUCCESS"),
                            ("FAILED", "FAILED"),
                            ("OUTDATED", "OUTDATED"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "error",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("overpay", "OVERPAID"),
                            ("surcharge", "UNDERPAID"),
                            ("none", "NONE"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("raw_create_response", models.JSONField(blank=True, null=True)),
                ("raw_resolve_response", models.JSONField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payments.transactiontype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            create_initial_inquiry_transaction_types,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
