# Generated by Django 3.2.23 on 2024-01-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactiontype",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
