# Generated by Django 3.2.23 on 2024-02-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transactiontype_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='validation_errors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
