# Generated by Django 3.2.25 on 2024-11-19 17:35

import django.db.models.deletion
from django.db import migrations, models

from inquiries.schemas import InquiryPlanTypeRef

new_naming = {
    "PREMIUM_INQUIRIES_5": InquiryPlanTypeRef.PREMIUM_L,
    "PREMIUM_INQUIRIES_10": InquiryPlanTypeRef.PREMIUM_XL,
    "PREMIUM_INQUIRIES_25": InquiryPlanTypeRef.PREMIUM_XXL,
}


def map_transaction_types_to_products(apps, schema_editor):
    Product = apps.get_model("premium", "Product")
    Transaction = apps.get_model("payments", "Transaction")

    for transaction in Transaction.objects.all():
        product = Product.objects.get(
            name=new_naming[transaction.transaction_type.name]
        )
        transaction.product = product
        transaction.save()


class Migration(migrations.Migration):
    dependencies = [
        ("premium", "0005_products"),
        ("payments", "0003_transaction_validation_errors"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="premium.product",
            ),
        ),
        migrations.RunPython(
            map_transaction_types_to_products, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="transaction_type",
        ),
        migrations.DeleteModel(
            name="TransactionType",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="premium.product"
            ),
        ),
    ]
