# Generated by Django 3.1 on 2020-08-31 21:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('slug', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y-%m-%d/', verbose_name='Profile picture')),
                ('bio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Bio')),
                ('email_verified', models.BooleanField(default=False, help_text='When user recieve confiramion and confirm it.', verbose_name='Email verified')),
                ('account_verified', models.BooleanField(default=False, help_text='Manually confirmed by Admin. This means that user is participant of soocer community.', verbose_name='Account verified')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('slug', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y-%m-%d/', verbose_name='Profile picture')),
                ('bio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Bio')),
                ('email_verified', models.BooleanField(default=False, help_text='When user recieve confiramion and confirm it.', verbose_name='Email verified')),
                ('account_verified', models.BooleanField(default=False, help_text='Manually confirmed by Admin. This means that user is participant of soocer community.', verbose_name='Account verified')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('slug', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y-%m-%d/', verbose_name='Profile picture')),
                ('bio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Bio')),
                ('email_verified', models.BooleanField(default=False, help_text='When user recieve confiramion and confirm it.', verbose_name='Email verified')),
                ('account_verified', models.BooleanField(default=False, help_text='Manually confirmed by Admin. This means that user is participant of soocer community.', verbose_name='Account verified')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('slug', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y-%m-%d/', verbose_name='Profile picture')),
                ('bio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Bio')),
                ('email_verified', models.BooleanField(default=False, help_text='When user recieve confiramion and confirm it.', verbose_name='Email verified')),
                ('account_verified', models.BooleanField(default=False, help_text='Manually confirmed by Admin. This means that user is participant of soocer community.', verbose_name='Account verified')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('height', models.PositiveIntegerField(blank=True, help_text='Height (cm)', null=True, verbose_name='Height')),
                ('weight', models.PositiveIntegerField(blank=True, help_text='Weight (kg)', null=True, verbose_name='Weight')),
                ('club_raw', models.CharField(blank=True, max_length=68, null=True, verbose_name='Club name')),
                ('league_raw', models.CharField(blank=True, max_length=68, null=True, verbose_name='League name')),
                ('voivodeship_raw', models.CharField(blank=True, max_length=68, null=True, verbose_name='Voivodeship name')),
                ('position_raw', models.CharField(blank=True, choices=[('GK', 'Bramkarz'), ('DL', 'Obrońca Lewy')], max_length=30, null=True, verbose_name='Position name')),
            ],
            options={
                'verbose_name': 'Player Profile',
                'verbose_name_plural': 'Player Profiles',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('slug', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y-%m-%d/', verbose_name='Profile picture')),
                ('bio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Bio')),
                ('email_verified', models.BooleanField(default=False, help_text='When user recieve confiramion and confirm it.', verbose_name='Email verified')),
                ('account_verified', models.BooleanField(default=False, help_text='Manually confirmed by Admin. This means that user is participant of soocer community.', verbose_name='Account verified')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleChangeRequest',
            fields=[
                ('user', models.OneToOneField(help_text='User who requested change', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='requestor', serialize=False, to='users.user')),
                ('approved', models.BooleanField(default=False, help_text='Defines if admin approved change')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('accepted_date', models.DateTimeField(auto_now=True)),
                ('current', models.CharField(max_length=100)),
                ('new', models.CharField(max_length=100)),
            ],
        ),
    ]
