# Generated by Django 3.1 on 2020-10-17 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachprofile',
            options={'verbose_name': 'Coach Profile', 'verbose_name_plural': 'Coach Profiles'},
        ),
    ]
