# Generated by Django 3.2 on 2022-07-16 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voivodeships", "0003_auto_20220715_1633"),
        ("profiles", "0001_squashed_0072_auto_20220627_2313"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachprofile",
            name="voivodeship_obj",
            field=models.ForeignKey(
                blank=True,
                help_text="Wybierz województwo.",
                max_length=20,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="voivodeships.voivodeships",
                verbose_name="Województwo zamieszkania",
            ),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="voivodeship_obj",
            field=models.ForeignKey(
                blank=True,
                help_text="Wybierz województwo.",
                max_length=20,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="voivodeships.voivodeships",
                verbose_name="Województwo zamieszkania",
            ),
        ),
        migrations.AddField(
            model_name="scoutprofile",
            name="voivodeship_obj",
            field=models.ForeignKey(
                blank=True,
                help_text="Wybierz województwo.",
                max_length=20,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="voivodeships.voivodeships",
                verbose_name="Województwo zamieszkania",
            ),
        ),
        migrations.AlterField(
            model_name="coachprofile",
            name="voivodeship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Dolnośląskie", "Dolnośląskie"),
                    ("Kujawsko-pomorskie", "Kujawsko-pomorskie"),
                    ("Lubelskie", "Lubelskie"),
                    ("Lubuskie", "Lubuskie"),
                    ("Łódzkie", "Łódzkie"),
                    ("Małopolskie", "Małopolskie"),
                    ("Mazowieckie", "Mazowieckie"),
                    ("Opolskie", "Opolskie"),
                    ("Podkarpackie", "Podkarpackie"),
                    ("Podlaskie", "Podlaskie"),
                    ("Pomorskie", "Pomorskie"),
                    ("Śląskie", "Śląskie"),
                    ("Świętokrzyskie", "Świętokrzyskie"),
                    ("Warmińsko-Mazurskie", "Warmińsko-Mazurskie"),
                    ("Wielkopolskie", "Wielkopolskie"),
                    ("Zachodniopomorskie", "Zachodniopomorskie"),
                ],
                help_text="Wybierz województwo. Stare pole przygotowane do migracji",
                max_length=68,
                null=True,
                verbose_name="Województwo zamieszkania.",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="voivodeship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Dolnośląskie", "Dolnośląskie"),
                    ("Kujawsko-pomorskie", "Kujawsko-pomorskie"),
                    ("Lubelskie", "Lubelskie"),
                    ("Lubuskie", "Lubuskie"),
                    ("Łódzkie", "Łódzkie"),
                    ("Małopolskie", "Małopolskie"),
                    ("Mazowieckie", "Mazowieckie"),
                    ("Opolskie", "Opolskie"),
                    ("Podkarpackie", "Podkarpackie"),
                    ("Podlaskie", "Podlaskie"),
                    ("Pomorskie", "Pomorskie"),
                    ("Śląskie", "Śląskie"),
                    ("Świętokrzyskie", "Świętokrzyskie"),
                    ("Warmińsko-Mazurskie", "Warmińsko-Mazurskie"),
                    ("Wielkopolskie", "Wielkopolskie"),
                    ("Zachodniopomorskie", "Zachodniopomorskie"),
                ],
                help_text="Wybierz województwo. Stare pole przygotowane do migracji.",
                max_length=68,
                null=True,
                verbose_name="Województwo zamieszkania",
            ),
        ),
        migrations.AlterField(
            model_name="scoutprofile",
            name="voivodeship",
            field=models.CharField(
                blank=True,
                help_text="Wojewódźtwo. Stare pole, czeka na migracje",
                max_length=68,
                null=True,
                verbose_name="Wojewódźtwo",
            ),
        ),
    ]
