# Generated by Django 3.2 on 2022-08-07 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0069_teamhistory"),
        ("profiles", "0001_squashed_0072_auto_20220627_2313"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="team_history_object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="players",
                to="clubs.teamhistory",
            ),
        ),
    ]
