# Generated by Django 3.2 on 2022-08-07 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0069_teamhistory"),
        ("profiles", "0002_playerprofile_team_history_object"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachprofile",
            name="team_history_object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="players_history",
                to="clubs.teamhistory",
            ),
        ),
    ]
