# Generated by Django 3.1 on 2020-10-17 21:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_auto_20201017_2222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='StandardProfile',
        ),
    ]
