# Generated by Django 3.2 on 2022-08-08 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0072_alter_teamhistory_league"),
        ("profiles", "0003_coachprofile_team_history_object"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileverificationstatus",
            name="team_history",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_history",
                to="clubs.teamhistory",
            ),
        ),
    ]
