# Generated by Django 3.1.2 on 2020-11-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_auto_20201109_1443"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerprofile",
            name="alt_formation",
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="formation_alt",
            field=models.CharField(
                blank=True,
                choices=[
                    ("5-3-2", "5-3-2"),
                    ("5-4-1", "5-4-1"),
                    ("4-4-2", "4-4-2"),
                    ("4-5-1", "4-5-1"),
                    ("4-3-3", "4-3-3"),
                    ("4-2-3-1", "4-2-3-1"),
                    ("4-1-4-1", "4-1-4-1"),
                    ("4-3-2-1", "4-3-2-1"),
                    ("3-5-2", "3-5-2"),
                    ("3-4-3", "3-4-3"),
                ],
                max_length=11,
                null=True,
                verbose_name="Alternative formation",
            ),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="position_fantasy",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "Bramkarz"),
                    (2, "Obrońca Lewy"),
                    (3, "Obrońca Prawy"),
                    (4, "Obrońca Środkowy"),
                    (5, "Pomocnik defensywny (6)"),
                    (6, "Pomocnik środkowy (8)"),
                    (7, "Pomocnik ofensywny (10)"),
                    (8, "Skrzydłowy"),
                    (9, "Napastnik"),
                ],
                max_length=35,
                null=True,
                verbose_name="Position name",
            ),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="position_raw_alt",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "Bramkarz"),
                    (2, "Obrońca Lewy"),
                    (3, "Obrońca Prawy"),
                    (4, "Obrońca Środkowy"),
                    (5, "Pomocnik defensywny (6)"),
                    (6, "Pomocnik środkowy (8)"),
                    (7, "Pomocnik ofensywny (10)"),
                    (8, "Skrzydłowy"),
                    (9, "Napastnik"),
                ],
                max_length=35,
                null=True,
                verbose_name="Position name",
            ),
        ),
        migrations.AlterField(
            model_name="clubprofile",
            name="data_mapper_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID of object placed in data_ database. It should alwayes reflect scheme which represents.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="coachprofile",
            name="data_mapper_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID of object placed in data_ database. It should alwayes reflect scheme which represents.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fanprofile",
            name="data_mapper_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID of object placed in data_ database. It should alwayes reflect scheme which represents.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="guestprofile",
            name="data_mapper_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID of object placed in data_ database. It should alwayes reflect scheme which represents.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="managerprofile",
            name="data_mapper_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID of object placed in data_ database. It should alwayes reflect scheme which represents.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="parentprofile",
            name="data_mapper_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID of object placed in data_ database. It should alwayes reflect scheme which represents.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="data_mapper_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID of object placed in data_ database. It should alwayes reflect scheme which represents.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="position_raw",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "Bramkarz"),
                    (2, "Obrońca Lewy"),
                    (3, "Obrońca Prawy"),
                    (4, "Obrońca Środkowy"),
                    (5, "Pomocnik defensywny (6)"),
                    (6, "Pomocnik środkowy (8)"),
                    (7, "Pomocnik ofensywny (10)"),
                    (8, "Skrzydłowy"),
                    (9, "Napastnik"),
                ],
                max_length=35,
                null=True,
                verbose_name="Position name",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="prefered_leg",
            field=models.CharField(
                blank=True,
                choices=[("Lewa", "Lewa"), ("Prawa", "Prawa")],
                max_length=30,
                null=True,
                verbose_name="Prefered leg",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="transfer_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SC", "Szukam klubu"),
                    ("RO", "Rozważę wszelkie oferty"),
                    ("NC", "Nie szukam klubu"),
                ],
                max_length=45,
                null=True,
                verbose_name="Transfer status",
            ),
        ),
        migrations.AlterField(
            model_name="rolechangerequest",
            name="new",
            field=models.CharField(
                choices=[
                    ("P", "Piłkarz"),
                    ("T", "Trener"),
                    ("G", "Gość"),
                    ("C", "Klub / Szkółka"),
                    ("SK", "Scout"),
                    ("R", "Rodzic"),
                    ("K", "Kibic"),
                    ("M", "Manadżer"),
                    ("S", "Standardowe"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="scoutprofile",
            name="data_mapper_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID of object placed in data_ database. It should alwayes reflect scheme which represents.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="standardprofile",
            name="data_mapper_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID of object placed in data_ database. It should alwayes reflect scheme which represents.",
                null=True,
            ),
        ),
    ]
