# Generated by Django 3.1 on 2020-10-17 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201017_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubprofile',
            options={'verbose_name': 'Coach Profile', 'verbose_name_plural': 'Coach Profiles'},
        ),
        migrations.AlterModelOptions(
            name='guestprofile',
            options={'verbose_name': 'Guest Profile', 'verbose_name_plural': 'Guest Profiles'},
        ),
    ]
