# Generated by Django 3.1.2 on 2020-11-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_auto_20201112_1223"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerprofile",
            name="card",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MKN", "Mam kartę na ręku"),
                    ("NCMKN", "Nie wiem czy mam kartę na ręku"),
                    ("NKN", "Nie mam karty na ręku"),
                ],
                max_length=60,
                null=True,
                verbose_name="Karta na ręku",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="formation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("5-3-2", "5-3-2"),
                    ("5-4-1", "5-4-1"),
                    ("4-4-2", "4-4-2"),
                    ("4-5-1", "4-5-1"),
                    ("4-3-3", "4-3-3"),
                    ("4-2-3-1", "4-2-3-1"),
                    ("4-1-4-1", "4-1-4-1"),
                    ("4-3-2-1", "4-3-2-1"),
                    ("3-5-2", "3-5-2"),
                    ("3-4-3", "3-4-3"),
                ],
                max_length=11,
                null=True,
                verbose_name="Formacja",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="formation_alt",
            field=models.CharField(
                blank=True,
                choices=[
                    ("5-3-2", "5-3-2"),
                    ("5-4-1", "5-4-1"),
                    ("4-4-2", "4-4-2"),
                    ("4-5-1", "4-5-1"),
                    ("4-3-3", "4-3-3"),
                    ("4-2-3-1", "4-2-3-1"),
                    ("4-1-4-1", "4-1-4-1"),
                    ("4-3-2-1", "4-3-2-1"),
                    ("3-5-2", "3-5-2"),
                    ("3-4-3", "3-4-3"),
                ],
                max_length=11,
                null=True,
                verbose_name="Alternatywna formacja",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="position_fantasy",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "Bramkarz"),
                    (2, "Obrońca Lewy"),
                    (3, "Obrońca Prawy"),
                    (4, "Obrońca Środkowy"),
                    (5, "Pomocnik defensywny (6)"),
                    (6, "Pomocnik środkowy (8)"),
                    (7, "Pomocnik ofensywny (10)"),
                    (8, "Skrzydłowy"),
                    (9, "Napastnik"),
                ],
                max_length=35,
                null=True,
                verbose_name="Pozycja Fantasy",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="position_raw_alt",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "Bramkarz"),
                    (2, "Obrońca Lewy"),
                    (3, "Obrońca Prawy"),
                    (4, "Obrońca Środkowy"),
                    (5, "Pomocnik defensywny (6)"),
                    (6, "Pomocnik środkowy (8)"),
                    (7, "Pomocnik ofensywny (10)"),
                    (8, "Skrzydłowy"),
                    (9, "Napastnik"),
                ],
                max_length=35,
                null=True,
                verbose_name="Pozycja alternat",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="prefered_leg",
            field=models.CharField(
                blank=True,
                choices=[("Lewa", "Lewa"), ("Prawa", "Prawa")],
                max_length=30,
                null=True,
                verbose_name="Noga",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="soccer_goal",
            field=models.CharField(
                blank=True,
                choices=[
                    (0, "Ekstraklasa"),
                    (1, "1 liga"),
                    (2, "2 liga"),
                    (3, "3 liga"),
                    (4, "4 liga"),
                    (5, "5 liga"),
                    (6, "A klasa"),
                    (7, "B klasa"),
                ],
                max_length=60,
                null=True,
                verbose_name="Karta na ręku",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="transfer_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SC", "Szukam klubu"),
                    ("RO", "Rozważę wszelkie oferty"),
                    ("NC", "Nie szukam klubu"),
                ],
                max_length=45,
                null=True,
                verbose_name="Status transferowy",
            ),
        ),
    ]
