# Generated by Django 3.1 on 2020-10-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20201018_0107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standardprofile',
            options={'verbose_name': 'Standard Profile', 'verbose_name_plural': 'Standard Profiles'},
        ),
        migrations.RemoveField(
            model_name='rolechangerequest',
            name='user',
        ),
        migrations.AddField(
            model_name='rolechangerequest',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rolechangerequest',
            name='current',
            field=models.CharField(choices=[('P', 'Piłkarz'), ('T', 'Trener')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rolechangerequest',
            name='new',
            field=models.CharField(choices=[('P', 'Piłkarz'), ('T', 'Trener')], max_length=100),
        ),
    ]
