# Generated by Django 3.1 on 2020-10-18 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_auto_20201018_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolechangerequest',
            name='user',
            field=models.OneToOneField(default=1, help_text='User who requested change', on_delete=django.db.models.deletion.CASCADE, related_name='requestor', to='users.user'),
            preserve_default=False,
        ),
    ]
