# Generated by Django 3.1.2 on 2020-11-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201112_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='prefered_leg',
            field=models.CharField(blank=True, choices=[('L', 'Lewa'), ('P', 'Prawa')], max_length=30, null=True, verbose_name='Noga'),
        ),
    ]
