# Generated by Django 3.1.2 on 2020-11-12 15:14

import address.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('profiles', '0006_auto_20201112_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nazwisko')),
                ('season', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sezon')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='adres e-mail')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telefon')),
            ],
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='lnp_url',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='O sobie'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='agent_name',
            field=models.BooleanField(blank=True, null=True, verbose_name='Otwarty na propozycje zagraniczne'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='agent_status',
            field=models.CharField(blank=True, choices=[(1, 'Mam agenta'), (2, 'Szukam agenta'), (3, 'Nie szukam agenta')], max_length=45, null=True, verbose_name='Czy Agent'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='laczynaspilka_url',
            field=models.URLField(blank=True, null=True, verbose_name='LNP'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='training_ready',
            field=models.CharField(blank=True, choices=[(1, '1-2 treningi'), (2, '3-4 treningi'), (3, '5-6 treningi')], max_length=250, null=True, verbose_name='Gotowość do treningu'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data urodzenia'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='club_raw',
            field=models.CharField(blank=True, max_length=68, null=True, verbose_name='Klub'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Height (cm)', null=True, validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(210)], verbose_name='Wzrost'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='league_raw',
            field=models.CharField(blank=True, max_length=68, null=True, verbose_name='Rozgrywki'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='min90_url',
            field=models.URLField(blank=True, null=True, verbose_name='90min portal'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Numer telefonu do agenta / agencji'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='position_raw',
            field=models.CharField(blank=True, choices=[(1, 'Bramkarz'), (2, 'Obrońca Lewy'), (3, 'Obrońca Prawy'), (4, 'Obrońca Środkowy'), (5, 'Pomocnik defensywny (6)'), (6, 'Pomocnik środkowy (8)'), (7, 'Pomocnik ofensywny (10)'), (8, 'Skrzydłowy'), (9, 'Napastnik')], max_length=35, null=True, verbose_name='Pozycja'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='practice_distance',
            field=models.PositiveIntegerField(blank=True, help_text='max practice distance', null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)], verbose_name='Maksymalna odległość na trening'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='soccer_goal',
            field=models.CharField(blank=True, choices=[(0, 'Ekstraklasa'), (1, '1 liga'), (2, '2 liga'), (3, '3 liga'), (4, '4 liga'), (5, '5 liga'), (6, 'A klasa'), (7, 'B klasa')], max_length=60, null=True, verbose_name='Piłkarski cel'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='team_raw',
            field=models.CharField(blank=True, max_length=68, null=True, verbose_name='Drużyna'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='transfermarket_url',
            field=models.URLField(blank=True, null=True, verbose_name='TrasferMarket'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='voivodeship_raw',
            field=models.CharField(blank=True, max_length=68, null=True, verbose_name='Wojewódźtwo'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='Weight (kg)', null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(140)], verbose_name='Waga'),
        ),
    ]
