# Generated by Django 3.1 on 2020-10-18 11:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0006_rolechangerequest_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolechangerequest',
            unique_together={('user', 'request_date')},
        ),
    ]
