# Generated by Django 3.1 on 2020-10-18 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0007_auto_20201018_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolechangerequest',
            name='user',
            field=models.OneToOneField(help_text='User who requested change', on_delete=django.db.models.deletion.CASCADE, related_name='changerolerequestor', to=settings.AUTH_USER_MODEL),
        ),
    ]
