# Generated by Django 3.1 on 2020-10-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20201018_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubprofile',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='coachprofile',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='standardprofile',
            name='picture',
        ),
    ]
