# Generated by Django 3.1 on 2020-10-18 18:09

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20201018_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='soccer_goal',
            field=models.CharField(blank=True, choices=[('P', 'Profesjonalna kariera'), ('KR', 'Kariera regionalna'), ('H', 'Trenerka jako hobby')], max_length=60, null=True, verbose_name='soccer goal'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='alt_formation',
            field=models.CharField(blank=True, choices=[(1, '5-3-2'), (2, '5-4-1'), (3, '4-4-2'), (4, '4-5-1'), (5, '4-3-3'), (6, '4-2-3-1'), (7, '4-1-4-1'), (8, '4-3-2-1'), (9, '3-5-2'), (10, '3-4-3')], max_length=11, null=True, verbose_name='Formation'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='card',
            field=models.CharField(blank=True, choices=[('MKN', 'Mam kartę na ręku'), ('NCMKN', 'Nie wiem czy mam kartę na ręku'), ('NKN', 'Nie mam karty na ręku')], max_length=60, null=True, verbose_name='karta na ręku'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='formation',
            field=models.CharField(blank=True, choices=[(1, '5-3-2'), (2, '5-4-1'), (3, '4-4-2'), (4, '4-5-1'), (5, '4-3-3'), (6, '4-2-3-1'), (7, '4-1-4-1'), (8, '4-3-2-1'), (9, '3-5-2'), (10, '3-4-3')], max_length=11, null=True, verbose_name='Formation'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='lnp_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='min90_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='practice_distance',
            field=models.PositiveIntegerField(blank=True, help_text='max practice distance', null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)], verbose_name='max practice distance'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='prefered_leg',
            field=models.CharField(blank=True, choices=[('L', 'Lewa'), ('P', 'Prawa')], max_length=30, null=True, verbose_name='prefered leg'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='soccer_goal',
            field=models.CharField(blank=True, choices=[(0, 'Ekstraklasa'), (1, '1 liga'), (2, '2 liga'), (3, '3 liga'), (4, '4 liga'), (5, '5 liga'), (6, 'A klasa'), (7, 'B klasa')], max_length=60, null=True, verbose_name='karta na ręku'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='team_raw',
            field=models.CharField(blank=True, max_length=68, null=True, verbose_name='Club name'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='transfer_status',
            field=models.CharField(blank=True, choices=[('SC', 'Szukam klubu'), ('RO', 'Rozważę wszelkie oferty'), ('NC', 'Nie szukam klubu')], max_length=45, null=True, verbose_name='transfer status'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='transfermarket_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Height (cm)', null=True, validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(210)], verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='Weight (kg)', null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(140)], verbose_name='Weight'),
        ),
    ]
