# Generated by Django 3.1.2 on 2020-11-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_auto_20201112_1643"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerprofile",
            name="card",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Mam kartę na ręku"),
                    (2, "Nie wiem czy mam kartę na ręku"),
                    (3, "Nie mam karty na ręku"),
                ],
                null=True,
                verbose_name="Karta na ręku",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="formation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("5-3-2", "5-3-2"),
                    ("5-4-1", "5-4-1"),
                    ("4-4-2", "4-4-2"),
                    ("4-5-1", "4-5-1"),
                    ("4-3-3", "4-3-3"),
                    ("4-2-3-1", "4-2-3-1"),
                    ("4-1-4-1", "4-1-4-1"),
                    ("4-3-2-1", "4-3-2-1"),
                    ("3-5-2", "3-5-2"),
                    ("3-4-3", "3-4-3"),
                ],
                max_length=15,
                null=True,
                verbose_name="Formacja",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="formation_alt",
            field=models.CharField(
                blank=True,
                choices=[
                    ("5-3-2", "5-3-2"),
                    ("5-4-1", "5-4-1"),
                    ("4-4-2", "4-4-2"),
                    ("4-5-1", "4-5-1"),
                    ("4-3-3", "4-3-3"),
                    ("4-2-3-1", "4-2-3-1"),
                    ("4-1-4-1", "4-1-4-1"),
                    ("4-3-2-1", "4-3-2-1"),
                    ("3-5-2", "3-5-2"),
                    ("3-4-3", "3-4-3"),
                ],
                max_length=15,
                null=True,
                verbose_name="Alternatywna formacja",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="position_fantasy",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Bramkarz"),
                    (2, "Obrońca Lewy"),
                    (3, "Obrońca Prawy"),
                    (4, "Obrońca Środkowy"),
                    (5, "Pomocnik defensywny (6)"),
                    (6, "Pomocnik środkowy (8)"),
                    (7, "Pomocnik ofensywny (10)"),
                    (8, "Skrzydłowy"),
                    (9, "Napastnik"),
                ],
                null=True,
                verbose_name="Pozycja Fantasy",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="position_raw_alt",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Bramkarz"),
                    (2, "Obrońca Lewy"),
                    (3, "Obrońca Prawy"),
                    (4, "Obrońca Środkowy"),
                    (5, "Pomocnik defensywny (6)"),
                    (6, "Pomocnik środkowy (8)"),
                    (7, "Pomocnik ofensywny (10)"),
                    (8, "Skrzydłowy"),
                    (9, "Napastnik"),
                ],
                null=True,
                verbose_name="Pozycja alternat",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="prefered_leg",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Lewa"), (2, "Prawa")],
                null=True,
                verbose_name="Noga",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="soccer_goal",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Ekstraklasa"),
                    (1, "1 liga"),
                    (2, "2 liga"),
                    (3, "3 liga"),
                    (4, "4 liga"),
                    (5, "5 liga"),
                    (6, "A klasa"),
                    (7, "B klasa"),
                ],
                null=True,
                verbose_name="Piłkarski cel",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="transfer_status",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Szukam klubu"),
                    (2, "Rozważę wszelkie oferty"),
                    (3, "Nie szukam klubu"),
                ],
                null=True,
                verbose_name="Status transferowy",
            ),
        ),
    ]
