# Generated by Django 3.1.2 on 2020-11-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20201112_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='position_fantasy',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Pozycja Fantasy'),
        ),
    ]
