# Generated by Django 3.1.2 on 2020-11-02 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_completeprofileteaser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolechangerequest',
            name='current',
        ),
    ]
