# Generated by Django 3.1.2 on 2020-11-02 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0012_remove_rolechangerequest_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolechangerequest',
            name='approver',
            field=models.ForeignKey(default=1, help_text='Admin who verified.', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
