# Generated by Django 3.1.2 on 2020-11-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20201113_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='position_raw',
            field=models.CharField(blank=True, choices=[('B', 'Bramkarz'), ('OL', 'Obrońca Lewy'), ('OP', 'Obrońca Prawy'), ('OS', 'Obrońca Środkowy'), ('PD', 'Pomocnik defensywny (6)'), ('PS', 'Pomocnik środkowy (8)'), ('PO', 'Pomocnik ofensywny (10)'), ('S', 'Skrzydłowy'), ('N', 'Napastnik')], max_length=200, null=True, verbose_name='Pozycja'),
        ),
    ]
