# Generated by Django 3.1.2 on 2020-11-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20201102_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='soccer_goal',
            field=models.CharField(blank=True, choices=[('Profesjonalna kariera', 'Profesjonalna kariera'), ('Kariera regionalna', 'Kariera regionalna'), ('Trenerka jako hobby', 'Trenerka jako hobby')], max_length=60, null=True, verbose_name='soccer goal'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='alt_formation',
            field=models.CharField(blank=True, choices=[('5-3-2', '5-3-2'), ('5-4-1', '5-4-1'), ('4-4-2', '4-4-2'), ('4-5-1', '4-5-1'), ('4-3-3', '4-3-3'), ('4-2-3-1', '4-2-3-1'), ('4-1-4-1', '4-1-4-1'), ('4-3-2-1', '4-3-2-1'), ('3-5-2', '3-5-2'), ('3-4-3', '3-4-3')], max_length=11, null=True, verbose_name='Formation'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='formation',
            field=models.CharField(blank=True, choices=[('5-3-2', '5-3-2'), ('5-4-1', '5-4-1'), ('4-4-2', '4-4-2'), ('4-5-1', '4-5-1'), ('4-3-3', '4-3-3'), ('4-2-3-1', '4-2-3-1'), ('4-1-4-1', '4-1-4-1'), ('4-3-2-1', '4-3-2-1'), ('3-5-2', '3-5-2'), ('3-4-3', '3-4-3')], max_length=11, null=True, verbose_name='Formation'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='prefered_leg',
            field=models.CharField(blank=True, choices=[('Lewa', 'Lewa'), ('Prawa', 'Prawa')], max_length=30, null=True, verbose_name='prefered leg'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='team_raw',
            field=models.CharField(blank=True, max_length=68, null=True, verbose_name='Team name'),
        ),
        migrations.AlterField(
            model_name='rolechangerequest',
            name='new',
            field=models.CharField(choices=[('P', 'Piłkarz'), ('T', 'Trener'), ('G', 'Gość'), ('C', 'Klub')], max_length=100),
        ),
    ]
