# Generated by Django 3.1.2 on 2020-11-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20201105_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubprofile',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='guestprofile',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='standardprofile',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
