# Generated by Django 3.1.2 on 2020-11-05 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0016_auto_20201105_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolechangerequest',
            name='approver',
            field=models.ForeignKey(help_text='Admin who verified.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
