# Generated by Django 3.1.2 on 2020-11-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0016_auto_20201117_0244"),
    ]

    operations = [
        migrations.AddField(
            model_name="playermetrics",
            name="fantasy",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playermetrics",
            name="games",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playermetrics",
            name="season",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playermetrics",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
