# Generated by Django 3.1.2 on 2020-11-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0017_auto_20201117_0326"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="team_club_league_voivodeship_ver",
            field=models.CharField(
                blank=True,
                help_text="Drużyna, klub, rozgrywki, wojewódźtwo.",
                max_length=355,
                null=True,
                verbose_name="team_club_league_voivodeship_ver",
            ),
        ),
    ]
