# Generated by Django 3.1.2 on 2020-11-06 16:04

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20201105_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Club name'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth date'),
        ),
    ]
