# Generated by Django 3.1.2 on 2020-11-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0018_playerprofile_team_club_league_voivodeship_ver"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="club",
            field=models.CharField(
                blank=True,
                help_text="Klub w którym obecnie reprezentuejsz",
                max_length=68,
                null=True,
                verbose_name="Klub",
            ),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="league",
            field=models.CharField(
                blank=True,
                help_text="Poziom rozgrywkowy",
                max_length=68,
                null=True,
                verbose_name="Deklarowane Rozgrywki",
            ),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="team",
            field=models.CharField(
                blank=True,
                help_text="Drużyna w której obecnie grasz",
                max_length=68,
                null=True,
                verbose_name="Drużyna",
            ),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="voivodeship",
            field=models.CharField(
                blank=True,
                help_text="Wojewódźtwo",
                max_length=68,
                null=True,
                verbose_name="Deklarowane Wojewódźtwo",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="club_raw",
            field=models.CharField(
                blank=True,
                help_text="Klub w którym obecnie reprezentuejsz",
                max_length=68,
                null=True,
                verbose_name="Deklarowany Klub",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="team_raw",
            field=models.CharField(
                blank=True,
                help_text="Drużyna w której obecnie grasz",
                max_length=68,
                null=True,
                verbose_name="Deklarowana Drużyna",
            ),
        ),
    ]
