# Generated by Django 3.1.2 on 2020-11-06 18:39

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20201106_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country'),
        ),
    ]
