# Generated by Django 3.1.2 on 2020-11-07 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20201107_1846'),
        ('profiles', '0019_auto_20201106_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('slug', models.CharField(blank=True, editable=False, max_length=255)),
                ('bio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Bio')),
                ('email_verified', models.BooleanField(default=False, help_text='When user recieve confiramion and confirm it.', verbose_name='Email verified')),
                ('account_verified', models.BooleanField(default=False, help_text='Manually confirmed by Admin. This means that user is participant of soocer community.', verbose_name='Account verified')),
            ],
            options={
                'verbose_name': 'Fan Profile',
                'verbose_name_plural': 'Fans Profiles',
            },
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('slug', models.CharField(blank=True, editable=False, max_length=255)),
                ('bio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Bio')),
                ('email_verified', models.BooleanField(default=False, help_text='When user recieve confiramion and confirm it.', verbose_name='Email verified')),
                ('account_verified', models.BooleanField(default=False, help_text='Manually confirmed by Admin. This means that user is participant of soocer community.', verbose_name='Account verified')),
            ],
            options={
                'verbose_name': 'Manager Profile',
                'verbose_name_plural': 'Managers Profiles',
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('slug', models.CharField(blank=True, editable=False, max_length=255)),
                ('bio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Bio')),
                ('email_verified', models.BooleanField(default=False, help_text='When user recieve confiramion and confirm it.', verbose_name='Email verified')),
                ('account_verified', models.BooleanField(default=False, help_text='Manually confirmed by Admin. This means that user is participant of soocer community.', verbose_name='Account verified')),
            ],
            options={
                'verbose_name': 'Parent Profile',
                'verbose_name_plural': 'Parents Profiles',
            },
        ),
        migrations.CreateModel(
            name='ScoutProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('slug', models.CharField(blank=True, editable=False, max_length=255)),
                ('bio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Bio')),
                ('email_verified', models.BooleanField(default=False, help_text='When user recieve confiramion and confirm it.', verbose_name='Email verified')),
                ('account_verified', models.BooleanField(default=False, help_text='Manually confirmed by Admin. This means that user is participant of soocer community.', verbose_name='Account verified')),
            ],
            options={
                'verbose_name': 'Scout Profile',
                'verbose_name_plural': 'Scouts Profiles',
            },
        ),
        migrations.AlterModelOptions(
            name='clubprofile',
            options={'verbose_name': 'Club Profile', 'verbose_name_plural': 'Club Profiles'},
        ),
        migrations.AlterModelOptions(
            name='coachprofile',
            options={'verbose_name': 'Coach Profile', 'verbose_name_plural': 'Coaches Profiles'},
        ),
        migrations.AlterModelOptions(
            name='guestprofile',
            options={'verbose_name': 'Guest Profile', 'verbose_name_plural': 'Guests Profiles'},
        ),
        migrations.DeleteModel(
            name='CompleteProfileTeaser',
        ),
    ]
