# Generated by Django 3.1.2 on 2020-11-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0022_auto_20201125_1904"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="video_description",
            field=models.TextField(blank=True, null=True, verbose_name="Temat i opis"),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="video_title",
            field=models.CharField(
                blank=True, max_length=235, null=True, verbose_name="Tytuł nagrania"
            ),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="video_url",
            field=models.URLField(blank=True, null=True, verbose_name="Youtube url"),
        ),
    ]
