# Generated by Django 3.1.2 on 2020-11-26 01:49

import address.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('profiles', '0023_auto_20201126_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='club',
            field=models.CharField(blank=True, help_text='Klub w którym obecnie reprezentuejsz', max_length=68, null=True, verbose_name='Klub'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='club_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='club_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='club_raw',
            field=models.CharField(blank=True, help_text='Klub w którym deklarujesz że obecnie reprezentuejsz', max_length=68, null=True, verbose_name='Deklarowany Klub'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='club_role',
            field=models.IntegerField(blank=True, help_text='Defines if admin approved change', null=True),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='diet_suplements',
            field=models.BooleanField(default=False, help_text='diet_suplements'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='fizo',
            field=models.BooleanField(default=False, help_text='fizo'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='game_bonus',
            field=models.BooleanField(default=False, help_text='game_bonus'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='gloves_shoes_refunds',
            field=models.BooleanField(default=False, help_text='gloves_shoes_refunds'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='league',
            field=models.CharField(blank=True, help_text='Poziom rozgrywkowy', max_length=68, null=True, verbose_name='Rozgrywki'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='league_raw',
            field=models.CharField(blank=True, help_text='Poziom rozgrywkowy który deklarujesz że grasz.', max_length=68, null=True, verbose_name='Rozgrywki'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='practice_stadion_address',
            field=address.models.AddressField(blank=True, help_text='Adres', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_practice_stadion_address', to='address.address'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='regular_gear',
            field=models.BooleanField(default=False, help_text='regular_gear'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='scolarships',
            field=models.BooleanField(default=False, help_text='scolarships'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='secondary_trainer',
            field=models.BooleanField(default=False, help_text='secondary_trainer'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='stadion_address',
            field=address.models.AddressField(blank=True, help_text='Adres', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_stadion_address', to='address.address'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='team',
            field=models.CharField(blank=True, help_text='Drużyna w której obecnie grasz', max_length=68, null=True, verbose_name='Drużyna'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='team_club_league_voivodeship_ver',
            field=models.CharField(blank=True, help_text='Drużyna, klub, rozgrywki, wojewódźtwo.', max_length=355, null=True, verbose_name='team_club_league_voivodeship_ver'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='team_raw',
            field=models.CharField(blank=True, help_text='Drużyna w której deklarujesz że obecnie grasz', max_length=68, null=True, verbose_name='Deklarowana Drużyna'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='traning_gear',
            field=models.BooleanField(default=False, help_text='traning_gear'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='travel_refunds',
            field=models.BooleanField(default=False, help_text='travel_refunds'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='voivodeship',
            field=models.CharField(blank=True, help_text='Wojewódźtwo', max_length=68, null=True, verbose_name='Wojewódźtwo'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='voivodeship_raw',
            field=models.CharField(blank=True, help_text='Wojewódźtwo w którym grasz.', max_length=68, null=True, verbose_name='Wojewódźtwo'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='O sobie'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='address',
            field=address.models.AddressField(blank=True, help_text='Adres', null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='club',
            field=models.CharField(blank=True, help_text='Klub w którym obecnie reprezentuejsz', max_length=68, null=True, verbose_name='Klub'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='club_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='club_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='club_raw',
            field=models.CharField(blank=True, help_text='Klub w którym deklarujesz że obecnie reprezentuejsz', max_length=68, null=True, verbose_name='Deklarowany Klub'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='club_role',
            field=models.IntegerField(blank=True, help_text='Defines if admin approved change', null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='diet_suplements',
            field=models.BooleanField(default=False, help_text='diet_suplements'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='fizo',
            field=models.BooleanField(default=False, help_text='fizo'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='game_bonus',
            field=models.BooleanField(default=False, help_text='game_bonus'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='gloves_shoes_refunds',
            field=models.BooleanField(default=False, help_text='gloves_shoes_refunds'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='league',
            field=models.CharField(blank=True, help_text='Poziom rozgrywkowy', max_length=68, null=True, verbose_name='Rozgrywki'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='league_raw',
            field=models.CharField(blank=True, help_text='Poziom rozgrywkowy który deklarujesz że grasz.', max_length=68, null=True, verbose_name='Rozgrywki'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='practice_distance',
            field=models.PositiveIntegerField(blank=True, help_text='Maksymalna odległośc na trening', null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)], verbose_name='Maksymalna odległość na trening'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='practice_stadion_address',
            field=address.models.AddressField(blank=True, help_text='Adres', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_practice_stadion_address', to='address.address'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='regular_gear',
            field=models.BooleanField(default=False, help_text='regular_gear'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='scolarships',
            field=models.BooleanField(default=False, help_text='scolarships'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='secondary_trainer',
            field=models.BooleanField(default=False, help_text='secondary_trainer'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='stadion_address',
            field=address.models.AddressField(blank=True, help_text='Adres', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_stadion_address', to='address.address'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='team',
            field=models.CharField(blank=True, help_text='Drużyna w której obecnie grasz', max_length=68, null=True, verbose_name='Drużyna'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='team_club_league_voivodeship_ver',
            field=models.CharField(blank=True, help_text='Drużyna, klub, rozgrywki, wojewódźtwo.', max_length=355, null=True, verbose_name='team_club_league_voivodeship_ver'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='team_raw',
            field=models.CharField(blank=True, help_text='Drużyna w której deklarujesz że obecnie grasz', max_length=68, null=True, verbose_name='Deklarowana Drużyna'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='training_ready',
            field=models.IntegerField(blank=True, choices=[(1, '1-2 treningi'), (2, '3-4 treningi'), (3, '5-6 treningi')], null=True, verbose_name='Gotowość do treningu'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='traning_gear',
            field=models.BooleanField(default=False, help_text='traning_gear'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='travel_refunds',
            field=models.BooleanField(default=False, help_text='travel_refunds'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='voivodeship',
            field=models.CharField(blank=True, help_text='Wojewódźtwo', max_length=68, null=True, verbose_name='Wojewódźtwo'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='voivodeship_raw',
            field=models.CharField(blank=True, help_text='Wojewódźtwo w którym grasz.', max_length=68, null=True, verbose_name='Wojewódźtwo'),
        ),
        migrations.AddField(
            model_name='fanprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='scoutprofile',
            name='address',
            field=address.models.AddressField(blank=True, help_text='Adres', null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
        migrations.AddField(
            model_name='scoutprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='scoutprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='scoutprofile',
            name='practice_distance',
            field=models.PositiveIntegerField(blank=True, help_text='Maksymalna odległośc na trening', null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)], verbose_name='Maksymalna odległość na trening'),
        ),
        migrations.AddField(
            model_name='scoutprofile',
            name='soccer_goal',
            field=models.IntegerField(blank=True, choices=[(1, 'Profesjonalna kariera'), (2, 'Kariera regionalna'), (3, 'Skauting jako hobby')], null=True, verbose_name='Piłkarski cel'),
        ),
        migrations.AlterField(
            model_name='clubprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data urodzenia'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='soccer_goal',
            field=models.IntegerField(blank=True, choices=[(1, 'Profesjonalna kariera'), (2, 'Kariera regionalna'), (3, 'Trenerka jako hobby')], null=True, verbose_name='Piłkarski cel'),
        ),
    ]
