# Generated by Django 3.1.2 on 2020-11-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_auto_20201126_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardprofile',
            name='history',
        ),
        migrations.RemoveField(
            model_name='standardprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='rolechangerequest',
            name='new',
            field=models.CharField(choices=[('P', 'Piłkarz'), ('T', 'Trener'), ('C', 'Klub / Szkółka piłkarska'), ('M', 'Agent piłkarski'), ('S', 'Skout'), ('R', 'Rodzic małego piłkarza'), ('G', 'Kibic / Rodzic')], max_length=100),
        ),
        migrations.DeleteModel(
            name='FanProfile',
        ),
        migrations.DeleteModel(
            name='StandardProfile',
        ),
    ]
