# Generated by Django 3.1.2 on 2020-12-04 18:01

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0028_auto_20201201_0024"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubprofile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region="PL",
                verbose_name="Telefon",
            ),
        ),
        migrations.AlterField(
            model_name="coachprofile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region="PL",
                verbose_name="Telefon",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="agent_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region="PL",
                verbose_name="Numer telefonu do agenta / agencji",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region="PL",
                verbose_name="Telefon",
            ),
        ),
        migrations.AlterField(
            model_name="trainercontact",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region="PL",
                verbose_name="Telefon",
            ),
        ),
    ]
