# Generated by Django 3.1.2 on 2020-12-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0029_auto_20201204_1901"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoutprofile",
            name="club_raw",
            field=models.CharField(
                blank=True,
                help_text="Klub w którym obecnie reprezentuejsz",
                max_length=68,
                null=True,
                verbose_name="Deklarowany klub",
            ),
        ),
        migrations.AddField(
            model_name="scoutprofile",
            name="league_raw",
            field=models.CharField(
                blank=True,
                help_text="Poziom rozgrywkowy",
                max_length=68,
                null=True,
                verbose_name="Deklarowany poziom rozgrywkowy",
            ),
        ),
        migrations.AddField(
            model_name="scoutprofile",
            name="voivodeship_raw",
            field=models.CharField(
                blank=True,
                help_text="Wojewódźtwo w którym grasz.",
                max_length=68,
                null=True,
                verbose_name="Deklarowane wojewódźtwo",
            ),
        ),
        migrations.AlterField(
            model_name="clubprofile",
            name="club_raw",
            field=models.CharField(
                blank=True,
                help_text="Klub w którym deklarujesz że obecnie reprezentuejsz",
                max_length=68,
                null=True,
                verbose_name="Deklarowany klub",
            ),
        ),
        migrations.AlterField(
            model_name="clubprofile",
            name="league",
            field=models.CharField(
                blank=True,
                help_text="Poziom rozgrywkowy",
                max_length=68,
                null=True,
                verbose_name="Poziom rozgrywkowy",
            ),
        ),
        migrations.AlterField(
            model_name="clubprofile",
            name="league_raw",
            field=models.CharField(
                blank=True,
                help_text="Poziom rozgrywkowy który deklarujesz że grasz.",
                max_length=68,
                null=True,
                verbose_name="Deklarowany poziom rozgrywkowy",
            ),
        ),
        migrations.AlterField(
            model_name="clubprofile",
            name="team_raw",
            field=models.CharField(
                blank=True,
                help_text="Drużyna w której deklarujesz że obecnie grasz",
                max_length=68,
                null=True,
                verbose_name="Deklarowana drużyna",
            ),
        ),
        migrations.AlterField(
            model_name="clubprofile",
            name="voivodeship_raw",
            field=models.CharField(
                blank=True,
                help_text="Wojewódźtwo w którym grasz.",
                max_length=68,
                null=True,
                verbose_name="Deklarowane wojewódźtwo",
            ),
        ),
        migrations.AlterField(
            model_name="coachprofile",
            name="club_role",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Trener"),
                    (2, "Prezes"),
                    (3, "Kierownik"),
                    (4, "Członek zarządu"),
                    (5, "Sztab szkoleniowy"),
                    (6, "Inne"),
                ],
                default=1,
                help_text="Defines if admin approved change",
                null=True,
            ),
        ),
    ]
