# Generated by Django 3.1.2 on 2020-12-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0030_auto_20201205_1308"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clubprofile",
            name="account_verified",
        ),
        migrations.RemoveField(
            model_name="clubprofile",
            name="email_verified",
        ),
        migrations.RemoveField(
            model_name="coachprofile",
            name="account_verified",
        ),
        migrations.RemoveField(
            model_name="coachprofile",
            name="email_verified",
        ),
        migrations.RemoveField(
            model_name="guestprofile",
            name="account_verified",
        ),
        migrations.RemoveField(
            model_name="guestprofile",
            name="email_verified",
        ),
        migrations.RemoveField(
            model_name="managerprofile",
            name="account_verified",
        ),
        migrations.RemoveField(
            model_name="managerprofile",
            name="email_verified",
        ),
        migrations.RemoveField(
            model_name="parentprofile",
            name="account_verified",
        ),
        migrations.RemoveField(
            model_name="parentprofile",
            name="email_verified",
        ),
        migrations.RemoveField(
            model_name="playerprofile",
            name="account_verified",
        ),
        migrations.RemoveField(
            model_name="playerprofile",
            name="email_verified",
        ),
        migrations.RemoveField(
            model_name="scoutprofile",
            name="account_verified",
        ),
        migrations.RemoveField(
            model_name="scoutprofile",
            name="email_verified",
        ),
        migrations.AlterField(
            model_name="clubprofile",
            name="bio",
            field=models.CharField(
                blank=True,
                max_length=455,
                null=True,
                verbose_name="Krótki opis o sobie",
            ),
        ),
        migrations.AlterField(
            model_name="coachprofile",
            name="bio",
            field=models.CharField(
                blank=True,
                max_length=455,
                null=True,
                verbose_name="Krótki opis o sobie",
            ),
        ),
        migrations.AlterField(
            model_name="guestprofile",
            name="bio",
            field=models.CharField(
                blank=True,
                max_length=455,
                null=True,
                verbose_name="Krótki opis o sobie",
            ),
        ),
        migrations.AlterField(
            model_name="managerprofile",
            name="bio",
            field=models.CharField(
                blank=True,
                max_length=455,
                null=True,
                verbose_name="Krótki opis o sobie",
            ),
        ),
        migrations.AlterField(
            model_name="parentprofile",
            name="bio",
            field=models.CharField(
                blank=True,
                max_length=455,
                null=True,
                verbose_name="Krótki opis o sobie",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="bio",
            field=models.CharField(
                blank=True,
                max_length=455,
                null=True,
                verbose_name="Krótki opis o sobie",
            ),
        ),
        migrations.AlterField(
            model_name="scoutprofile",
            name="bio",
            field=models.CharField(
                blank=True,
                max_length=455,
                null=True,
                verbose_name="Krótki opis o sobie",
            ),
        ),
        migrations.AlterField(
            model_name="scoutprofile",
            name="club",
            field=models.CharField(
                blank=True,
                help_text="Klub, który obecnie reprezentuejsz",
                max_length=68,
                null=True,
                verbose_name="Klub",
            ),
        ),
    ]
