# Generated by Django 3.1.2 on 2020-12-09 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0013_auto_20201208_1706"),
        ("profiles", "0035_auto_20201208_1706"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubprofile",
            name="club_object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clubowners",
                to="clubs.club",
            ),
        ),
        migrations.AddField(
            model_name="coachprofile",
            name="team_object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coaches",
                to="clubs.team",
            ),
        ),
    ]
