# Generated by Django 3.1.2 on 2020-12-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0038_auto_20201211_1509"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainercontact",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Telefon"
            ),
        ),
    ]
