# Generated by Django 3.1.2 on 2021-01-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0043_auto_20210105_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='agent_name',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Imię i nazwisko agenta / Nazwa agencji'),
        ),
    ]
