# Generated by Django 3.1.2 on 2021-01-05 15:50

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('profiles', '0044_auto_20210105_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='address',
            field=address.models.AddressField(blank=True, help_text='Miasto z którego dojeżdżam na trening', null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
    ]
