# Generated by Django 3.1.2 on 2021-01-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0046_auto_20210105_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='licence',
        ),
    ]
