# Generated by Django 3.1.2 on 2021-01-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0048_coachprofile_licence"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilevisithistory",
            name="counter_scout",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
