# Generated by Django 3.1.2 on 2021-01-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0049_profilevisithistory_counter_scout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='licence',
            field=models.IntegerField(blank=True, choices=[(1, 'UEFA PRO'), (2, 'UEFA A'), (3, 'UEFA EY A'), (4, 'UEFA B'), (5, 'UEFA C'), (6, 'GRASS C'), (7, 'GRASS D'), (8, 'UEFA Futsal B'), (9, 'PZPN A'), (10, 'PZPN B'), (11, 'W trakcie kursu')], null=True, verbose_name='Licencja'),
        ),
    ]
