# Generated by Django 3.1.2 on 2021-02-02 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0023_league_code"),
        ("profiles", "0050_auto_20210108_1543"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="team_object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="players",
                to="clubs.team",
            ),
        ),
    ]
