# Generated by Django 3.1.2 on 2021-02-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0051_playerprofile_team_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='meta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
