# Generated by Django 3.1.2 on 2021-02-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0052_playerprofile_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='meta_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
