# Generated by Django 3.1.2 on 2021-02-06 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0026_auto_20210206_1612"),
        ("profiles", "0053_playerprofile_meta_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="team_object_alt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="players_alt",
                to="clubs.team",
            ),
        ),
    ]
