# Generated by Django 3.1.2 on 2021-02-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0054_playerprofile_team_object_alt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerprofile",
            name="meta",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
