# Generated by Django 3.1.2 on 2021-08-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0056_auto_20210306_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
