# Generated by Django 3.1.14 on 2022-01-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0057_coachprofile_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='address',
            field=models.CharField(blank=True, help_text='Adres', max_length=100, null=True),
        ),
    ]
