# Generated by Django 3.1.13 on 2022-02-10 23:29

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_auto_20200830_1851"),
        ("profiles", "0058_auto_20220130_1815"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coachprofile",
            name="address",
            field=address.models.AddressField(
                blank=True,
                help_text="Miasto z którego dojeżdżam na trening",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="address.address",
            ),
        ),
        migrations.AlterField(
            model_name="coachprofile",
            name="team_club_league_voivodeship_ver",
            field=models.CharField(
                blank=True,
                help_text="Drużyna, klub, rozgrywki, wojewódźtwo.",
                max_length=355,
                null=True,
                verbose_name="Województwo3",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="voivodeship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Dolnośląskie", "Dolnośląskie"),
                    ("Kujawsko-pomorskie", "Kujawsko-pomorskie"),
                    ("Lubelskie", "Lubelskie"),
                    ("Lubuskie", "Lubuskie"),
                    ("Łódzkie", "Łódzkie"),
                    ("Małopolskie", "Małopolskie"),
                    ("Mazowieckie", "Mazowieckie"),
                    ("Opolskie", "Opolskie"),
                    ("Podkarpackie", "Podkarpackie"),
                    ("Podlaskie", "Podlaskie"),
                    ("Pomorskie", "Pomorskie"),
                    ("Śląskie", "Śląskie"),
                    ("Świętokrzyskie", "Świętokrzyskie"),
                    ("Warmińsko-Mazurskie", "Warmińsko-Mazurskie"),
                    ("Wielkopolskie", "Wielkopolskie"),
                    ("Zachodniopomorskie", "Zachodniopomorskie"),
                ],
                max_length=68,
                null=True,
                verbose_name="Województwo",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="voivodeship_raw",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Dolnośląskie", "Dolnośląskie"),
                    ("Kujawsko-pomorskie", "Kujawsko-pomorskie"),
                    ("Lubelskie", "Lubelskie"),
                    ("Lubuskie", "Lubuskie"),
                    ("Łódzkie", "Łódzkie"),
                    ("Małopolskie", "Małopolskie"),
                    ("Mazowieckie", "Mazowieckie"),
                    ("Opolskie", "Opolskie"),
                    ("Podkarpackie", "Podkarpackie"),
                    ("Podlaskie", "Podlaskie"),
                    ("Pomorskie", "Pomorskie"),
                    ("Śląskie", "Śląskie"),
                    ("Świętokrzyskie", "Świętokrzyskie"),
                    ("Warmińsko-Mazurskie", "Warmińsko-Mazurskie"),
                    ("Wielkopolskie", "Wielkopolskie"),
                    ("Zachodniopomorskie", "Zachodniopomorskie"),
                ],
                help_text="Wojewódźtwo w którym grasz.",
                max_length=68,
                null=True,
                verbose_name="Wojewódźtwo",
            ),
        ),
        migrations.AlterField(
            model_name="scoutprofile",
            name="address",
            field=address.models.AddressField(
                blank=True,
                help_text="Adres",
                max_length=100,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="address.address",
            ),
        ),
    ]
