# Generated by Django 3.1.14 on 2022-01-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0059_auto_20220123_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoutprofile',
            name='address',
            field=models.CharField(blank=True, help_text='Adres', max_length=100, null=True),
        ),
    ]
