# Generated by Django 3.1.14 on 2022-01-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0061_coachprofile_voivodeship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='voivodeship',
            field=models.CharField(blank=True, choices=[('dolnośląskie', 'dolnośląskie'), ('kujawsko-pomorskie', 'kujawsko-pomorskie'), ('lubelskie', 'lubelskie'), ('lubuskie', 'lubuskie'), ('łódzkie', 'łódzkie'), ('małopolskie', 'małopolskie'), ('mazowieckie', 'mazowieckie'), ('opolskie', 'opolskie'), ('podkarpackie', 'podkarpackie'), ('podlaskie', 'podlaskie'), ('pomorskie', 'pomorskie'), ('śląskie', 'śląskie'), ('świętokrzyskie', 'świętokrzyskie'), ('warmińsko-mazurskie', 'warmińsko-mazurskie'), ('wielkopolskie', 'wielkopolskie'), ('zachodniopomorskie', 'zachodniopomorskie')], max_length=20, null=True, verbose_name='Województwo'),
        ),
    ]
