# Generated by Django 3.1.13 on 2022-03-06 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0059_auto_20220204_2344'),
        ('profiles', '0062_auto_20220213_1952'),
    ]

    operations = [
    ]
