# Generated by Django 3.1.13 on 2022-03-06 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clubs", "0063_league_highest_parent"),
        ("profiles", "0064_auto_20220306_2232"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileVerificationStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(max_length=255)),
                (
                    "previous_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("has_team", models.BooleanField()),
                ("team_not_found", models.BooleanField()),
                (
                    "previous_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_team",
                        to="clubs.team",
                    ),
                ),
                (
                    "set_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="set_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team",
                        to="clubs.team",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="clubprofile",
            name="verification",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.profileverificationstatus",
            ),
        ),
        migrations.AddField(
            model_name="coachprofile",
            name="verification",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.profileverificationstatus",
            ),
        ),
        migrations.AddField(
            model_name="guestprofile",
            name="verification",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.profileverificationstatus",
            ),
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="verification",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.profileverificationstatus",
            ),
        ),
        migrations.AddField(
            model_name="parentprofile",
            name="verification",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.profileverificationstatus",
            ),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="verification",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.profileverificationstatus",
            ),
        ),
        migrations.AddField(
            model_name="scoutprofile",
            name="verification",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.profileverificationstatus",
            ),
        ),
    ]
