# Generated by Django 3.1.14 on 2022-02-06 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0058_auto_20220130_1815'),
        ('profiles', '0065_auto_20220123_1656'),
    ]

    operations = [
    ]
