# Generated by Django 3.1.14 on 2022-02-06 21:53

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('profiles', '0066_merge_20220206_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachprofile',
            name='team',
        ),
        migrations.RemoveField(
            model_name='coachprofile',
            name='voivodeship',
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='address',
            field=address.models.AddressField(blank=True, help_text='Adres', null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='team_club_league_voivodeship_ver',
            field=models.CharField(blank=True, help_text='Drużyna, klub, rozgrywki, wojewódźtwo.', max_length=355, null=True, verbose_name='team_club_league_voivodeship_ver'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='address',
            field=address.models.AddressField(blank=True, help_text='Miasto z którego dojeżdżam na trening', null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='voivodeship',
            field=models.CharField(blank=True, db_index=True, help_text='Wojewódźtwo', max_length=68, null=True, verbose_name='Wojewódźtwo'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='voivodeship_raw',
            field=models.CharField(blank=True, help_text='Wojewódźtwo w którym grasz.', max_length=68, null=True, verbose_name='Wojewódźtwo'),
        ),
        migrations.AlterField(
            model_name='scoutprofile',
            name='address',
            field=address.models.AddressField(blank=True, help_text='Adres', null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
    ]
