# Generated by Django 3.1.13 on 2022-03-24 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0067_auto_20220323_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileverificationstatus',
            name='previous_club',
        ),
        migrations.RemoveField(
            model_name='profileverificationstatus',
            name='previous_status',
        ),
        migrations.RemoveField(
            model_name='profileverificationstatus',
            name='previous_team',
        ),
        migrations.AddField(
            model_name='profileverificationstatus',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='profiles.profileverificationstatus'),
        ),
        migrations.AlterField(
            model_name='profileverificationstatus',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
