# Generated by Django 3.1.14 on 2022-02-11 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0067_auto_20220206_2253'),
        ('profiles', '0059_auto_20220211_0029'),
    ]

    operations = [
    ]
