# Generated by Django 3.1.13 on 2022-03-24 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0068_auto_20220324_1735"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileverificationstatus",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
