# Generated by Django 3.1.13 on 2022-03-24 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0069_profileverificationstatus_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileverificationstatus",
            name="previous",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next",
                to="profiles.profileverificationstatus",
            ),
        ),
    ]
