# Generated by Django 3.1.13 on 2022-03-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0070_auto_20220324_2203"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileverificationstatus",
            name="text",
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
