# Generated by Django 3.2 on 2022-06-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0071_profileverificationstatus_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='team_club_league_voivodeship_ver',
            field=models.CharField(blank=True, help_text='Drużyna, klub, rozgrywki, wojewódźtwo.', max_length=355, null=True, verbose_name='Województwo'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='team_club_league_voivodeship_ver',
            field=models.CharField(blank=True, help_text='Drużyna, klub, rozgrywki, województwo.', max_length=355, null=True, verbose_name='team_club_league_voivodeship_ver'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='voivodeship',
            field=models.CharField(blank=True, choices=[('Dolnośląskie', 'Dolnośląskie'), ('Kujawsko-pomorskie', 'Kujawsko-pomorskie'), ('Lubelskie', 'Lubelskie'), ('Lubuskie', 'Lubuskie'), ('Łódzkie', 'Łódzkie'), ('Małopolskie', 'Małopolskie'), ('Mazowieckie', 'Mazowieckie'), ('Opolskie', 'Opolskie'), ('Podkarpackie', 'Podkarpackie'), ('Podlaskie', 'Podlaskie'), ('Pomorskie', 'Pomorskie'), ('Śląskie', 'Śląskie'), ('Świętokrzyskie', 'Świętokrzyskie'), ('Warmińsko-Mazurskie', 'Warmińsko-Mazurskie'), ('Wielkopolskie', 'Wielkopolskie'), ('Zachodniopomorskie', 'Zachodniopomorskie')], help_text='Wybierz województwo', max_length=68, null=True, verbose_name='Województwo zamieszkania'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='voivodeship_raw',
            field=models.CharField(blank=True, choices=[('Dolnośląskie', 'Dolnośląskie'), ('Kujawsko-pomorskie', 'Kujawsko-pomorskie'), ('Lubelskie', 'Lubelskie'), ('Lubuskie', 'Lubuskie'), ('Łódzkie', 'Łódzkie'), ('Małopolskie', 'Małopolskie'), ('Mazowieckie', 'Mazowieckie'), ('Opolskie', 'Opolskie'), ('Podkarpackie', 'Podkarpackie'), ('Podlaskie', 'Podlaskie'), ('Pomorskie', 'Pomorskie'), ('Śląskie', 'Śląskie'), ('Świętokrzyskie', 'Świętokrzyskie'), ('Warmińsko-Mazurskie', 'Warmińsko-Mazurskie'), ('Wielkopolskie', 'Wielkopolskie'), ('Zachodniopomorskie', 'Zachodniopomorskie')], help_text='Wojewódźtwo w którym grasz. Nie uzywane pole', max_length=68, null=True, verbose_name='Wojewódźtwo (raw)'),
        ),
    ]
