# Generated by Django 3.2 on 2022-07-20 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def move_currently_videos(apps, schema_editor):
    def get_videos(obj):
        return [
            {
                "url": obj.video_url,
                "title": obj.video_title,
                "desc": obj.video_description,
            },
            {
                "url": obj.video_url_second,
                "title": obj.video_title_second,
                "desc": obj.video_description_second,
            },
            {
                "url": obj.video_url_third,
                "title": obj.video_title_third,
                "desc": obj.video_description_third,
            },
        ]

    player = apps.get_model("profiles", "PlayerProfile")
    video = apps.get_model("profiles", "PlayerVideo")
    for player_obj in player.objects.all():
        videos = get_videos(player_obj)
        for obj in videos:
            if obj["url"]:
                video.objects.create(
                    url=obj["url"],
                    title=obj["title"] or "",
                    description=obj["desc"] or "",
                    player=player_obj,
                )


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0072_auto_20220627_2313"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerVideo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(verbose_name="Youtube url")),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=235,
                        null=True,
                        verbose_name="Tytuł nagrania",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Opis"),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_video",
                        to="profiles.playerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Video",
                "verbose_name_plural": "Player Videos",
            },
        ),
        migrations.RunPython(move_currently_videos),
        migrations.RemoveField(
            model_name="playerprofile",
            name="video_description",
        ),
        migrations.RemoveField(
            model_name="playerprofile",
            name="video_description_second",
        ),
        migrations.RemoveField(
            model_name="playerprofile",
            name="video_description_third",
        ),
        migrations.RemoveField(
            model_name="playerprofile",
            name="video_title",
        ),
        migrations.RemoveField(
            model_name="playerprofile",
            name="video_title_second",
        ),
        migrations.RemoveField(
            model_name="playerprofile",
            name="video_title_third",
        ),
        migrations.RemoveField(
            model_name="playerprofile",
            name="video_url",
        ),
        migrations.RemoveField(
            model_name="playerprofile",
            name="video_url_second",
        ),
        migrations.RemoveField(
            model_name="playerprofile",
            name="video_url_third",
        ),
    ]
