# Generated by Django 3.2 on 2022-07-13 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voivodeships', '0001_initial'),
        ('profiles', '0073_auto_20220712_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutprofile',
            name='new_voivodeship',
            field=models.ForeignKey(blank=True, help_text='Wybierz województwo. Nowe pole.', max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voivodeships.voivodeships', verbose_name='Województwo zamieszkania'),
        ),
        migrations.AlterField(
            model_name='scoutprofile',
            name='voivodeship',
            field=models.CharField(blank=True, help_text='Wojewódźtwo. Stare pole, czeka na migracje', max_length=68, null=True, verbose_name='Wojewódźtwo'),
        ),
    ]
