# Generated by Django 3.2 on 2022-10-26 11:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0074_merge_20220814_1130"),
        ("profiles", "0074_merge_20220928_1427"),
    ]

    operations = []
