# Generated by Django 3.2 on 2022-12-18 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0001_initial'),
        ('profiles', '0075_merge_20221026_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='mapper',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapper.mapper'),
        ),
    ]
