# Generated by Django 3.2 on 2022-12-06 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0075_merge_20221026_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='mapper',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapper', to='profiles.mapper'),
        ),
        migrations.CreateModel(
            name='MapperEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapper_id', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('OLD_LNP', 'OLD_LPN'), ('NEW_LNP', 'NEW_LPN'), ('TRANSFERMARKT', 'TRANSFERMARKT'), ('90MINUT', '90MINUT')], max_length=20)),
                ('url', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.mapper')),
            ],
            options={
                'unique_together': {('target', 'source')},
            },
        ),
    ]
