# Generated by Django 3.2 on 2023-01-22 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0076_playerprofile_mapper"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coachprofile",
            name="training_ready",
        ),
        migrations.RemoveField(
            model_name="playerprofile",
            name="club_raw",
        ),
        migrations.RemoveField(
            model_name="playerprofile",
            name="league_raw",
        ),
        migrations.RemoveField(
            model_name="playerprofile",
            name="team_raw",
        ),
        migrations.RemoveField(
            model_name="scoutprofile",
            name="club",
        ),
        migrations.RemoveField(
            model_name="scoutprofile",
            name="league",
        ),
        migrations.RemoveField(
            model_name="scoutprofile",
            name="voivodeship",
        ),
    ]
