# Generated by Django 3.2 on 2023-01-25 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0005_alter_mapperentity_related_type'),
        ('profiles', '0077_auto_20230122_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='mapper',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapper.mapper'),
        ),
    ]
