# Generated by Django 3.2 on 2023-02-15 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0007_auto_20230216_0029'),
        ('profiles', '0078_coachprofile_mapper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='mapper',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapper.mapper'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='mapper',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapper.mapper'),
        ),
    ]
