# Generated by Django 3.2 on 2023-03-17 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("external_links", "0002_alter_externallinksentity_related_type"),
        ("profiles", "0079_auto_20230216_0029"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachprofile",
            name="external_links",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="external_links.externallinks",
            ),
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="external_links",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="external_links.externallinks",
            ),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="external_links",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="external_links.externallinks",
            ),
        ),
        migrations.AddField(
            model_name="scoutprofile",
            name="external_links",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="external_links.externallinks",
            ),
        ),
    ]
