# Generated by Django 3.2 on 2023-03-22 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0080_auto_20230318_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfilePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playmaker_position', models.IntegerField(blank=True, choices=[(1, 'Bramkarz'), (2, 'Obrońca Lewy'), (3, 'Obrońca Prawy'), (4, 'Obrońca Środkowy'), (5, 'Pomocnik defensywny (6)'), (6, 'Pomocnik środkowy (8)'), (7, 'Pomocnik ofensywny (10)'), (8, 'Skrzydłowy'), (9, 'Napastnik')], null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('score_position', models.CharField(max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.playerprofile')),
            ],
            options={
                'verbose_name': 'Player Profile Position',
                'verbose_name_plural': 'Player Profile Positions',
            },
        ),
    ]
