# Generated by Django 3.2 on 2023-03-24 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0081_playerposition_score_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfilePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False, help_text="Indicates whether this is the player's main position.")),
                ('player_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.playerposition')),
                ('player_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.playerprofile')),
            ],
            options={
                'verbose_name': 'Player Profile Position',
                'verbose_name_plural': 'Player Profile Positions',
                'unique_together': {('player_position', 'player_profile')},
            },
        ),
    ]
