# Generated by Django 3.2 on 2023-03-26 19:16

from django.db import migrations, models
from django.utils.translation import ugettext_lazy as _


def populate_languages(apps, schema_editor):
    """
    Populates a Language model with the given language data.
    """
    languages = [
        ("af", _("Afrykanerski"), ("afrikaans"), 2),
        ("sq", _("Albański"), ("shqip"), 2),
        ("am", _("Amharski"), ("አማርኛ"), 2),
        ("ar", _("Arabski"), ("العربية"), 2),
        ("hy", _("Ormiański"), ("հայերեն"), 2),
        ("az", _("Azerbejdżański"), ("azərbaycan dili"), 2),
        ("eu", _("Baskijski"), ("euskara"), 2),
        ("be", _("Białoruski"), ("беларуская мова"), 2),
        ("bn", _("Bengalski"), ("বাংলা"), 2),
        ("bs", _("Bośniacki"), ("bosanski jezik"), 2),
        ("bg", _("Bułgarski"), ("Български език"), 2),
        ("my", _("Birmański"), ("ဗမာစာ"), 2),
        ("ca", _("Kataloński"), ("Català"), 2),
        ("zh", _("Chiński"), ("中文"), 2),
        ("hr", _("Chorwacki"), ("Hrvatski jezik"), 2),
        ("cs", _("Czeski"), ("Čeština"), 2),
        ("da", _("Duński"), ("Dansk"), 2),
        ("nl", _("Holenderski"), ("Nederlands"), 2),
        ("en", _("Angielski"), ("English"), 1),
        ("eo", _("Esperanto"), ("Esperanto"), 2),
        ("et", _("Estoński"), ("Eesti keel"), 2),
        ("fi", _("Fiński"), ("Suomi"), 2),
        ("fr", _("Francuski"), ("Français"), 1),
        ("gl", _("Galicyjski"), ("Galego"), 2),
        ("ka", _("Gruziński"), ("ქართული"), 2),
        ("de", _("Niemiecki"), ("Deutsch"), 1),
        ("el", _("Grecki"), ("Ελληνικά"), 2),
        ("gu", _("Gudżarati"), ("ગુજરાતી"), 2),
        ("ht", _("Haitański kreolski"), ("Kréyòl ayisyen"), 2),
        ("he", _("Hebrajski"), ("עִבְרִית"), 2),
        ("hi", _("Hinduski"), ("हिन्दी"), 2),
        ("hu", _("Węgierski"), ("Magyar"), 2),
        ("is", _("Islandzki"), ("Íslenska"), 2),
        ("ig", _("Igbo"), ("Asụsụ Igbo"), 2),
        ("id", _("Indonezyjski"), ("Bahasa Indonesia"), 2),
        ("ga", _("Irlandzki"), ("Gaeilge"), 2),
        ("it", _("Włoski"), ("Italiano"), 1),
        ("ja", _("Japoński"), ("日本語"), 2),
        ("jv", _("Jawajski"), ("Basa Jawa"), 2),
        ("kn", _("Kannada"), ("ಕನ್ನಡ"), 2),
        ("kk", _("Kazachski"), ("Қазақ тілі"), 2),
        ("km", _("Khmerski"), ("ភាសាខ្មែរ"), 2),
        ("rw", _("Kinyarwanda"), ("Kinyarwanda"), 2),
        ("ko", _("Koreański"), ("한국어"), 2),
        ("ku", _("Kurdyjski"), ("کوردی"), 2),
        ("ky", _("Kirgiski"), ("Кыргызча"), 2),
        ("lo", _("Laotański"), ("ພາສາລາວ"), 2),
        ("lv", _("Łotewski"), ("Latviešu"), 2),
        ("lt", _("Litewski"), ("Lietuvių"), 2),
        ("lb", _("Luksemburski"), ("Lëtzebuergesch"), 2),
        ("mk", _("Macedoński"), ("Македонски"), 2),
        ("mg", _("Malgaski"), ("Malagasy"), 2),
        ("ms", _("Malajski"), ("Bahasa Melayu"), 2),
        ("ml", _("Malajalam"), ("മലയാളം"), 2),
        ("mt", _("Maltański"), ("Malti"), 2),
        ("mi", _("Maoryjski"), ("te reo Māori"), 2),
        ("mr", _("Marathi"), ("मराठी"), 2),
        ("mn", _("Mongolski"), ("Монгол хэл"), 2),
        ("ne", _("Nepalski"), ("नेपाली"), 2),
        ("no", _("Norweski"), ("Norsk"), 2),
        ("ny", _("Njandża"), ("ChiChewa"), 2),
        ("or", _("Orija"), ("ଓଡ଼ିଆ"), 2),
        ("ps", _("Paszto"), ("پښتو"), 2),
        ("fa", _("Perski"), ("فارسی"), 2),
        ("pl", _("Polski"), ("Polski"), 1),
        ("pt", _("Portugalski"), ("Português"), 2),
        ("pa", _("Pendżabski"), ("ਪੰਜਾਬੀ"), 2),
        ("ro", _("Rumuński"), ("Română"), 2),
        ("ru", _("Rosyjski"), ("Русский"), 2),
        ("sm", _("Samoański"), ("Gagana faʻa Samoa"), 2),
        ("gd", _("Gaelicki"), ("Gàidhlig"), 2),
        ("sr", _("Serbski"), ("Српски"), 2),
        ("st", _("Sotho"), ("Sesotho"), 2),
        ("sn", _("Shona"), ("chiShona"), 2),
        ("sd", _("Sindhi"), ("سنڌي"), 2),
        ("si", _("Syngaleski"), ("සිංහල"), 2),
        ("sk", _("Słowacki"), ("Slovenčina"), 2),
        ("sl", _("Słoweński"), ("Slovenščina"), 2),
        ("so", _("Somalijski"), ("Soomaaliga"), 2),
        ("es", _("Hiszpański"), ("Español"), 1),
        ("su", _("Sundajski"), ("Basa Sunda"), 2),
        ("sw", _("Suahili"), ("Kiswahili"), 2),
        ("sv", _("Szwedzki"), ("Svenska"), 2),
        ("tg", _("Tadżycki"), ("Тоҷикӣ"), 2),
        ("ta", _("Tamilski"), ("தமிழ்"), 2),
        ("tt", _("Tatarski"), ("Татар теле"), 2),
        ("te", _("Telugu"), ("తెలుగు"), 2),
        ("th", _("Tajski"), ("ไทย"), 2),
        ("uk", _("Ukraiński"), ("Українська"), 2),
        ("ur", _("Urdu"), ("اردو"), 2),
        ("uz", _("Uzbecki"), ("Oʻzbekcha"), 2),
        ("vi", _("Wietnamski"), ("Tiếng Việt"), 2),
        ("zh-hans", _("Chiński (Uproszczony)"), ("简体中文"), 2),
        ("zh-hant", _("Chiński (Tradycyjny)"), ("繁體中文"), 2),
    ]
    Language = apps.get_model("profiles", "Language")
    for code, name, native_name, priority in languages:
        Language.objects.create(
            name=name, code=code, native_name=native_name, priority=priority
        )


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0082_playerprofileposition"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("native_name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=10)),
                ("priority", models.IntegerField(default=2)),
            ],
            options={
                "ordering": ["priority", "name"],
            },
        ),
        migrations.RunPython(populate_languages),
    ]
