# Generated by Django 3.2 on 2023-05-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0083_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermetrics',
            name='pm_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermetrics',
            name='pm_score_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermetrics',
            name='season_score',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermetrics',
            name='season_score_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
