# Generated by Django 3.2 on 2023-05-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0084_auto_20230516_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermetrics',
            name='pm_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='PlayMaker Score'),
        ),
        migrations.AlterField(
            model_name='playermetrics',
            name='pm_score_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='PlayMaker Score date updated'),
        ),
        migrations.AlterField(
            model_name='playermetrics',
            name='season_score',
            field=models.JSONField(blank=True, null=True, verbose_name='Season Score'),
        ),
        migrations.AlterField(
            model_name='playermetrics',
            name='season_score_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Season Score date updated'),
        ),
    ]
