# Generated by Django 3.2 on 2023-06-27 12:02
from functools import partial
from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor, profile_type):
    model = apps.get_model("profiles", profile_type)
    for inst in model.objects.all():
        inst.uuid = uuid.uuid4()
        inst.save()


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0085_auto_20230627_0954"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubprofile",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(partial(create_uuid, profile_type="ClubProfile")),
        migrations.AddField(
            model_name="clubprofile",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="coachprofile",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(partial(create_uuid, profile_type="CoachProfile")),
        migrations.AddField(
            model_name="coachprofile",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="guestprofile",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(partial(create_uuid, profile_type="GuestProfile")),
        migrations.AddField(
            model_name="guestprofile",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(partial(create_uuid, profile_type="ManagerProfile")),
        migrations.AddField(
            model_name="managerprofile",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="otherprofile",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(partial(create_uuid, profile_type="OtherProfile")),
        migrations.AddField(
            model_name="otherprofile",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="parentprofile",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(partial(create_uuid, profile_type="ParentProfile")),
        migrations.AddField(
            model_name="parentprofile",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(partial(create_uuid, profile_type="PlayerProfile")),
        migrations.AddField(
            model_name="playerprofile",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="scoutprofile",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(partial(create_uuid, profile_type="ScoutProfile")),
        migrations.AddField(
            model_name="scoutprofile",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
