# Generated by Django 3.2 on 2023-06-27 19:41

from django.db import migrations, models
import django.db.models.deletion


def populate_coach_licence(apps, schema_editor):
    Licence = apps.get_model('profiles', 'Licence')
    CoachProfile = apps.get_model('profiles', 'CoachProfile')
    CoachLicence = apps.get_model('profiles', 'CoachLicence')

    LICENCE_CHOICES = [
        (1, "UEFA PRO"),
        (2, "UEFA A"),
        (3, "UEFA EY A"),
        (4, "UEFA B"),
        (5, "UEFA C"),
        (6, "GRASS C"),
        (7, "GRASS D"),
        (8, "UEFA Futsal B"),
        (9, "PZPN A"),
        (10, "PZPN B"),
        (11, "W trakcie kursu"),
    ]

    # Create Licence instances for each unique licence choice
    for licence_choice_value, licence_choice_name in LICENCE_CHOICES:
        Licence.objects.create(id=licence_choice_value, name=licence_choice_name)

    # Populate CoachLicence instances based on CoachProfile licences
    for coach_profile in CoachProfile.objects.all():
        licence_id = coach_profile.licence

        if licence_id is not None:
            licence = Licence.objects.get(id=licence_id)

            CoachLicence.objects.create(
                coach_profile=coach_profile,
                licence=licence,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0086_auto_20230627_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=17, null=True, verbose_name='Licencja')),
            ],
        ),
        migrations.CreateModel(
            name='CoachLicence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('coach_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licences', to='profiles.coachprofile')),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.licence')),
            ],
        ),
        migrations.RunPython(populate_coach_licence)
    ]
