# Generated by Django 3.2 on 2023-07-26 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0085_auto_20230530_1532'),
        ('profiles', '0087_coachlicence_licencetype'),
    ]

    operations = [
    ]
