# Generated by Django 3.2 on 2023-07-25 15:21
from django.db import migrations
from profiles.models import PlayerProfile, PlayerProfilePosition, PlayerPosition


def migrate_position_data(apps, schema_editor) -> None:
    """
    This function migrates the position data from the PlayerProfile model to the
    PlayerProfilePosition model.

    The `position_raw` field of the PlayerProfile model is used as the main position
    and the `position_raw_alt` field is used as the alternate position.

    The function checks the `position_raw` field for each profile in PlayerProfile.
    If it's not empty, a new main position is created in the PlayerProfilePosition.

    Similarly, if the `position_raw_alt` field is not empty and is different from
    `position_raw`, a new alternate position is created in the PlayerProfilePosition
    model.
    """

    player_profiles = PlayerProfile.objects.all()

    for profile in player_profiles:
        if profile.position_raw:
            position_name = profile.get_position_raw_display()
            player_position, created = PlayerPosition.objects.get_or_create(name__iexact=position_name)
            PlayerProfilePosition.objects.create(
                player_profile=profile,
                player_position=player_position,
                is_main=True
            )

        if profile.position_raw_alt and (profile.position_raw != profile.position_raw_alt):
            position_name_alt = profile.get_position_raw_alt_display()
            player_position_alt, created_alt = PlayerPosition.objects.get_or_create(name__iexact=position_name_alt)
            PlayerProfilePosition.objects.create(
                player_profile=profile,
                player_position=player_position_alt,
                is_main=False
            )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0088_merge_20230722_1245'),
    ]

    operations = [
        migrations.RunPython(migrate_position_data),
    ]
