# Generated by Django 3.2 on 2023-08-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0088_auto_20230731_1406"),
    ]

    operations = [
        migrations.AddField(
            model_name="managerprofile",
            name="agency_email",
            field=models.EmailField(
                blank=True,
                help_text="Contact email address for the managing agency.",
                max_length=254,
                null=True,
                verbose_name="Agency Email",
            ),
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="agency_instagram_url",
            field=models.URLField(
                blank=True,
                help_text="URL of the managing agency's Instagram profile.",
                max_length=500,
                null=True,
                verbose_name="Agency Instagram URL",
            ),
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="agency_phone",
            field=models.CharField(
                blank=True,
                help_text="Contact phone number for the managing agency.",
                max_length=15,
                null=True,
                verbose_name="Agency Phone",
            ),
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="agency_transfermarkt_url",
            field=models.URLField(
                blank=True,
                help_text="URL of the managing agency's profile on Transfermarkt.",
                max_length=500,
                null=True,
                verbose_name="Agency Transfermarkt URL",
            ),
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="agency_twitter_url",
            field=models.URLField(
                blank=True,
                help_text="URL of the managing agency's Twitter profile.",
                max_length=500,
                null=True,
                verbose_name="Agency Twitter URL",
            ),
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="agency_website_url",
            field=models.URLField(
                blank=True,
                help_text="URL of the managing agency's official website.",
                max_length=500,
                null=True,
                verbose_name="Agency Website URL",
            ),
        ),
    ]
