# Generated by Django 3.2 on 2023-07-26 18:08

from django.db import migrations


def migrate_position_data(apps, schema_editor) -> None:
    """
    This function migrates the position data from the PlayerProfile model to the
    PlayerProfilePosition model.

    The `position_raw` field of the PlayerProfile model is used as the main position
    and the `position_raw_alt` field is used as the alternate position.

    The function checks the `position_raw` field for each profile in PlayerProfile.
    If it's not empty, a new main position is created in the PlayerProfilePosition.

    Similarly, if the `position_raw_alt` field is not empty and is different from
    `position_raw`, a new alternate position is created in the PlayerProfilePosition
    model.
    """
    player_position_model = apps.get_model("profiles", "PlayerPosition")
    player_profile_position_model = apps.get_model("profiles", "PlayerProfilePosition")
    player_profile_model = apps.get_model("profiles", "PlayerProfile")
    player_profiles = player_profile_model.objects.all()

    for profile in player_profiles:
        if profile.position_raw:
            position_name = profile.get_position_raw_display()
            player_position, created = player_position_model.objects.get_or_create(
                name__iexact=position_name
            )
            player_profile_position_model.objects.create(
                player_profile=profile, player_position=player_position, is_main=True
            )

        if profile.position_raw_alt and (
            profile.position_raw != profile.position_raw_alt
        ):
            position_name_alt = profile.get_position_raw_alt_display()
            (
                player_position_alt,
                created_alt,
            ) = player_position_model.objects.get_or_create(
                name__iexact=position_name_alt
            )
            player_profile_position_model.objects.create(
                player_profile=profile,
                player_position=player_position_alt,
                is_main=False,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0090_refereelevel"),
    ]

    operations = [
        migrations.RunPython(migrate_position_data),
    ]
