# Generated by Django 3.2 on 2023-08-07 18:35

from django.db import migrations, connection


def reset_licence_type_sequence(apps, schema_editor) -> None:
    """
    Reset the ID sequence for the LicenceType model to its max ID.

    Background:
    During earlier migrations, there were instances where specific IDs were manually set for
    the LicenceType model. This caused the auto-increment sequence to fall out of sync
    with the actual data in the database. As a result, when trying to add new records, there
    was potential for ID conflicts due to the sequence suggesting an ID that already existed.

    This function corrects this by resetting the sequence to the next available ID after
    the highest current ID. This ensures that any new records added will have a unique ID
    that doesn't conflict with existing records.
    """
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT setval(pg_get_serial_sequence('"profiles_licencetype"', 'id'), 
            COALESCE(MAX("id"), 1), MAX("id") IS NOT null) 
            FROM "profiles_licencetype";
        """
        )


def add_new_licences(apps, schema_editor) -> None:
    """
    Add new licence types to the LicenceType model.

    After resetting the ID sequence for LicenceType, this function simply creates
    the new licenses. It no longer manually sets the ID because the sequence
    reset has already taken care of that.
    """
    LicenceType = apps.get_model("profiles", "LicenceType")

    # Define the new licences to be added.
    NEW_LICENCES = [
        "UEFA Goalkeeper A",
        "UEFA Goalkeeper B",
    ]

    # Create LicenceType instances for each new licence.
    for licence_name in NEW_LICENCES:
        LicenceType.objects.create(name=licence_name)


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0091_migratepositiondata"),
    ]

    operations = [
        migrations.RunPython(reset_licence_type_sequence),
        migrations.RunPython(add_new_licences),
    ]
