# Generated by Django 3.2 on 2023-08-04 15:30

from django.db import migrations, models


def set_shortcuts_and_score_positions(apps, schema_editor) -> None:
    """
    Populates the `shortcut` and `score_position` fields for all `PlayerPosition` objects.

    This function adds or updates the shortcut and score position for each player position,
    based on a predefined mapping. If a player position does not exist in the database,
    it will be created.
    """

    PlayerPosition = apps.get_model("profiles", "PlayerPosition")
    positions_and_shortcuts = {
        "Bramkarz": ("GK", "Bramkarz"),
        "Skrzydłowy": ("W", "Ofensywny pomocnik"),
        "Pomocnik Ofensywny (10)": ("CAM", "Ofensywny pomocnik"),
        "Pomocnik Defensywny (6)": ("DM", "Defensywny pomocnik"),
        "Pomocnik Środkowy (8)": ("CM", "Ofensywny pomocnik"),
        "Obrońca Środkowy": ("CB", "Obrońca"),
        "Obrońca Prawy": ("RB", "Obrońca"),
        "Obrońca Lewy": ("LB", "Obrońca"),
        "Lewy pomocnik": ("LM", "Ofensywny pomocnik"),
        "Prawy pomocnik": ("RM", "Ofensywny pomocnik"),
        "Napastnik": ("F", "Napastnik"),
        "Wahadłowy lewy": ("LWB", "Obrońca"),
        "Wahadłowy prawy": ("RWB", "Obrońca"),
    }
    for name, (shortcut, score_position) in positions_and_shortcuts.items():
        position, created = PlayerPosition.objects.get_or_create(name=name)
        position.shortcut = shortcut  # Set the position shortcut
        position.score_position = score_position  # Set the score_position
        position.save()


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0092_reset_licencetype_sequence_and_add_licences"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerposition",
            name="shortcut",
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.RunPython(set_shortcuts_and_score_positions),
    ]
