# Generated by Django 3.2 on 2023-08-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0093_playerposition_shortcut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerposition",
            name="shortcut",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
