# Generated by Django 3.2 on 2023-08-04 10:21

from django.db import migrations, models
import django.db.models.deletion
import profiles.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("external_links", "0002_alter_externallinksentity_related_type"),
        ("users", "0006_alter_user_declared_role"),
        ("clubs", "0083_auto_20230318_0028"),
        ("profiles", "0094_alter_playerposition_shortcut"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="refereelevel",
            options={
                "verbose_name": "Referee Level",
                "verbose_name_plural": "Referee Levels",
            },
        ),
        migrations.AlterField(
            model_name="refereelevel",
            name="role",
            field=models.CharField(
                choices=[
                    ("Referee", "Sędzia główny"),
                    ("Assistant Referee", "Asystent"),
                ],
                help_text="The role referee plays on this level (Referee or Assistant Referee).",
                max_length=17,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="rolechangerequest",
            name="new",
            field=models.CharField(
                choices=[
                    ("P", "Piłkarz"),
                    ("T", "Trener"),
                    ("C", "Działacz klubu"),
                    ("M", "Menadżer"),
                    ("S", "Skaut"),
                    ("R", "Rodzic małego piłkarza"),
                    ("G", "Kibic"),
                    ("O", "Inne"),
                    ("A", "Sędzia"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="RefereeProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="users.user",
                    ),
                ),
                (
                    "data_mapper_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID of object placed in data_ database. It should alwayes reflect scheme which represents.",
                        null=True,
                    ),
                ),
                ("slug", models.CharField(blank=True, editable=False, max_length=255)),
                (
                    "bio",
                    models.CharField(
                        blank=True,
                        max_length=455,
                        null=True,
                        verbose_name="Krótki opis o sobie",
                    ),
                ),
                ("event_log", models.JSONField(blank=True, null=True)),
                ("step", models.IntegerField(blank=True, default=None, null=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "external_links",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="external_links.externallinks",
                    ),
                ),
                (
                    "history",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profilevisithistory",
                    ),
                ),
                (
                    "verification",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="profiles.profileverificationstatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referee Profile",
                "verbose_name_plural": "Referee Profiles",
            },
            bases=(models.Model, profiles.models.EventLogMixin),
        ),
        migrations.AddField(
            model_name="refereelevel",
            name="referee_profile",
            field=models.ForeignKey(
                help_text="The referee profile that this particular level and role combination is associated with.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.refereeprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="refereelevel",
            unique_together={("level", "role", "referee_profile")},
        ),
    ]
