# Generated by Django 3.2 on 2023-08-17 15:56

from django.db import migrations


def migrate_positions(apps, schema_editor) -> None:
    """
    Migrates PlayerProfilePosition instances that have the positions
    "Wahadłowy lewy" or "Wahadłowy prawy" to "Obrońca Lewy" and "Obrońca Prawy" respectively.
    """
    PlayerPosition = apps.get_model("profiles", "PlayerPosition")
    PlayerProfilePosition = apps.get_model("profiles", "PlayerProfilePosition")

    # Fetch old and new positions
    pos_wahadlowy_lewy = PlayerPosition.objects.get(name="Wahadłowy lewy")
    pos_wahadlowy_prawy = PlayerPosition.objects.get(name="Wahadłowy prawy")
    pos_obronca_lewy = PlayerPosition.objects.get(name="Obrońca Lewy")
    pos_obronca_prawy = PlayerPosition.objects.get(name="Obrońca Prawy")

    # Update PlayerProfilePosition
    PlayerProfilePosition.objects.filter(player_position=pos_wahadlowy_lewy).update(
        player_position=pos_obronca_lewy
    )
    PlayerProfilePosition.objects.filter(player_position=pos_wahadlowy_prawy).update(
        player_position=pos_obronca_prawy
    )


def delete_profiles_positions_with_obsolete_position(apps, schema_editor) -> None:
    """
    Deletes all PlayerProfilePosition instances where the position is "Dowolna".
    Note: The "Dowolna" position is being removed from use.
    """
    PlayerPosition = apps.get_model("profiles", "PlayerPosition")
    PlayerProfilePosition = apps.get_model("profiles", "PlayerProfilePosition")

    pos_dowolna = PlayerPosition.objects.filter(name="Dowolna")

    if pos_dowolna:
        PlayerProfilePosition.objects.filter(player_position__in=pos_dowolna).delete()


def delete_unnecessary_positions(apps, schema_editor) -> None:
    """
    Deletes PlayerPosition entries for "Wahadłowy lewy", "Wahadłowy prawy", and "Dowolna".
    """
    PlayerPosition = apps.get_model("profiles", "PlayerPosition")
    PlayerPosition.objects.filter(
        name__in=["Wahadłowy lewy", "Wahadłowy prawy", "Dowolna"]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0095_create_refereeprofile_and_update_refereelevel"),
    ]

    operations = [
        migrations.RunPython(migrate_positions),
        migrations.RunPython(delete_profiles_positions_with_obsolete_position),
        migrations.RunPython(delete_unnecessary_positions),
    ]
