# Generated by Django 3.2 on 2023-08-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0083_auto_20230318_0028'),
        ('profiles', '0096_auto_20230817_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refereelevel',
            old_name='role',
            new_name='referee_role',
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='formation',
            field=models.CharField(blank=True, choices=[('5-3-2', '5-3-2'), ('5-4-1', '5-4-1'), ('4-4-2', '4-4-2'), ('4-5-1', '4-5-1'), ('4-3-3', '4-3-3'), ('4-2-3-1', '4-2-3-1'), ('4-1-4-1', '4-1-4-1'), ('4-3-2-1', '4-3-2-1'), ('3-5-2', '3-5-2'), ('3-4-3', '3-4-3'), ('4-3-1-2', '4-3-1-2'), ('4-4-1-1', '4-4-1-1')], help_text='This field represents the preferred formation of the coach.', max_length=7, null=True, verbose_name='Formacja'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='formation',
            field=models.CharField(blank=True, choices=[('5-3-2', '5-3-2'), ('5-4-1', '5-4-1'), ('4-4-2', '4-4-2'), ('4-5-1', '4-5-1'), ('4-3-3', '4-3-3'), ('4-2-3-1', '4-2-3-1'), ('4-1-4-1', '4-1-4-1'), ('4-3-2-1', '4-3-2-1'), ('3-5-2', '3-5-2'), ('3-4-3', '3-4-3'), ('4-3-1-2', '4-3-1-2'), ('4-4-1-1', '4-4-1-1')], max_length=15, null=True, verbose_name='Formacja'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='formation_alt',
            field=models.CharField(blank=True, choices=[('5-3-2', '5-3-2'), ('5-4-1', '5-4-1'), ('4-4-2', '4-4-2'), ('4-5-1', '4-5-1'), ('4-3-3', '4-3-3'), ('4-2-3-1', '4-2-3-1'), ('4-1-4-1', '4-1-4-1'), ('4-3-2-1', '4-3-2-1'), ('3-5-2', '3-5-2'), ('3-4-3', '3-4-3'), ('4-3-1-2', '4-3-1-2'), ('4-4-1-1', '4-4-1-1')], max_length=15, null=True, verbose_name='Alternatywna formacja'),
        ),
        migrations.AlterUniqueTogether(
            name='refereelevel',
            unique_together={('level', 'referee_role', 'referee_profile')},
        ),
    ]
