# Generated by Django 3.2 on 2023-08-29 15:35

from django.db import migrations, models


def change_name_and_populate_keys(apps, schema_editor) -> None:
    """
    This function changes the names of the licence types, populates the key and order fields,
    and creates a new licence type if it does not already exist.
    """
    LicenceType = apps.get_model("profiles", "LicenceType")

    # create new LicenceType object if not exists
    if not LicenceType.objects.filter(name="UEFA Futsal C").exists():
        LicenceType.objects.create(name="UEFA Futsal C", key="C", order=None)

    licences = LicenceType.objects.all()
    name_to_key_order = {
        "Jestem w trakcie kursu": {"key": None, "order": 0},
        "UEFA PRO": {"key": "PRO", "order": 1},
        "UEFA EY A": {"key": "EY A", "order": 2},
        "UEFA A": {"key": "A", "order": 3},
        "UEFA B": {"key": "B", "order": 4},
        "UEFA C": {"key": "C", "order": 5},
        "Grassroots C": {"key": "C", "order": 6},
        "Grassroots D": {"key": "D", "order": 7},
        "UEFA Goalkeeper A": {"key": "A", "order": 8},
        "UEFA Goalkeeper B": {"key": "B", "order": 9},
        "UEFA Futsal B": {"key": "B", "order": 10},
        "UEFA Futsal C": {"key": "C", "order": 11},
        "PZPN A": {"key": "A", "order": 12},
        "PZPN B": {"key": "B", "order": 13},
    }

    for licence in licences:
        # change "W trakcie kursu" to "Jestem w trakcie kursu"
        if licence.name == "W trakcie kursu":
            licence.name = "Jestem w trakcie kursu"
        # change "GRASS" to "Grassroots"
        if "GRASS" in licence.name:
            licence.name = licence.name.replace("GRASS", "Grassroots")
        # populate the key and order fields
        data = name_to_key_order.get(licence.name)
        if data:
            licence.key = data["key"]
            licence.order = data["order"]
        licence.save()


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0097_auto_20230823_2100"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="licencetype",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="licencetype",
            name="key",
            field=models.CharField(
                help_text="Key of the licence",
                max_length=10,
                null=True,
                verbose_name="Key",
            ),
        ),
        migrations.AddField(
            model_name="licencetype",
            name="order",
            field=models.PositiveIntegerField(
                help_text="Order in which the licence will be listed.",
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="licencetype",
            name="name",
            field=models.CharField(
                help_text="Type of the licence",
                max_length=25,
                unique=True,
                verbose_name="Licencja",
            ),
        ),
        migrations.RunPython(change_name_and_populate_keys),
    ]
