# Generated by Django 3.2 on 2023-08-31 18:41

from django.db import migrations, models
import django.db.models.deletion
from profiles.models import PROFILE_MODELS, PROFILE_TYPE


def create_verification_stage(apps, schema_editor) -> None:
    """Loop through each profile, then create verification_stage if it doesn't exist"""
    VerificationStage = apps.get_model("profiles", "VerificationStage")
    for profile_type in PROFILE_MODELS:
        Profile: PROFILE_TYPE = apps.get_model("profiles", profile_type.__name__)
        for profile in Profile.objects.all():
            profile.verification_stage = VerificationStage.objects.create()
            profile.save()


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0097_auto_20230823_2100"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationStage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.IntegerField(default=0)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
                ("done", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="clubprofile",
            name="step",
        ),
        migrations.RemoveField(
            model_name="coachprofile",
            name="step",
        ),
        migrations.RemoveField(
            model_name="guestprofile",
            name="step",
        ),
        migrations.RemoveField(
            model_name="managerprofile",
            name="step",
        ),
        migrations.RemoveField(
            model_name="otherprofile",
            name="step",
        ),
        migrations.RemoveField(
            model_name="parentprofile",
            name="step",
        ),
        migrations.RemoveField(
            model_name="playerprofile",
            name="step",
        ),
        migrations.RemoveField(
            model_name="refereeprofile",
            name="step",
        ),
        migrations.RemoveField(
            model_name="scoutprofile",
            name="step",
        ),
        migrations.AddField(
            model_name="clubprofile",
            name="verification_stage",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.verificationstage",
            ),
        ),
        migrations.AddField(
            model_name="coachprofile",
            name="verification_stage",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.verificationstage",
            ),
        ),
        migrations.AddField(
            model_name="guestprofile",
            name="verification_stage",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.verificationstage",
            ),
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="verification_stage",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.verificationstage",
            ),
        ),
        migrations.AddField(
            model_name="otherprofile",
            name="verification_stage",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.verificationstage",
            ),
        ),
        migrations.AddField(
            model_name="parentprofile",
            name="verification_stage",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.verificationstage",
            ),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="verification_stage",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.verificationstage",
            ),
        ),
        migrations.AddField(
            model_name="refereeprofile",
            name="verification_stage",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.verificationstage",
            ),
        ),
        migrations.AddField(
            model_name="scoutprofile",
            name="verification_stage",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.verificationstage",
            ),
        ),
        migrations.RunPython(create_verification_stage),
    ]
