# Generated by Django 3.2 on 2023-09-04 20:36

from django.db import migrations, models
from django.db.models import QuerySet

from profiles.models import ClubProfile


def migrate_club_roles(apps, schema_editor) -> None:  # noqa
    """
    Perform migration of club roles in the database.

    This function migrates club roles stored in the database based on predefined role mappings.
    It updates the existing club profiles' roles according to the provided mappings, and also
    adjusts the role values for specific cases.
    Note:
        This migration is designed to convert old club role values to new role values as per the
        defined role mappings. It iterates through all club profiles and updates their roles
        accordingly.

    Examples:
        Calling this function during a database migration will update club profile roles based
        on predefined mappings and special cases. For instance, if a club profile has a role
        "Kierownik (2)", it will be updated to "Kierownik drużyny" and assigned a new role value of 5.
    """  # noqa: E501

    old_mapping = dict(
        (
            (1, "Prezes"),
            (2, "Kierownik"),
            (3, "Członek zarządu"),
            (4, "Sztab szkoleniowy"),
            (5, "Trener"),
            (6, "V-ce prezes"),
            (7, "II trener"),
            (8, "Dyrektor sportowy"),
            (9, "Analityk"),
            (10, "Dyrektor skautingu"),
            (11, "Skaut"),
            (12, "Trener bramkarzy"),
            (13, "Koordynator"),
        )
    )

    ClubProfileModel: ModelBase = apps.get_model("profiles", "ClubProfile")  # noqa
    club_profiles: QuerySet[ClubProfile] = ClubProfileModel.objects.all()

    for club_profile in club_profiles:
        if club_profile.club_role:
            if old_mapping[club_profile.club_role] == "Kierownik":
                club_profile._temporary_field_club_role = "Kierownik Drużyny"
            else:
                club_profile._temporary_field_club_role = old_mapping[
                    club_profile.club_role
                ]
            club_profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0099_alter_licencetype_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubprofile",
            name="_temporary_field_club_role",
            field=models.CharField(
                blank=True, help_text="Defines club role", max_length=128, null=True
            ),
        ),
        migrations.RunPython(migrate_club_roles),
    ]
