# Generated by Django 3.2 on 2023-09-04 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0098_playervideo_label"),
        ("profiles", "0099_alter_licencetype_order"),
    ]

    operations = []
