# Generated by Django 3.2.21 on 2023-09-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0098_auto_20230831_2041'),
        ('profiles', '0100_merge_20230904_1725'),
    ]

    operations = [
    ]
