# Generated by Django 3.2 on 2023-09-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0100_clubprofile__temporary_field_club_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubprofile",
            name="club_role",
            field=models.CharField(
                blank=True,
                help_text="Defines if admin approved change",
                max_length=128,
                null=True,
            ),  # noqa: E501
        ),
    ]
