# Generated by Django 3.2 on 2023-09-04 20:46

from django.db import migrations
from django.db.models import QuerySet

from profiles.models import ClubProfile


def migrate_club_roles(apps, schema_editor) -> None:  # noqa
    """
    Map _temporary_field_club_role field value to new club_profile field
    (changed typing from int to string)
    """

    ClubProfileModel: ModelBase = apps.get_model("profiles", "ClubProfile")  # noqa
    club_profiles: QuerySet[ClubProfile] = ClubProfileModel.objects.all()

    for club_profile in club_profiles:
        club_profile.club_role = club_profile._temporary_field_club_role  # noqa
        club_profile.save()


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0101_alter_clubprofile_club_role"),
    ]

    operations = [
        migrations.RunPython(migrate_club_roles),
        migrations.RemoveField(
            model_name="clubprofile",
            name="_temporary_field_club_role",
        ),
    ]
