# Generated by Django 3.2 on 2023-09-07 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0101_merge_20230906_1010'),
        ('profiles', '0102_remove_clubprofile__temporary_field_club_role'),
    ]

    operations = [
    ]
