# Generated by Django 3.2.21 on 2023-09-08 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0088_merge_20230726_1159"),
        ("profiles", "0103_merge_20230907_1126"),
    ]

    operations = []
