# Generated by Django 3.2.21 on 2023-09-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0104_merge_20230908_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refereelevel',
            name='referee_role',
            field=models.CharField(choices=[('Referee', 'Sędzia główny'), ('AssistantReferee', 'Asystent')], help_text='The role referee plays on this level (Referee or Assistant Referee).', max_length=17, verbose_name='Role'),
        ),
    ]
