# Generated by Django 3.2.21 on 2023-09-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0105_alter_refereelevel_referee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencetype',
            name='key',
            field=models.CharField(blank=True, help_text='Key of the licence', max_length=10, null=True, verbose_name='Key'),
        ),
    ]
