# Generated by Django 3.2.21 on 2023-09-26 18:03

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


def move_ownership_from_coach_to_user(apps, schema_editor) -> None:
    """Move ownership from CoachProfile to User."""
    User = apps.get_model(settings.AUTH_USER_MODEL)
    CoachLicence = apps.get_model("profiles", "CoachLicence")

    for licence in CoachLicence.objects.all():
        if licence.coach_profile:
            licence.owner = User.objects.get(pk=licence.coach_profile.user.pk)
            licence.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_auto_20230918_0219"),
        ("profiles", "0106_alter_licencetype_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachlicence",
            name="is_in_progress",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="coachlicence",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="User holding this license",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="coachlicence",
            name="release_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(move_ownership_from_coach_to_user),
    ]
