# Generated by Django 3.2.21 on 2023-09-26 18:04

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_auto_20230918_0219"),
        ("profiles", "0107_auto_20230926_2003"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coachlicence",
            name="owner",
            field=models.ForeignKey(
                help_text="User holding this license",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coachlicence",
            unique_together={("licence", "owner")},
        ),
        migrations.RemoveField(
            model_name="coachlicence",
            name="coach_profile",
        ),
    ]
