# Generated by Django 3.2.21 on 2023-09-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0108_auto_20230926_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='agency_facebook_url',
            field=models.URLField(blank=True, help_text="URL of the managing agency's Facebook profile.", max_length=500, null=True, verbose_name='Agency Facebook URL'),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='agency_other_url',
            field=models.URLField(blank=True, help_text='Other agency URL.', max_length=500, null=True, verbose_name='Agency Facebook URL'),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='other_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Other'),
        ),
    ]
