# Generated by Django 3.2.21 on 2023-09-28 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_userpreferences(apps, user_id: int) -> None:
    """Create UserPreferences for each user"""
    User = apps.get_model("users", "User")
    UserPreferences = apps.get_model("users", "UserPreferences")

    for user in User.objects.all():
        UserPreferences.objects.get_or_create(user=user)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0109_auto_20230927_1915"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("release_year", models.IntegerField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_userpreferences),
    ]
