# Generated by Django 3.2.21 on 2023-10-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0110_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationstage",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
