# Generated by Django 3.2 on 2023-10-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0088_auto_20230930_1920"),
        ("profiles", "0110_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamContributor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_uuid",
                    models.UUIDField(
                        db_index=True, help_text="UUID of the related profile."
                    ),
                ),
                (
                    "round",
                    models.CharField(
                        blank=True,
                        choices=[("wiosenna", "wiosenna"), ("jesienna", "jesienna")],
                        default=None,
                        help_text="Seasonal round for the contribution.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Determines if this is the primary contributor for the season and round.",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Start date of the contribution.",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="End date of the contribution.", null=True
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IC", "Pierwszy trener"),
                            ("IIC", "Drugi trener"),
                            ("GKC", "Trener bramkarzy"),
                            ("FIC", "Trener motoryki"),
                            ("MEC", "Trener mentalny"),
                            ("ANC", "Analityk"),
                            ("OTC", "Inne"),
                        ],
                        help_text="Role of the contributor in the team.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "is_actual",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this Team is the current one.",
                    ),
                ),
                ("team_history", models.ManyToManyField(to="clubs.TeamHistory")),
            ],
            options={
                "ordering": [
                    "-team_history__league_history__season__name",
                    "-is_primary",
                    "round",
                ],
            },
        ),
    ]
