# Generated by Django 3.2 on 2023-10-04 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0111_teamcontributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Youtube url')),
                ('title', models.CharField(blank=True, max_length=235, null=True, verbose_name='Tytuł nagrania')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('label', models.IntegerField(blank=True, choices=[(1, 'Skrót meczu'), (2, 'Cały mecz'), (3, 'Bramka')], null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_video', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player Video',
                'verbose_name_plural': 'Player Videos',
            },
        ),
        migrations.DeleteModel(
            name='PlayerVideo',
        ),
    ]
