# Generated by Django 3.2 on 2023-10-04 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0112_auto_20231004_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilevideo',
            options={'verbose_name': 'Profile Video', 'verbose_name_plural': 'Profile Videos'},
        ),
    ]
