# Generated by Django 3.2 on 2023-10-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0113_alter_profilevideo_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilevideo',
            old_name='player',
            new_name='user',
        ),
    ]
