# Generated by Django 3.2 on 2023-10-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0111_alter_verificationstage_date_updated'),
        ('profiles', '0114_rename_player_profilevideo_user'),
    ]

    operations = [
    ]
