# Generated by Django 3.2.21 on 2023-10-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0115_merge_20231007_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilevideo',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
