# Generated by Django 3.2.21 on 2023-10-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0116_profilevideo_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilevideo",
            name="label",
            field=models.CharField(
                blank=True,
                choices=[
                    ("player_short", "Skrót meczu"),
                    ("player_full", "Cały mecz"),
                    ("player_goal", "Bramka"),
                    ("coach_short", "Skrót meczu"),
                    ("coach_full", "Cały mecz"),
                    ("coach_analysis", "Analiza"),
                    ("scout_player_analysis", "Piłkarz"),
                    ("scout_tactics", "Taktyka"),
                    ("scout_fragment", "Stałe fragmenty"),
                    ("club_short", "Skrót meczu"),
                    ("club_full", "Cały mecz"),
                    ("club_analysis", "Analiza"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
