# Generated by Django 3.2 on 2023-10-07 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0116_profilevideo_date_created"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teamcontributor",
            unique_together={("profile_uuid", "role", "start_date")},
        ),
        migrations.RemoveField(
            model_name="teamcontributor",
            name="is_actual",
        ),
    ]
