# Generated by Django 3.2.21 on 2023-10-17 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0117_alter_profilevideo_label'),
        ('profiles', '0117_auto_20231007_1527'),
    ]

    operations = [
    ]
