# Generated by Django 3.2 on 2023-10-18 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('external_links', '0004_alter_externallinksentity_target'),
        ('profiles', '0118_merge_20231017_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='external_links',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='external_links.externallinks'),
        ),
    ]
