# Generated by Django 3.2.21 on 2023-10-27 14:30

from django.db import migrations
from django.db.migrations.state import StateApps as _StateApps


def move_parent_profile_to_guest_profile(apps: _StateApps, *_) -> None:
    """Migrate ParentProfile to GuestProfile."""
    ParentProfile = apps.get_model("profiles", "ParentProfile")
    GuestProfile = apps.get_model("profiles", "GuestProfile")

    for parent in ParentProfile.objects.all():
        data = parent.__dict__
        data.pop("_state")
        GuestProfile.objects.update_or_create(pk=parent.pk, defaults=data)


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0119_clubprofile_external_links"),
    ]

    operations = [
        migrations.RunPython(move_parent_profile_to_guest_profile),
        migrations.RemoveField(
            model_name="parentprofile",
            name="history",
        ),
        migrations.RemoveField(
            model_name="parentprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="parentprofile",
            name="verification",
        ),
        migrations.RemoveField(
            model_name="parentprofile",
            name="verification_stage",
        ),
        migrations.DeleteModel(
            name="ParentProfile",
        ),
    ]
