# Generated by Django 3.2 on 2023-10-26 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0088_auto_20230930_1920"),
        ("profiles", "0120_auto_20231027_1630"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubprofile",
            name="team_history_object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="club_profiles_history",
                to="clubs.teamhistory",
            ),
        ),
        migrations.AddField(
            model_name="clubprofile",
            name="team_object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="club_profiles",
                to="clubs.team",
            ),
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="team_history_object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managers_history",
                to="clubs.teamhistory",
            ),
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="team_object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manager_profiles",
                to="clubs.team",
            ),
        ),
        migrations.AddField(
            model_name="scoutprofile",
            name="team_history_object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scouts_history",
                to="clubs.teamhistory",
            ),
        ),
        migrations.AddField(
            model_name="scoutprofile",
            name="team_object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scouts",
                to="clubs.team",
            ),
        ),
        migrations.AddField(
            model_name="teamcontributor",
            name="is_primary_for_round",
            field=models.BooleanField(
                default=False,
                help_text="Determines if this is the primary contributor for the season and round.",
            ),
        ),
        migrations.AlterField(
            model_name="teamcontributor",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Determines if this is the actual contribution.",
            ),
        ),
    ]
