# Generated by Django 3.2 on 2023-10-31 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0089_leaguehistory_year'),
        ('profiles', '0121_auto_20231026_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestprofile',
            name='team_history_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_history', to='clubs.teamhistory'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='team_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_profiles', to='clubs.team'),
        ),
        migrations.AlterField(
            model_name='rolechangerequest',
            name='new',
            field=models.CharField(choices=[('P', 'Piłkarz'), ('T', 'Trener'), ('C', 'Działacz klubu'), ('M', 'Menadżer'), ('S', 'Skaut'), ('G', 'Kibic'), ('O', 'Inne'), ('A', 'Sędzia')], max_length=100),
        ),
    ]
