# Generated by Django 3.2 on 2023-11-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0122_auto_20231031_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='custom_club_role',
            field=models.CharField(blank=True, help_text='Custom club role specified by the user.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='custom_coach_role',
            field=models.CharField(blank=True, help_text='Custom club role specified by the user.', max_length=255, null=True, verbose_name='Custom Coach Role'),
        ),
    ]
