# Generated by Django 3.2 on 2023-11-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0123_auto_20231101_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcontributor',
            name='custom_role',
            field=models.CharField(blank=True, help_text="Custom role of the contributor when 'Other' is selected.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teamcontributor',
            name='role',
            field=models.CharField(blank=True, choices=[('IC', 'Pierwszy trener'), ('IIC', 'Drugi trener'), ('GKC', 'Trener bramkarzy'), ('FIC', 'Trener motoryki'), ('MEC', 'Trener mentalny'), ('ANC', 'Analityk'), ('OTC', 'Inne'), ('P', 'Prezes'), ('DSp', 'Dyrektor sportowy'), ('CZ', 'Członek zarządu'), ('DSk', 'Dyrektor skautingu'), ('KD', 'Kierownik drużyny'), ('O', 'Inne')], help_text='Role of the contributor in the team.', max_length=50, null=True),
        ),
    ]
