# Generated by Django 3.2 on 2023-11-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0124_auto_20231104_2253"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubprofile",
            name="data_fulfill_status",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "Uzupełnione"),
                    (2, "Częściowo uzupełnione"),
                    (3, "Nie uzupełnione"),
                ],
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coachprofile",
            name="data_fulfill_status",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "Uzupełnione"),
                    (2, "Częściowo uzupełnione"),
                    (3, "Nie uzupełnione"),
                ],
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="guestprofile",
            name="data_fulfill_status",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "Uzupełnione"),
                    (2, "Częściowo uzupełnione"),
                    (3, "Nie uzupełnione"),
                ],
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="data_fulfill_status",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "Uzupełnione"),
                    (2, "Częściowo uzupełnione"),
                    (3, "Nie uzupełnione"),
                ],
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="otherprofile",
            name="data_fulfill_status",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "Uzupełnione"),
                    (2, "Częściowo uzupełnione"),
                    (3, "Nie uzupełnione"),
                ],
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="data_fulfill_status",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "Uzupełnione"),
                    (2, "Częściowo uzupełnione"),
                    (3, "Nie uzupełnione"),
                ],
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="refereeprofile",
            name="data_fulfill_status",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "Uzupełnione"),
                    (2, "Częściowo uzupełnione"),
                    (3, "Nie uzupełnione"),
                ],
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scoutprofile",
            name="data_fulfill_status",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "Uzupełnione"),
                    (2, "Częściowo uzupełnione"),
                    (3, "Nie uzupełnione"),
                ],
                editable=False,
                max_length=255,
                null=True,
            ),
        ),
    ]
