# Generated by Django 3.2 on 2023-11-12 23:39

from django.db import migrations, models


def map_old_roles_to_new(apps, schema_editor) -> None:
    """
    Migrates existing `club_role` values in the ClubProfile model to conform to predefined choices.

    This function iterates over all instances of ClubProfile and updates the `club_role` field
    based on a predefined mapping. If a `club_role` value does not match any key in the
    mapping and is not empty, it is set to "Other" (represented by "O"), and the original `club_role` value
    is preserved in the `custom_club_role` field. This ensures that custom roles are not lost during the
    transition to standardized role names.

    The function is designed to transition from descriptive role names to a new system of short codes
    and a separate field for custom roles, enhancing data consistency and structure.
    """
    ClubProfile = apps.get_model("profiles", "ClubProfile")

    # Mapping from old descriptive roles to new short codes
    role_mapping = {
        "prezes": "P",
        "dyrektor sportowy": "DSp",
        "członek zarządu": "CZ",
        "dyrektor skautingu": "DSk",
        "kierownik drużyny": "KD",
    }

    for profile in ClubProfile.objects.all():
        lower_case_role = (
            profile.club_role.lower() if profile.club_role else profile.club_role
        )
        if lower_case_role in role_mapping:
            profile.club_role = role_mapping[lower_case_role]
        elif profile.club_role and lower_case_role not in role_mapping.values():
            profile.custom_club_role = profile.club_role  # Preserving the original role
            profile.club_role = "O"  # Setting to "Other"
        profile.save()


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0124_auto_20231104_2253"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubprofile",
            name="club_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P", "Prezes"),
                    ("DSp", "Dyrektor sportowy"),
                    ("CZ", "Członek zarządu"),
                    ("DSk", "Dyrektor skautingu"),
                    ("KD", "Kierownik drużyny"),
                    ("O", "Inne"),
                ],
                help_text="Defines if admin approved change",
                max_length=128,
                null=True,
            ),
        ),
        migrations.RunPython(map_old_roles_to_new),
    ]
