# Generated by Django 3.2 on 2023-11-12 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0124_auto_20231104_2253'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamcontributor',
            unique_together=set(),
        ),
    ]
