# Generated by Django 3.2 on 2023-11-12 22:08

from typing import List

from django.db import migrations

from profiles.managers import ProfileManager


def migrate_fulfill_score(apps, schema_editor) -> None:  # noqa
    loop_able_profiles = []

    PlayerProfile = apps.get_model("profiles", "PlayerProfile")
    CoachProfile = apps.get_model("profiles", "CoachProfile")
    ScoutProfile = apps.get_model("profiles", "ScoutProfile")
    ManagerProfile = apps.get_model("profiles", "ManagerProfile")
    ClubProfile = apps.get_model("profiles", "ClubProfile")
    GuestProfile = apps.get_model("profiles", "GuestProfile")

    players: List[PlayerProfile] = list(PlayerProfile.objects.all())
    coaches: List[CoachProfile] = list(CoachProfile.objects.all())
    scouts: List[ScoutProfile] = list(ScoutProfile.objects.all())
    managers: List[ManagerProfile] = list(ManagerProfile.objects.all())
    clubs: List[ClubProfile] = list(ClubProfile.objects.all())
    guests: List[GuestProfile] = list(GuestProfile.objects.all())

    loop_able_profiles.extend(players)
    loop_able_profiles.extend(coaches)
    loop_able_profiles.extend(scouts)
    loop_able_profiles.extend(managers)
    loop_able_profiles.extend(clubs)
    loop_able_profiles.extend(guests)

    for profile in loop_able_profiles:
        manager = ProfileManager()
        profile.data_fulfill_status = manager.get_data_score(profile)
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0125_auto_20231112_1230"),
    ]

    operations = [migrations.RunPython(migrate_fulfill_score)]
