# Generated by Django 3.2 on 2023-11-12 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0125_alter_clubprofile_club_role"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teamcontributor",
            unique_together=set(),
        ),
    ]
