# Generated by Django 3.2 on 2023-11-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0126_alter_teamcontributor_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='dial_code',
            field=models.CharField(blank=True, help_text='Country dial code for the agency phone number.', max_length=5, null=True, verbose_name='Dial Code'),
        ),
    ]
