# Generated by Django 3.2 on 2023-11-15 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0125_alter_clubprofile_club_role'),
        ('profiles', '0126_auto_20231112_2308'),
    ]

    operations = [
    ]
