# Generated by Django 3.2 on 2023-11-16 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0126_alter_teamcontributor_unique_together'),
        ('profiles', '0127_merge_20231115_0932'),
    ]

    operations = [
    ]
