# Generated by Django 3.2 on 2023-11-19 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0127_managerprofile_dial_code'),
        ('profiles', '0128_merge_20231116_1850'),
    ]

    operations = [
    ]
