# Generated by Django 3.2 on 2023-11-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0129_merge_20231119_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestprofile',
            name='custom_role',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom Role'),
        ),
    ]
