# Generated by Django 3.2 on 2023-11-24 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inquiries', '0007_created_mail_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0130_guestprofile_custom_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilevisithistory',
            old_name='counter',
            new_name='counter_anonymoususer',
        ),
        migrations.RenameField(
            model_name='profilevisithistory',
            old_name='counter_coach',
            new_name='counter_clubprofile',
        ),
        migrations.RenameField(
            model_name='profilevisithistory',
            old_name='counter_scout',
            new_name='counter_coachprofile',
        ),
        migrations.AddField(
            model_name='profilevisithistory',
            name='counter_guestprofile',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilevisithistory',
            name='counter_managerprofile',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilevisithistory',
            name='counter_playerprofile',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilevisithistory',
            name='counter_refereeprofile',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilevisithistory',
            name='counter_scoutprofile',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilevisithistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilevisithistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profilevisithistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_visit_history', to='users.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProfileTransferStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(blank=True, choices=[('1', 'Szukam klubu'), ('2', 'Rozważę propozycje'), ('3', 'Nie szukam klubu'), ('4', 'Piłkarska emerytura')], help_text='Defines a status of the transfer for the profile.', max_length=255, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquiries.inquirycontact')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
