# Generated by Django 3.2 on 2023-11-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0131_auto_20231124_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubprofile',
            name='history',
        ),
        migrations.RemoveField(
            model_name='coachprofile',
            name='history',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='history',
        ),
        migrations.RemoveField(
            model_name='managerprofile',
            name='history',
        ),
        migrations.RemoveField(
            model_name='otherprofile',
            name='history',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='history',
        ),
        migrations.RemoveField(
            model_name='refereeprofile',
            name='history',
        ),
        migrations.RemoveField(
            model_name='scoutprofile',
            name='history',
        ),
    ]
