# Generated by Django 3.2 on 2023-11-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0132_auto_20231125_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiletransferstatus',
            name='contact',
        ),
        migrations.AddField(
            model_name='profiletransferstatus',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email address for the transfer.', max_length=254, null=True, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='profiletransferstatus',
            name='contact_phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number for the transfer.', max_length=15, null=True, verbose_name='Contact Phone Number'),
        ),
    ]
