# Generated by Django 3.2 on 2023-11-30 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('profiles', '0133_auto_20231128_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTransferRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], help_text='Define team gender', max_length=10)),
                ('status', models.CharField(blank=True, choices=[('1', 'Nieznany'), ('2', 'Szukam piłkarzy'), ('3', 'Nie szukam piłkarzy')], help_text='Defines a status of the transfer for the profile.', max_length=255, null=True)),
                ('position', models.CharField(choices=[('1', 'Dowolna pozycja'), ('2', 'Bramkarz'), ('3', 'Środkowy obrońca'), ('4', 'Lewy obrońca'), ('5', 'Prawy obrońca'), ('6', 'Defensywny pomocnik'), ('7', 'Środkowy pomocnik'), ('8', 'Ofensywny pomocnik'), ('9', 'Lewy pomocnik'), ('10', 'Prawy pomocnik'), ('11', 'Napastnik')], help_text='Define team position', max_length=10)),
                ('number_of_trainings', models.CharField(choices=[('1', '1-2 treningi tygodniowo'), ('2', '3-4 treningi tygodniowo'), ('3', '5+ treningów tygodniowo')], help_text='Define number of trainings per week', max_length=10)),
                ('additional_info', models.CharField(blank=True, choices=[('1', 'Zwrot lub organizacja transportu'), ('2', 'Zwrot za butóy lub rękawice'), ('3', 'Sprzęt treningowy'), ('4', 'Dobre zaplecze treningowe'), ('5', 'Premie za wygrane'), ('6', 'Fizjoterapeuta w sztabie'), ('7', 'Siłownia do dyspozycji'), ('8', 'Walka o awans'), ('9', 'Doświadczony trener')], help_text='Additional information about the transfer request.', max_length=255, null=True)),
                ('salary', models.CharField(choices=[('1', '0 - 499 zł'), ('2', '500 - 999 zł'), ('3', '1000 - 1999 zł'), ('4', '2000 - 3999 zł'), ('5', '4000+ zł')], help_text='Define salary', max_length=10)),
                ('contact_email', models.EmailField(blank=True, help_text='Email address of the contact person.', max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Phone number of the contact person.', max_length=15, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('requesting_team', models.ForeignKey(help_text='The team that is requesting the transfer.', on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='profiles.teamcontributor')),
            ],
        ),
    ]
