# Generated by Django 3.2 on 2023-12-03 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0089_leaguehistory_year'),
        ('profiles', '0134_profiletransferrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletransferstatus',
            name='additional_info',
            field=models.CharField(blank=True, choices=[('1', 'Dostępny od zaraz'), ('2', 'Wracam po kontuzji'), ('3', 'Możliwe wypożyczenie'), ('4', 'Po przeprowadzce'), ('5', 'Studiuje zaoczne'), ('6', 'Pracuje w nieregularnym trybie pracy')], help_text='Additional information about the transfer.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profiletransferstatus',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_status', to='clubs.league'),
        ),
    ]
