# Generated by Django 3.2 on 2023-12-03 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0089_leaguehistory_year'),
        ('profiles', '0135_auto_20231203_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletransferstatus',
            name='additional_info',
            field=models.CharField(choices=[('1', 'Dostępny od zaraz'), ('2', 'Wracam po kontuzji'), ('3', 'Możliwe wypożyczenie'), ('4', 'Po przeprowadzce'), ('5', 'Studiuje zaoczne'), ('6', 'Pracuje w nieregularnym trybie pracy')], default=1, help_text='Additional information about the transfer.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profiletransferstatus',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_status', to='clubs.league'),
        ),
        migrations.AlterField(
            model_name='profiletransferstatus',
            name='status',
            field=models.CharField(choices=[('1', 'Szukam klubu'), ('2', 'Rozważę propozycje'), ('3', 'Nie szukam klubu'), ('4', 'Piłkarska emerytura')], help_text='Defines a status of the transfer for the profile.', max_length=255),
        ),
    ]
