# Generated by Django 3.2 on 2023-12-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0138_auto_20231204_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiletransferstatus',
            name='contact_phone_number',
        ),
        migrations.AddField(
            model_name='profiletransferstatus',
            name='dial_code',
            field=models.CharField(blank=True, help_text='Country dial code for the phone number.', max_length=5, null=True, verbose_name='Dial Code'),
        ),
        migrations.AddField(
            model_name='profiletransferstatus',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for the transfer status.', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profiletransferrequest',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for the transfer request.', max_length=15, null=True),
        ),
    ]
