# Generated by Django 3.2 on 2023-12-04 20:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0139_auto_20231204_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletransferstatus',
            name='additional_info',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('1', 'Dostępny od zaraz'), ('2', 'Wracam po kontuzji'), ('3', 'Możliwe wypożyczenie'), ('4', 'Po przeprowadzce'), ('5', 'Studiuje zaoczne'), ('6', 'Pracuje w nieregularnym trybie pracy')], help_text='Additional information about the transfer.', max_length=10), null=True, size=None),
        ),
    ]
