# Generated by Django 3.2 on 2023-12-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0140_alter_profiletransferstatus_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletransferstatus',
            name='dial_code',
            field=models.IntegerField(blank=True, help_text='Country dial code for the phone number.', max_length=4, null=True, verbose_name='Dial Code'),
        ),
    ]
