# Generated by Django 3.2 on 2023-12-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0090_auto_20231211_2251'),
        ('profiles', '0141_alter_profiletransferstatus_dial_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletransferstatus',
            name='dial_code',
            field=models.IntegerField(blank=True, help_text='Country dial code for the phone number.', null=True, verbose_name='Dial Code'),
        ),
        migrations.AlterField(
            model_name='teamcontributor',
            name='team_history',
            field=models.ManyToManyField(help_text='Teams associated with the contributor.', to='clubs.Team'),
        ),
    ]
