# Generated by Django 3.2 on 2023-12-07 23:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0141_alter_profiletransferstatus_dial_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletransferrequest',
            name='additional_info',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('1', 'Zwrot lub organizacja transportu'), ('2', 'Zwrot za butóy lub rękawice'), ('3', 'Sprzęt treningowy'), ('4', 'Dobre zaplecze treningowe'), ('5', 'Premie za wygrane'), ('6', 'Fizjoterapeuta w sztabie'), ('7', 'Siłownia do dyspozycji'), ('8', 'Walka o awans'), ('9', 'Doświadczony trener')], help_text='Additional information about the transfer request.', max_length=255, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='profiletransferrequest',
            name='position',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('1', 'Dowolna pozycja'), ('2', 'Bramkarz'), ('3', 'Środkowy obrońca'), ('4', 'Lewy obrońca'), ('5', 'Prawy obrońca'), ('6', 'Defensywny pomocnik'), ('7', 'Środkowy pomocnik'), ('8', 'Ofensywny pomocnik'), ('9', 'Lewy pomocnik'), ('10', 'Prawy pomocnik'), ('11', 'Napastnik')], help_text='Define team position', max_length=10), size=None),
        ),
        migrations.AlterField(
            model_name='profiletransferstatus',
            name='dial_code',
            field=models.IntegerField(blank=True, help_text='Country dial code for the phone number.', null=True, verbose_name='Dial Code'),
        ),
    ]
