# Generated by Django 3.2 on 2023-12-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0142_auto_20231208_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletransferrequest',
            name='dial_code',
            field=models.IntegerField(blank=True, help_text='Country dial code for the phone number.', max_length=5, null=True, verbose_name='Dial Code'),
        ),
    ]
