# Generated by Django 3.2 on 2023-12-13 19:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0143_alter_profiletransferrequest_dial_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiletransferrequest',
            name='additional_info',
        ),
        migrations.AddField(
            model_name='profiletransferrequest',
            name='benefits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('1', 'Zwrot lub organizacja transportu'), ('2', 'Zwrot za buty lub rękawice'), ('3', 'Sprzęt treningowy'), ('4', 'Dobre zaplecze treningowe'), ('5', 'Premie za wygrane'), ('6', 'Fizjoterapeuta w sztabie'), ('7', 'Siłownia do dyspozycji'), ('8', 'Walka o awans'), ('9', 'Doświadczony trener')], help_text='Additional information about the transfer.', max_length=255, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='profiletransferrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiletransferrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profiletransferstatus',
            name='benefits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('1', 'Zwrot lub organizacja transportu'), ('2', 'Zwrot za buty lub rękawice'), ('3', 'Sprzęt treningowy'), ('4', 'Dobre zaplecze treningowe'), ('5', 'Premie za wygrane'), ('6', 'Fizjoterapeuta w sztabie'), ('7', 'Siłownia do dyspozycji'), ('8', 'Walka o awans'), ('9', 'Doświadczony trener')], help_text='Additional information about the transfer.', max_length=255, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='profiletransferstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiletransferstatus',
            name='number_of_trainings',
            field=models.CharField(blank=True, choices=[('1', '1-2 treningi tygodniowo'), ('2', '3-4 treningi tygodniowo'), ('3', '5+ treningów tygodniowo')], default=None, help_text='Define number of trainings per week', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profiletransferstatus',
            name='salary',
            field=models.CharField(blank=True, choices=[('1', '0 - 499 zł'), ('2', '500 - 999 zł'), ('3', '1000 - 1999 zł'), ('4', '2000 - 3999 zł'), ('5', '4000+ zł')], default=None, help_text='Define salary', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profiletransferstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profiletransferrequest',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email address for the transfer.', max_length=254, null=True, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='profiletransferrequest',
            name='dial_code',
            field=models.IntegerField(blank=True, help_text='Country dial code for the phone number.', null=True, verbose_name='Dial Code'),
        ),
        migrations.AlterField(
            model_name='profiletransferrequest',
            name='number_of_trainings',
            field=models.CharField(blank=True, choices=[('1', '1-2 treningi tygodniowo'), ('2', '3-4 treningi tygodniowo'), ('3', '5+ treningów tygodniowo')], default=None, help_text='Define number of trainings per week', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profiletransferrequest',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for the transfer.', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profiletransferrequest',
            name='salary',
            field=models.CharField(blank=True, choices=[('1', '0 - 499 zł'), ('2', '500 - 999 zł'), ('3', '1000 - 1999 zł'), ('4', '2000 - 3999 zł'), ('5', '4000+ zł')], default=None, help_text='Define salary', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profiletransferstatus',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for the transfer.', max_length=15, null=True),
        ),
    ]
