# Generated by Django 3.2 on 2023-12-27 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0144_auto_20231213_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilevisithistory',
            name='user_logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profilevisithistory',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='profilevisithistory',
            unique_together={('user', 'created_at')},
        ),
        migrations.AddIndex(
            model_name='profilevisithistory',
            index=models.Index(fields=['user'], name='profiles_pr_user_id_9d0b75_idx'),
        ),
    ]
