# Generated by Django 3.2 on 2023-12-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0090_auto_20231226_2335'),
        ('profiles', '0144_auto_20231213_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcontributor',
            name='team_history',
            field=models.ManyToManyField(help_text='Teams associated with the contributor.', to='clubs.Team'),
        ),
    ]
