# Generated by Django 3.2 on 2023-12-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0145_auto_20231227_0837"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerprofile",
            name="voivodeship_raw",
        ),
        migrations.RemoveField(
            model_name="scoutprofile",
            name="voivodeship_raw",
        ),
        migrations.AddField(
            model_name="playerposition",
            name="shortcut_pl",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
