# Generated by Django 3.2 on 2024-01-02 11:25

from django.db import migrations, models

from profiles.services import PlayerPositionService


def change_position_names(apps, schema_editor) -> None:  # noqa
    """Starts the position cleanup process."""
    PlayerPosition = apps.get_model("profiles", "PlayerPosition")  # noqa
    position_service = PlayerPositionService(model=PlayerPosition)
    position_service.start_position_cleanup_process()


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0146_auto_20231231_1127"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playerposition",
            options={
                "ordering": ["ordering"],
                "verbose_name": "Player Position",
                "verbose_name_plural": "Player Positions",
            },
        ),
        migrations.RemoveField(
            model_name="profiletransferrequest",
            name="position",
        ),
        migrations.AddField(
            model_name="playerposition",
            name="ordering",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="profiletransferrequest",
            name="player_position",
            field=models.ManyToManyField(
                help_text="The position that the team is requesting.",
                related_name="transfer_requests",
                to="profiles.PlayerPosition",
            ),
        ),
        migrations.RunPython(change_position_names),
    ]
