# Generated by Django 3.2 on 2024-01-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0146_alter_teamcontributor_team_history'),
        ('profiles', '0147_auto_20240102_1225'),
    ]

    operations = [
    ]
