# Generated by Django 3.2 on 2024-01-07 15:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0148_merge_20240103_1729"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiletransferrequest",
            name="league",
            field=models.CharField(
                blank=True,
                help_text="League name filled automatically from team.club.voivodeship_obj",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profiletransferrequest",
            name="voivodeship",
            field=models.CharField(
                blank=True,
                help_text="Voivodeship name filled automatically from team.club.voivodeship_obj",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profiletransferrequest",
            name="benefits",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("1", "Zwrot lub organizacja transportu"),
                        ("2", "Zwrot za buty lub rękawice"),
                        ("3", "Sprzęt treningowy"),
                        ("4", "Dobre zaplecze treningowe"),
                        ("5", "Premie za wygrane"),
                        ("6", "Fizjoterapeuta w sztabie"),
                        ("7", "Siłownia do dyspozycji"),
                        ("8", "Walka o awans"),
                        ("9", "Doświadczony trener"),
                    ],
                    help_text="Additional information about the transfer.",
                    max_length=255,
                    null=True,
                ),
                blank=True,
                help_text="Benefits defines as integers with comma. Example: 1,2",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="profiletransferstatus",
            name="benefits",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("1", "Zwrot lub organizacja transportu"),
                        ("2", "Zwrot za buty lub rękawice"),
                        ("3", "Sprzęt treningowy"),
                        ("4", "Dobre zaplecze treningowe"),
                        ("5", "Premie za wygrane"),
                        ("6", "Fizjoterapeuta w sztabie"),
                        ("7", "Siłownia do dyspozycji"),
                        ("8", "Walka o awans"),
                        ("9", "Doświadczony trener"),
                    ],
                    help_text="Additional information about the transfer.",
                    max_length=255,
                    null=True,
                ),
                blank=True,
                help_text="Benefits defines as integers with comma. Example: 1,2",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="teamcontributor",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IC", "Pierwszy trener"),
                    ("IIC", "Drugi trener"),
                    ("GKC", "Trener bramkarzy"),
                    ("FIC", "Trener motoryki"),
                    ("MEC", "Trener mentalny"),
                    ("ANC", "Analityk"),
                    ("OTC", "Inne"),
                    ("P", "Prezes"),
                    ("DSp", "Dyrektor sportowy"),
                    ("CZ", "Członek zarządu"),
                    ("DSk", "Dyrektor skautingu"),
                    ("KD", "Kierownik drużyny"),
                    ("O", "Inne"),
                ],
                help_text="Role of the contributor in the team. Role specified for club/coach profile",
                max_length=50,
                null=True,
            ),
        ),
    ]
