# Generated by Django 3.2 on 2024-01-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0148_merge_20240103_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='formation',
            field=models.CharField(blank=True, choices=[('1-3-4-3', '1-3-4-3'), ('1-5-3-2', '1-5-3-2'), ('1-4-3-1-2', '1-4-3-1-2'), ('1-4-1-4-1', '1-4-1-4-1'), ('1-4-3-3', '1-4-3-3'), ('1-4-2-3-1', '1-4-2-3-1'), ('1-4-4-2', '1-4-4-2'), ('1-5-4-1', '1-5-4-1'), ('1-4-2-4', '1-4-2-4'), ('1-5-2-3', '1-5-2-3')], help_text='This field represents the preferred formation of the coach.', max_length=15, null=True, verbose_name='Formacja'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='formation',
            field=models.CharField(blank=True, choices=[('1-3-4-3', '1-3-4-3'), ('1-5-3-2', '1-5-3-2'), ('1-4-3-1-2', '1-4-3-1-2'), ('1-4-1-4-1', '1-4-1-4-1'), ('1-4-3-3', '1-4-3-3'), ('1-4-2-3-1', '1-4-2-3-1'), ('1-4-4-2', '1-4-4-2'), ('1-5-4-1', '1-5-4-1'), ('1-4-2-4', '1-4-2-4'), ('1-5-2-3', '1-5-2-3')], max_length=15, null=True, verbose_name='Formacja'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='formation_alt',
            field=models.CharField(blank=True, choices=[('1-3-4-3', '1-3-4-3'), ('1-5-3-2', '1-5-3-2'), ('1-4-3-1-2', '1-4-3-1-2'), ('1-4-1-4-1', '1-4-1-4-1'), ('1-4-3-3', '1-4-3-3'), ('1-4-2-3-1', '1-4-2-3-1'), ('1-4-4-2', '1-4-4-2'), ('1-5-4-1', '1-5-4-1'), ('1-4-2-4', '1-4-2-4'), ('1-5-2-3', '1-5-2-3')], max_length=15, null=True, verbose_name='Alternatywna formacja'),
        ),
    ]
