# Generated by Django 3.2 on 2024-01-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0149_auto_20240107_1639'),
        ('profiles', '0150_auto_20240107_1738'),
    ]

    operations = [
    ]
