# Generated by Django 3.2.23 on 2024-01-18 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0151_merge_0149_auto_20240107_1639_0150_auto_20240107_1738"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profiletransferrequest",
            name="dial_code",
        ),
        migrations.RemoveField(
            model_name="profiletransferrequest",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="profiletransferstatus",
            name="dial_code",
        ),
        migrations.RemoveField(
            model_name="profiletransferstatus",
            name="phone_number",
        ),
    ]
