# Generated by Django 3.2.23 on 2024-01-16 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0151_merge_0149_auto_20240107_1639_0150_auto_20240107_1738"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profiletransferrequest",
            old_name="player_position",
            new_name="position",
        ),
    ]
