# Generated by Django 3.2.23 on 2024-01-18 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0152_auto_20240118_1134"),
        ("profiles", "0152_rename_player_position_profiletransferrequest_position"),
    ]

    operations = []
