# Generated by Django 3.2.23 on 2024-01-18 21:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0153_merge_20240118_1626"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profiletransferrequest",
            name="contact_email",
        ),
    ]
