# Generated by Django 3.2 on 2024-01-20 19:05

from django.db import migrations


def update_slug(apps, schema_editor) -> None:
    """
    A data migration function to update the slug fields of profile models.

    This function iterates over specified profile models and updates their slug fields.
    The update replaces the English role names in the slugs with their Polish equivalents.  # noqa 501
    """
    slug_mapping = {
        "player": "pilkarz",
        "coach": "trener",
        "club": "dzialacz-klubowy",
        "scout": "skaut",
        "guest": "kibic",
        "manager": "menadzer",
    }

    for model_name in [
        "PlayerProfile",
        "CoachProfile",
        "ClubProfile",
        "ScoutProfile",
        "GuestProfile",
        "ManagerProfile",
    ]:
        Model = apps.get_model("profiles", model_name)
        for instance in Model.objects.all():
            for eng, pol in slug_mapping.items():
                if instance.slug.startswith(eng):
                    instance.slug = instance.slug.replace(eng, pol, 1)
                    instance.save()
                    break


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0154_remove_profiletransferrequest_contact_email"),
    ]

    operations = [
        migrations.RunPython(update_slug)
    ]
