# Generated by Django 3.2.23 on 2024-01-20 22:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0154_remove_profiletransferrequest_contact_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profiletransferstatus",
            name="contact_email",
        ),
    ]
