# Generated by Django 3.2 on 2024-01-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0154_remove_profiletransferrequest_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermetrics',
            name='pm_score_state',
            field=models.CharField(choices=[('not_calculated', 'Not Calculated'), ('in_progress', 'In Progress'), ('calculated', 'Calculated')], default='not_calculated', help_text="Defines a status of the player's pm_score.", max_length=20),
        ),
    ]
