# Generated by Django 3.2 on 2024-01-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0155_auto_20240120_2014'),
        ('profiles', '0155_remove_profiletransferstatus_contact_email'),
    ]

    operations = [
    ]
