# Generated by Django 3.2 on 2024-01-25 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0155_playermetrics_pm_score_state'),
        ('profiles', '0156_merge_20240125_1805'),
    ]

    operations = [
    ]
