# Generated by Django 3.2 on 2024-05-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0157_merge_20240125_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('slug', models.CharField(editable=False, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
