# Generated by Django 3.2.21 on 2024-11-19 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0002_auto_20241119_1422'),
        ('profiles', '0158_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='premium_products',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='premium.premiumproduct'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='premium_products',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='premium.premiumproduct'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='premium_products',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='premium.premiumproduct'),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='premium_products',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='premium.premiumproduct'),
        ),
        migrations.AddField(
            model_name='otherprofile',
            name='premium_products',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='premium.premiumproduct'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='premium_products',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='premium.premiumproduct'),
        ),
        migrations.AddField(
            model_name='refereeprofile',
            name='premium_products',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='premium.premiumproduct'),
        ),
        migrations.AddField(
            model_name='scoutprofile',
            name='premium_products',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='premium.premiumproduct'),
        ),
    ]
