# Generated by Django 3.2.25 on 2024-11-26 17:24

import django.db.models.deletion
from django.db import migrations, models

from profiles.models import PROFILE_MODELS


def create_visitation(apps, schema_editor):
    Visitation = apps.get_model("profiles", "Visitation")
    for profile_model_class in PROFILE_MODELS:
        profile_model = apps.get_model("profiles", profile_model_class.__name__)
        for profile in profile_model.objects.all():
            profile.visitation = Visitation.objects.create()
            profile.save()


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0159_auto_20241119_1422"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="clubprofile",
            name="visitation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="profiles.visitation",
            ),
        ),
        migrations.AddField(
            model_name="coachprofile",
            name="visitation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="profiles.visitation",
            ),
        ),
        migrations.AddField(
            model_name="guestprofile",
            name="visitation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="profiles.visitation",
            ),
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="visitation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="profiles.visitation",
            ),
        ),
        migrations.AddField(
            model_name="otherprofile",
            name="visitation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="profiles.visitation",
            ),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="visitation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="profiles.visitation",
            ),
        ),
        migrations.AddField(
            model_name="refereeprofile",
            name="visitation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="profiles.visitation",
            ),
        ),
        migrations.AddField(
            model_name="scoutprofile",
            name="visitation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="profiles.visitation",
            ),
        ),
        migrations.RunPython(create_visitation, reverse_code=migrations.RunPython.noop),
    ]
