# Generated by Django 3.2.25 on 2024-12-03 12:55

import django.db.models.deletion
from django.db import migrations, models


def create_external_links(apps, schema_editor):
    GuestProfile = apps.get_model("profiles", "GuestProfile")
    ExternalLinks = apps.get_model("external_links", "ExternalLinks")

    for guest_profile in GuestProfile.objects.all():
        guest_profile.external_links = ExternalLinks.objects.create()
        guest_profile.save()


class Migration(migrations.Migration):
    dependencies = [
        ("external_links", "0004_alter_externallinksentity_target"),
        ("profiles", "0159_auto_20241119_1422"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestprofile",
            name="external_links",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="external_links.externallinks",
            ),
        ),
        migrations.RunPython(
            create_external_links, reverse_code=migrations.RunPython.noop
        ),
    ]
