# Generated by Django 3.2.25 on 2024-11-26 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0160_auto_20241126_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileVisitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('visited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_objects', to='profiles.visitation')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_by_me', to='profiles.visitation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
