# Generated by Django 3.2.25 on 2024-12-05 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0160_guestprofile_external_links'),
        ('profiles', '0161_profilevisitation'),
    ]

    operations = [
    ]
