# Generated by Django 3.2.25 on 2024-12-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0162_merge_20241205_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitation',
            name='_visitors_count_per_year',
            field=models.JSONField(default=dict),
        ),
    ]
