# Generated by Django 3.2.25 on 2024-12-23 19:57

from django.db import migrations, models


def update_pm_score_history_with_current_pm_score(apps, schema_editor):
    PlayerMetrics = apps.get_model("profiles", "PlayerMetrics")

    for player_metrics in PlayerMetrics.objects.filter(pm_score__gt=0):
        player_metrics.pm_score_history = {
            str(player_metrics.pm_score_updated.date()): player_metrics.pm_score,
        }
        player_metrics.save()


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0163_visitation__visitors_count_per_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="playermetrics",
            name="pm_score_history",
            field=models.JSONField(
                default=dict, verbose_name="PlayMaker Score history"
            ),
        ),
        migrations.RunPython(
            update_pm_score_history_with_current_pm_score,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
