# Generated by Django 3.2.25 on 2025-01-08 11:46

from django.db import migrations


def create_external_links(apps, schema_editor):
    ClubProfile = apps.get_model("profiles", "ClubProfile")
    ExternalLinks = apps.get_model("external_links", "ExternalLinks")

    for club_profile in ClubProfile.objects.all():
        club_profile.external_links = ExternalLinks.objects.create()
        club_profile.save()


class Migration(migrations.Migration):
    dependencies = [
        ("external_links", "0004_alter_externallinksentity_target"),
        ("profiles", "0164_playermetrics_pm_score_history"),
    ]

    operations = [
        migrations.RunPython(
            create_external_links, reverse_code=migrations.RunPython.noop
        ),
    ]
