# Generated by Django 3.2.25 on 2025-04-15 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0165_auto_20250108_1246"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerprofile",
            name="meta_updated",
        ),
        migrations.RemoveField(
            model_name="playerprofile",
            name="meta",
        ),
        migrations.CreateModel(
            name="ProfileMeta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_profile_class", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name="playermetrics",
            name="pm_score",
            field=models.IntegerField(
                blank=True,
                help_text="Tu tylko liczba całkowita, w historię możemy wrzucić zmiennoprzecinkową.",
                null=True,
                verbose_name="PlayMaker Score",
            ),
        ),
        migrations.AlterField(
            model_name="playermetrics",
            name="pm_score_history",
            field=models.JSONField(
                default=dict,
                help_text="Format daty: YYYY-MM-DD w apostrofach, wartości zmiennoprzecinkowe PMS z kropką: {'2024-11-32': 1.23, '2025-04-19': 3.21}",
                verbose_name="PlayMaker Score history",
            ),
        ),
        migrations.AddField(
            model_name="clubprofile",
            name="meta",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.profilemeta",
            ),
        ),
        migrations.AddField(
            model_name="coachprofile",
            name="meta",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.profilemeta",
            ),
        ),
        migrations.AddField(
            model_name="guestprofile",
            name="meta",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.profilemeta",
            ),
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="meta",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.profilemeta",
            ),
        ),
        migrations.AddField(
            model_name="otherprofile",
            name="meta",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.profilemeta",
            ),
        ),
        migrations.AddField(
            model_name="refereeprofile",
            name="meta",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.profilemeta",
            ),
        ),
        migrations.AddField(
            model_name="scoutprofile",
            name="meta",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.profilemeta",
            ),
        ),
    ]
