# Generated by Django 3.2.25 on 2025-02-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0165_auto_20250108_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermetrics',
            name='pm_score',
            field=models.IntegerField(blank=True, help_text='Tu tylko liczba całkowita, w historię możemy wrzucić zmiennoprzecinkową.', null=True, verbose_name='PlayMaker Score'),
        ),
        migrations.AlterField(
            model_name='playermetrics',
            name='pm_score_history',
            field=models.JSONField(default=dict, help_text="Format daty: YYYY-MM-DD w apostrofach, wartości zmiennoprzecinkowe PMS z kropką: {'2024-11-32': 1.23, '2025-04-19': 3.21}", verbose_name='PlayMaker Score history'),
        ),
    ]
