# Generated by Django 3.2.25 on 2025-04-16 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0166_auto_20250415_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='meta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profilemeta'),
        ),
    ]
