# Generated by Django 3.2.25 on 2025-04-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0166_auto_20250201_1137'),
        ('profiles', '0167_playerprofile_meta'),
    ]

    operations = [
    ]
