# Generated by Django 3.2.25 on 2025-04-20 23:32


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from profiles.models import PROFILE_MODELS


def create_meta_for_all_profiles(apps, schema_editor):
    """
    Create ProfileMeta for all existing profiles.
    """
    ProfileMeta = apps.get_model("profiles", "ProfileMeta")

    for profile_type in PROFILE_MODELS:
        Profile = apps.get_model("profiles", profile_type.__name__)
        for profile in Profile.objects.all():
            if not profile.meta:
                profile.meta = ProfileMeta.objects.create(
                    _profile_class=profile_type.__name__.lower(),
                    user=profile.user,
                )
                profile.save()


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0168_merge_0166_auto_20250201_1137_0167_playerprofile_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemeta',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(create_meta_for_all_profiles, migrations.RunPython.noop)
    ]
