# Generated by Django 3.2.25 on 2025-04-23 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0169_auto_20250421_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemeta',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
