# Generated by Django 3.2.25 on 2025-05-10 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0169_auto_20250421_0132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemeta',
            options={'verbose_name': 'Meta', 'verbose_name_plural': 'Metas'},
        ),
    ]
