# Generated by Django 3.2.25 on 2025-05-23 17:24


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("profiles", "0170_alter_profilemeta_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilevisitation",
            name="new_visitation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="new_visitation",
                to="profiles.profilemeta",
            ),
        ),
        migrations.AddField(
            model_name="profilevisitation",
            name="new_visitor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="new_visitor",
                to="profiles.profilemeta",
            ),
        ),
        migrations.RunSQL(
            """
-- PlayerProfile
UPDATE profiles_profilevisitation pv
SET new_visitor_id = pp.meta_id
FROM profiles_playerprofile pp
WHERE pv.visitor_id = pp.visitation_id;

UPDATE profiles_profilevisitation pv
SET new_visitation_id = pp.meta_id
FROM profiles_playerprofile pp
WHERE pv.visited_id = pp.visitation_id;

-- CoachProfile
UPDATE profiles_profilevisitation pv
SET new_visitor_id = cp.meta_id
FROM profiles_coachprofile cp
WHERE pv.visitor_id = cp.visitation_id;

UPDATE profiles_profilevisitation pv
SET new_visitation_id = cp.meta_id
FROM profiles_coachprofile cp
WHERE pv.visited_id = cp.visitation_id;

-- ClubProfile
UPDATE profiles_profilevisitation pv
SET new_visitor_id = clp.meta_id
FROM profiles_clubprofile clp
WHERE pv.visitor_id = clp.visitation_id;

UPDATE profiles_profilevisitation pv
SET new_visitation_id = clp.meta_id
FROM profiles_clubprofile clp
WHERE pv.visited_id = clp.visitation_id;

-- GuestProfile
UPDATE profiles_profilevisitation pv
SET new_visitor_id = gp.meta_id
FROM profiles_guestprofile gp
WHERE pv.visitor_id = gp.visitation_id;

UPDATE profiles_profilevisitation pv
SET new_visitation_id = gp.meta_id
FROM profiles_guestprofile gp
WHERE pv.visited_id = gp.visitation_id;

-- ManagerProfile
UPDATE profiles_profilevisitation pv
SET new_visitor_id = mp.meta_id
FROM profiles_managerprofile mp
WHERE pv.visitor_id = mp.visitation_id;

UPDATE profiles_profilevisitation pv
SET new_visitation_id = mp.meta_id
FROM profiles_managerprofile mp
WHERE pv.visited_id = mp.visitation_id;

-- ScoutProfile
UPDATE profiles_profilevisitation pv
SET new_visitor_id = sp.meta_id
FROM profiles_scoutprofile sp
WHERE pv.visitor_id = sp.visitation_id;

UPDATE profiles_profilevisitation pv
SET new_visitation_id = sp.meta_id
FROM profiles_scoutprofile sp
WHERE pv.visited_id = sp.visitation_id;

-- RefereeProfile
UPDATE profiles_profilevisitation pv
SET new_visitor_id = rp.meta_id
FROM profiles_refereeprofile rp
WHERE pv.visitor_id = rp.visitation_id;

UPDATE profiles_profilevisitation pv
SET new_visitation_id = rp.meta_id
FROM profiles_refereeprofile rp
WHERE pv.visited_id = rp.visitation_id;

-- OtherProfile
UPDATE profiles_profilevisitation pv
SET new_visitor_id = op.meta_id
FROM profiles_otherprofile op
WHERE pv.visitor_id = op.visitation_id;

UPDATE profiles_profilevisitation pv
SET new_visitation_id = op.meta_id
FROM profiles_otherprofile op
WHERE pv.visited_id = op.visitation_id;""",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
