# Generated by Django 3.2.25 on 2025-05-23 18:48

import django.db.models.deletion
from django.db import migrations, models


def remove_empty_visitations(apps, schema_editor):
    ProfileVisitation = apps.get_model("profiles", "ProfileVisitation")

    ProfileVisitation.objects.filter(new_visitation__isnull=True).delete()
    ProfileVisitation.objects.filter(new_visitor__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0171_auto_20250523_1924"),
    ]

    operations = [
        migrations.RunPython(
            remove_empty_visitations, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="profilevisitation",
            name="visited",
        ),
        migrations.RemoveField(
            model_name="profilevisitation",
            name="visitor",
        ),
        migrations.AlterField(
            model_name="profilevisitation",
            name="new_visitation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visited_objects",
                to="profiles.profilemeta",
            ),
        ),
        migrations.AlterField(
            model_name="profilevisitation",
            name="new_visitor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visited_by_me",
                to="profiles.profilemeta",
            ),
        ),
    ]
