# Generated by Django 3.2.25 on 2025-05-23 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0172_auto_20250523_2048"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profilevisitation",
            old_name="new_visitation",
            new_name="visited",
        ),
        migrations.RenameField(
            model_name="profilevisitation",
            old_name="new_visitor",
            new_name="visitor",
        ),
    ]
