# Generated by Django 3.2.25 on 2025-06-08 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0097_club_visible"),
        ("profiles", "0173_auto_20250523_2048"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiletransferrequest",
            name="position",
            field=models.ManyToManyField(
                help_text="The position that the team is requesting.",
                related_name="transfer_requests_old",
                to="profiles.PlayerPosition",
            ),
        ),
        migrations.AlterField(
            model_name="profiletransferrequest",
            name="requesting_team",
            field=models.ForeignKey(
                help_text="The team that is requesting the transfer.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfer_requests_old",
                to="profiles.teamcontributor",
            ),
        ),
        migrations.AlterField(
            model_name="profiletransferstatus",
            name="league",
            field=models.ManyToManyField(
                related_name="transfer_status_old", to="clubs.League"
            ),
        ),
    ]
