# Generated by Django 3.2.25 on 2025-07-07 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0173_auto_20250523_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubprofile',
            name='data_fulfill_status',
        ),
        migrations.RemoveField(
            model_name='clubprofile',
            name='data_mapper_id',
        ),
        migrations.RemoveField(
            model_name='clubprofile',
            name='verification',
        ),
        migrations.RemoveField(
            model_name='coachprofile',
            name='data_fulfill_status',
        ),
        migrations.RemoveField(
            model_name='coachprofile',
            name='data_mapper_id',
        ),
        migrations.RemoveField(
            model_name='coachprofile',
            name='verification',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='data_fulfill_status',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='data_mapper_id',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='verification',
        ),
        migrations.RemoveField(
            model_name='managerprofile',
            name='data_fulfill_status',
        ),
        migrations.RemoveField(
            model_name='managerprofile',
            name='data_mapper_id',
        ),
        migrations.RemoveField(
            model_name='managerprofile',
            name='verification',
        ),
        migrations.RemoveField(
            model_name='otherprofile',
            name='data_fulfill_status',
        ),
        migrations.RemoveField(
            model_name='otherprofile',
            name='data_mapper_id',
        ),
        migrations.RemoveField(
            model_name='otherprofile',
            name='verification',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='data_fulfill_status',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='data_mapper_id',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='verification',
        ),
        migrations.RemoveField(
            model_name='refereeprofile',
            name='data_fulfill_status',
        ),
        migrations.RemoveField(
            model_name='refereeprofile',
            name='data_mapper_id',
        ),
        migrations.RemoveField(
            model_name='refereeprofile',
            name='verification',
        ),
        migrations.RemoveField(
            model_name='scoutprofile',
            name='data_fulfill_status',
        ),
        migrations.RemoveField(
            model_name='scoutprofile',
            name='data_mapper_id',
        ),
        migrations.RemoveField(
            model_name='scoutprofile',
            name='verification',
        ),
        migrations.DeleteModel(
            name='ProfileVerificationStatus',
        ),
    ]
