# Generated by Django 3.2.25 on 2025-07-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0173_auto_20250523_2048'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='playerprofile',
            index=models.Index(fields=['user', 'team_object'], name='profiles_pl_user_id_49a5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='playerprofile',
            index=models.Index(fields=['voivodeship_obj', 'team_object'], name='profiles_pl_voivode_9bbc4f_idx'),
        ),
        migrations.AddIndex(
            model_name='playerprofile',
            index=models.Index(fields=['uuid'], name='profiles_pl_uuid_12b538_idx'),
        ),
    ]
