# Generated by Django 3.2.25 on 2025-06-08 01:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0174_auto_20250608_0316"),
        ("transfers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profiletransferstatus",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="profiletransferstatus",
            name="league",
        ),
        migrations.DeleteModel(
            name="ProfileTransferRequest",
        ),
        migrations.DeleteModel(
            name="ProfileTransferStatus",
        ),
    ]
