# Generated by Django 3.2.25 on 2025-07-09 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0174_auto_20250708_0003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoleChangeRequest',
        ),
    ]
