# Generated by Django 3.2.25 on 2025-06-19 21:18

from django.db import migrations, models


def save_data(apps, schema_editor):
    models = {
        apps.get_model("profiles", "PlayerProfile"),
        apps.get_model("profiles", "CoachProfile"),
        apps.get_model("profiles", "ClubProfile"),
        apps.get_model("profiles", "ManagerProfile"),
        apps.get_model("profiles", "ScoutProfile"),
        apps.get_model("profiles", "GuestProfile"),
    }
    for model in models:
        for profile in model.objects.all():
            meta = profile.meta
            meta._slug = profile.slug
            meta._uuid = profile.uuid
            meta.save()


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0175_auto_20250608_0350"),
    ]
    operations = [
        migrations.AddField(
            model_name="profilemeta",
            name="_slug",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profilemeta",
            name="_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(save_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="profilemeta",
            name="_slug",
            field=models.CharField(
                blank=False, max_length=255, null=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="profilemeta",
            name="_uuid",
            field=models.UUIDField(unique=True, blank=False, null=False),
        ),
        migrations.RemoveField(
            model_name="playerprofile",
            name="voivodeship",
        ),
        migrations.RemoveField(
            model_name="playerprofile",
            name="transfer_status",
        ),
    ]
