# Generated by Django 3.2.25 on 2025-07-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0175_delete_rolechangerequest'),
        ('profiles', '0176_auto_20250619_2318'),
    ]

    operations = [
    ]
