# Generated by Django 3.2.25 on 2025-10-29 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0178_alter_profilemeta_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemeta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to=settings.AUTH_USER_MODEL),
        ),
    ]
