# Generated by Django 3.1 on 2020-09-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initial_setup',
            field=models.BooleanField(default=None, null=True, verbose_name='Skip full setup'),
        ),
        migrations.AlterField(
            model_name='user',
            name='declared_club',
            field=models.CharField(help_text='Users declaration in which club he plays.', max_length=355, verbose_name='declared club'),
        ),
        migrations.AlterField(
            model_name='user',
            name='declared_role',
            field=models.CharField(blank=True, choices=[('P', 'Piłkarz'), ('T', 'Trener')], help_text='Users declaration in which role he has', max_length=355, null=True, verbose_name='declared club'),
        ),
    ]
