# Generated by Django 3.2 on 2023-07-05 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from cities_light.models import City
from unidecode import unidecode
from typing import Optional, Union, Any
from app.utils.cities import CUSTOM_CITY_MAPPING
from profiles.models import PlayerProfile, ScoutProfile, CoachProfile
from users.models import User, UserPreferences


def get_address_from_profile(profile: Optional[models.Model]) -> Optional[str]:
    """
    Get the address from a profile object.
    """
    address = getattr(profile, 'address', None)
    return address.formatted if address else None


def get_localization_from_address(address: Optional[str]) -> Optional[int]:
    """
    Get the city ID from an address by matching the City object based on the address field in the profile.
    """
    if address is not None:
        for key, value in CUSTOM_CITY_MAPPING.items():
            if address.lower() == value.lower():
                address = key
        city = City.objects.filter(name_ascii__icontains=unidecode(address)).first()
        return city.id if city else None
    return None


def update_user_preferences_from_profile(
        profile: Union[PlayerProfile, ScoutProfile, CoachProfile],
        user_preferences_model: UserPreferences,
        user: User
) -> None:
    """
    Update the localization field in the User Preferences model based on the address field of the provided profile.
    """
    localization = get_address_from_profile(profile)
    city_id = get_localization_from_address(localization) if localization else None
    user_preferences, created = user_preferences_model.objects.get_or_create(user=user)
    user_preferences.localization_id = city_id
    user_preferences.save()


def populate_localization(apps: Any, schema_editor: Any) -> None:
    """
    Populate the localization field of user objects based on profile addresses.
    """
    User = apps.get_model('users', 'User')
    PlayerProfile = apps.get_model('profiles', 'PlayerProfile')
    CoachProfile = apps.get_model('profiles', 'CoachProfile')
    ScoutProfile = apps.get_model('profiles', 'ScoutProfile')
    UserPreferences = apps.get_model('users', 'UserPreferences')

    users = User.objects.all()

    for user in users:
        player_profile = PlayerProfile.objects.filter(user=user).first()
        coach_profile = CoachProfile.objects.filter(user=user).first()
        scout_profile = ScoutProfile.objects.filter(user=user).first()

        if player_profile:
            update_user_preferences_from_profile(player_profile, UserPreferences, user)

        if coach_profile:
            update_user_preferences_from_profile(coach_profile, UserPreferences, user)

        if scout_profile:
            update_user_preferences_from_profile(scout_profile, UserPreferences, user)


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('profiles', '0087_coachlicence_licencetype'),
        ('users', '0002_alter_user_declared_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship', models.CharField(blank=True, help_text="User's citizenship (country of citizenship)", max_length=50, null=True)),
                ('spoken_languages', models.ManyToManyField(blank=True, help_text="User's known languages (languages spoken by the user)", to='profiles.Language')),
                ('localization', models.ForeignKey(blank=True, help_text="User's localization (city and voivodeship)", null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city', verbose_name='Localization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.RunPython(populate_localization)
    ]
