# Generated by Django 3.1 on 2020-10-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200901_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='initial_setup',
            field=models.BooleanField(default=None, help_text='Flag ', null=True, verbose_name='Skip full setup'),
        ),
    ]
