# Generated by Django 3.2 on 2023-07-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_userpreferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Mężczyzna"), ("K", "Kobieta")],
                help_text="User's gender (represents the gender identity of the user)",
                max_length=1,
                null=True,
                verbose_name="Gender",
            ),
        ),
    ]
