# Generated by Django 3.1 on 2020-10-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201017_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='A', max_length=255, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='declared_club',
            field=models.CharField(blank=True, help_text='Users declaration in which club he plays.', max_length=355, null=True, verbose_name='declared club'),
        ),
    ]
