# Generated by Django 3.2 on 2023-07-13 22:13

from typing import Any
from django.db import migrations, models


def migrate_birth_dates(apps: Any, schema_editor: Any) -> None:
    """
    Migrates the birth_date from PlayerProfile and CoachProfile to a new field in UserPreferences.

    This migration transfers the birth_date information from the PlayerProfile and CoachProfile
    models to a new field in the UserPreferences model for each user. It ensures that the birth date
    information is migrated and stored correctly in the UserPreferences model.
    """

    UserPreferences = apps.get_model("users", "UserPreferences")
    PlayerProfile = apps.get_model("profiles", "PlayerProfile")
    CoachProfile = apps.get_model("profiles", "CoachProfile")

    for player_profile in PlayerProfile.objects.all():
        user_preferences = UserPreferences.objects.get(user=player_profile.user)
        user_preferences.birth_date = player_profile.birth_date
        user_preferences.save()

    for coach_profile in CoachProfile.objects.all():
        user_preferences = UserPreferences.objects.get(user=coach_profile.user)
        user_preferences.birth_date = coach_profile.birth_date
        user_preferences.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_userpreferences_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="birth_date",
            field=models.DateField(
                blank=True,
                help_text="User's date of birth",
                null=True,
                verbose_name="Data urodzenia",
            ),
        ),
        migrations.RunPython(migrate_birth_dates),
    ]
