# Generated by Django 3.1 on 2020-10-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='declared_role',
            field=models.CharField(blank=True, choices=[('P', 'Piłkarz'), ('T', 'Trener')], help_text='Users declaration in which role he has', max_length=355, null=True, verbose_name='declared role'),
        ),
    ]
