# Generated by Django 3.2 on 2023-08-22 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230808_2159'),
        ('users', '0007_user_last_activity'),
    ]

    operations = [
    ]
