# Generated by Django 3.1 on 2020-10-18 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201018_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False, help_text='Defines if admin approved change')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(help_text='Admin who verified.', on_delete=django.db.models.deletion.CASCADE, related_name='approver', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='User who shoudl be verified.', on_delete=django.db.models.deletion.CASCADE, related_name='userforverification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
