# Generated by Django 3.1 on 2020-10-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='initial_setup',
        ),
        migrations.AddField(
            model_name='user',
            name='finish_account_initial_setup',
            field=models.BooleanField(blank=True, null=True, verbose_name='Skip full setup'),
        ),
    ]
