# Generated by Django 3.2 on 2023-09-18 00:19

from django.db import migrations


def migrate_user_preferences(apps, schema_editor) -> None:
    """
    Migrate user preferences based on their associated profiles.

    For each user profile that has a country field (namely PlayerProfile,
    CoachProfile, and ScoutProfile), this migration will:

    1. Fetch the corresponding UserPreferences object linked with the profile's user.
    2. Update the 'citizenship' attribute of UserPreferences based on the 'country'
       attribute of the user's profile.
    3. Attempt to determine and set a default spoken language for the user
       based on the country's language code. If no corresponding language entry
       is found, it silently ignores the missing entry.
    4. Save the updated UserPreferences object back to the database.
    """
    UserPreferences = apps.get_model("users", "UserPreferences")
    PlayerProfile = apps.get_model("profiles", "PlayerProfile")
    CoachProfile = apps.get_model("profiles", "CoachProfile")
    ScoutProfile = apps.get_model("profiles", "ScoutProfile")
    Language = apps.get_model("profiles", "Language")
    PROFILE_MODELS_WITH_COUNTRY = [PlayerProfile, CoachProfile, ScoutProfile]

    # Loop through each profile model
    for profile_model in PROFILE_MODELS_WITH_COUNTRY:
        for profile in profile_model.objects.all():
            # If country in the profile is None, skip this profile
            if profile.country.code is None:
                continue
            # Get user preferences associated with the profile's user
            user_prefs = UserPreferences.objects.get(user_id=profile.user.id)

            # Set the citizenship based on profile's country
            user_prefs.citizenship = [profile.country.code]

            # Set the default language based on country's language code
            try:
                language_code = profile.country.code.lower()
                if (
                    not language_code
                ):  # Ensure the language code is not an empty string or None
                    continue
                language_obj = Language.objects.get(code=language_code)
                user_prefs.spoken_languages.add(language_obj)
            except Language.DoesNotExist:
                # Handle cases where there's no language with that code
                pass

            user_prefs.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_userpreferences_citizenship"),
    ]

    operations = [
        migrations.RunPython(migrate_user_preferences),
    ]
