# Generated by Django 3.2.21 on 2023-10-27 12:02

from django.db import migrations
from django.db.migrations.state import StateApps as _StateApps


def purge_declared_role(apps: _StateApps, *_) -> None:
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        user.declared_role = None
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_auto_20230918_0219"),
        ("profiles", "0120_auto_20231027_1630")
    ]

    operations = [
        migrations.RunPython(purge_declared_role),
    ]
