# Generated by Django 3.1.2 on 2020-11-02 23:18

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201018_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=django_fsm.FSMField(choices=[('New', 'New'), ('Email Verified', 'Email Verified'), ('Account Verified', 'Account Verified'), ('Migrated', 'Migrated'), ('Activated', 'Activated'), ('Locked', 'Locked'), ('Banned', 'Banned')], default='New', max_length=50),
        ),
    ]
