# Generated by Django 3.1.2 on 2020-11-06 18:39

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201105_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=django_fsm.FSMField(choices=[('New', 'New'), ('Authentication Verified', 'Authentication Verified'), ('Account Verified', 'Account Verified'), ('Migrated', 'Migrated'), ('Activated', 'Activated'), ('Locked', 'Locked'), ('Banned', 'Banned')], default='New', max_length=50),
        ),
    ]
