# Generated by Django 3.2.23 on 2024-01-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_declared_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='historical_role',
            field=models.CharField(blank=True, choices=[('P', 'Piłkarz'), ('T', 'Trener'), ('C', 'Działacz klubu'), ('M', 'Menadżer'), ('S', 'Skaut'), ('G', 'Kibic'), ('O', 'Inne'), ('A', 'Sędzia')], help_text='User role declaration from previous app version.', max_length=355, null=True, verbose_name='Deklaracja historycznej roli'),
        ),
    ]
