# Generated by Django 3.2.23 on 2024-01-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_user_declared_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="dial_code",
            field=models.IntegerField(
                blank=True,
                help_text="Country dial code for the phone number.",
                null=True,
                verbose_name="Dial Code",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number for the transfer.",
                max_length=15,
                null=True,
            ),
        ),
    ]
