# Generated by Django 3.1.2 on 2020-11-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201106_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='declared_role',
            field=models.CharField(blank=True, choices=[('P', 'Piłkarz'), ('T', 'Trener'), ('G', 'Gość'), ('C', 'Klub')], help_text='Users declaration in which role he has. It is main paramter.', max_length=355, null=True, verbose_name='declared role'),
        ),
    ]
