# Generated by Django 3.2.23 on 2024-01-18 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_auto_20240118_1134"),
        ("users", "0013_user_historical_role"),
    ]

    operations = []
