# Generated by Django 3.2.23 on 2024-01-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_merge_20240118_1626"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Contact email address for the transfer.",
                max_length=254,
                null=True,
                verbose_name="Contact Email",
            ),
        ),
    ]
