# Generated by Django 3.2 on 2024-01-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_is_email_verified'),
        ('users', '0015_userpreferences_contact_email'),
    ]

    operations = [
    ]
