# Generated by Django 3.2 on 2024-01-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_merge_20240122_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_status',
            field=models.CharField(choices=[('Niewyświetlany', 'Not Shown'), ('W trakcie analizy', 'Under Review'), ('Zweryfikowany', 'Verified')], default='Zweryfikowany', help_text='Status for managing visibility in databases', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text="Indicates whether the user's email address has been verified."),
        ),
    ]
