# Generated by Django 3.2.25 on 2025-02-01 10:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_ref_objects_for_users(apps, schema_editor):
    User = apps.get_model("users", "User")
    Ref = apps.get_model("users", "Ref")

    for user in User.objects.all():
        Ref.objects.get_or_create(user=user)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_auto_20240128_2034"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ref",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserRef",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ref_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="users.ref", verbose_name='Referred by'
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            create_ref_objects_for_users, reverse_code=migrations.RunPython.noop
        ),
    ]
