# Generated by Django 3.2.25 on 2025-02-26 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_ref_userref'),
    ]

    operations = [
        migrations.AddField(
            model_name='ref',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AddField(
            model_name='ref',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Krótki tytuł'),
        ),
        migrations.AlterField(
            model_name='ref',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
