# Generated by Django 3.2.25 on 2025-02-26 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20250226_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ref',
            options={'verbose_name': 'Afiliacja', 'verbose_name_plural': 'Afiliacje'},
        ),
        migrations.AlterModelOptions(
            name='userref',
            options={'verbose_name': 'Zaproszenie afiliacyjne', 'verbose_name_plural': 'Zaproszenia afiliacyjne'},
        ),
    ]
