# Generated by Django 3.2.21 on 2023-09-23 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("callback", models.URLField(blank=True, null=True)),
                ("seen", models.BooleanField(default=False)),
                ("seen_date", models.DateTimeField(blank=True, default=None)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(
                fields=["user", "seen"], name="events_noti_user_id_256fdc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificationevent",
            unique_together={("user", "created_at", "message")},
        ),
    ]
