# Generated by Django 3.2.21 on 2023-09-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationevent",
            name="seen_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
