# Generated by Django 3.2.23 on 2023-11-15 23:37

from django.db import migrations, models

from mailing.default_templates import NEW_ACCOUNT_EMAIL_BODY, PASSWORD_CHANGE_EMAIL_BODY
from mailing.models import EmailTemplate as _EmailTemplate


def create_initial_email_templates(apps, *_) -> None:
    """Create initial email templates for new user and password change."""
    EmailTemplate = apps.get_model("mailing", "EmailTemplate")

    EmailTemplate.objects.create(
        subject="Witaj na PlayMaker.pro. Potwierdź rejestrację konta.",
        body=NEW_ACCOUNT_EMAIL_BODY,
        email_type=_EmailTemplate.EmailType.NEW_USER,
    )
    EmailTemplate.objects.create(
        subject="Zmiana hasła do Twojego konta.",
        body=PASSWORD_CHANGE_EMAIL_BODY,
        email_type=_EmailTemplate.EmailType.PASSWORD_CHANGE,
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "body",
                    models.TextField(
                        help_text="Type '#male_form|female_form#' - to mark something that should be determined by recipient gender (e.g. #Otrzymałeś|Otrzymałaś#). #url# as placeholder for some url."
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("NEW_USER", "NEW_USER"),
                            ("PASSWORD_CHANGE", "PASSWORD_CHANGE"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=True,
                        verbose_name="Is default email template for selected type?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email template",
                "verbose_name_plural": "Email templates",
                "unique_together": {("email_type", "is_default")},
            },
        ),
        migrations.RunPython(create_initial_email_templates),
    ]
