# Generated by Django 3.2.23 on 2023-11-27 22:59

from django.db import migrations, models

from mailing.default_templates import INQUIRY_LIMIT_REACHED
from mailing.models import EmailTemplate as _EmailTemplate


def _create_email_template_for_reaching_inquiry_limit(apps, schema_editor):
    """Create new type of InquiryLogMessage - LIMIT_REACHED."""
    EmailTemplate = apps.get_model("mailing", "EmailTemplate")

    EmailTemplate.objects.create(
        email_type=_EmailTemplate.EmailType.INQUIRY_LIMIT,
        subject="Rozbuduj swoje transferowe możliwości – Rozszerz limit zapytań!",
        body=INQUIRY_LIMIT_REACHED,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("NEW_USER", "NEW_USER"),
                    ("PASSWORD_CHANGE", "PASSWORD_CHANGE"),
                    ("INQUIRY_LIMIT", "INQUIRY_LIMIT"),
                ],
                max_length=255,
            ),
        ),
        migrations.RunPython(
            _create_email_template_for_reaching_inquiry_limit,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
