# Generated by Django 3.2.23 on 2023-12-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_emailtemplate_email_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('email_type', models.CharField(max_length=255)),
            ],
        ),
    ]
