# Generated by Django 3.2.23 on 2024-02-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_useremailoutbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='email_type',
            field=models.CharField(choices=[('NEW_USER', 'NEW_USER'), ('PASSWORD_CHANGE', 'PASSWORD_CHANGE'), ('INQUIRY_LIMIT', 'INQUIRY_LIMIT'), ('SYSTEM', 'SYSTEM')], max_length=255),
        ),
    ]
