# Generated by Django 3.2.25 on 2025-01-10 15:12

from django.db import migrations, models

from mailing.default_templates import PREMIUM_PROFILE_EXPIRED


def create_template_for_premium_expired(apps, schema_editor):
    EmailTemplate = apps.get_model("mailing", "EmailTemplate")

    EmailTemplate.objects.get_or_create(
        subject="⚠️ Twoje Premium wygasło – odnów je teraz!",
        body=PREMIUM_PROFILE_EXPIRED,
        email_type="PREMIUM_EXPIRED",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0004_alter_emailtemplate_email_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("NEW_USER", "NEW_USER"),
                    ("PASSWORD_CHANGE", "PASSWORD_CHANGE"),
                    ("INQUIRY_LIMIT", "INQUIRY_LIMIT"),
                    ("SYSTEM", "SYSTEM"),
                    ("PREMIUM_EXPIRED", "PREMIUM_EXPIRED"),
                ],
                max_length=255,
            ),
        ),
        migrations.RunPython(
            create_template_for_premium_expired, reverse_code=migrations.RunPython.noop
        ),
    ]
