# Generated by Django 3.2.25 on 2025-07-05 17:38

from django.db import migrations, models

# def populate_email_html_body(apps, schema_editor) -> None:
#     """
#     Populate the `html_body` field for all EmailTemplate instances by rendering their corresponding HTML templates.
#     """
#     EmailTemplate = apps.get_model('mailing', 'EmailTemplate')

#     with transaction.atomic():
#         for email in EmailTemplate.objects.all():
#             try:
#                 template_path = f"mailing/mails/{email.email_type}.html"
#                 rendered_html = render_to_string(template_path)
#                 email.html_body = rendered_html
#                 email.save(update_fields=["html_body"])
#             except Exception as e:
#                 raise Exception(f"Failed to render template for email {email.pk}: {e}")


# def clear_email_html_body(apps, schema_editor) -> None:
#     """Clear the `html_body` field for all EmailTemplate instances by setting it to None."""
#     EmailTemplate = apps.get_model('mailing', 'EmailTemplate')
#     EmailTemplate.objects.all().update(html_body=None)


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0005_auto_20250110_1612"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="html_body",
            field=models.TextField(
                blank=True,
                null=True,
                help_text="Rendered HTML version of the email template",
            ),
        ),
        # migrations.RunPython(populate_email_html_body, reverse_code=clear_email_html_body),
    ]
