# Generated by Django 3.2.25 on 2025-07-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_auto_20250110_1612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
