# Generated by Django 3.2.25 on 2025-07-26 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_delete_emailtemplate'),
        ('mailing', '0006_emailtemplate_html_body'),
    ]

    operations = [
    ]
