# Generated by Django 3.2.25 on 2025-08-02 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_merge_20250726_0646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEmailOutbox',
        ),
    ]
