# Generated by Django 3.2.25 on 2025-08-19 00:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import mailing


def create_mailing_for_existing_users(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Mailing = apps.get_model("mailing", "Mailing")
    for user in User.objects.all():
        Mailing.objects.get_or_create(user=user)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mailing", "0008_delete_useremailoutbox"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MailingPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("operation_id", models.UUIDField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mail_template",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                mailing.schemas.EmailTemplateFileNames["INQUIRY_LIMIT"],
                                mailing.schemas.EmailTemplateFileNames["INQUIRY_LIMIT"],
                            ),
                            (
                                mailing.schemas.EmailTemplateFileNames["NEW_USER"],
                                mailing.schemas.EmailTemplateFileNames["NEW_USER"],
                            ),
                            (
                                mailing.schemas.EmailTemplateFileNames[
                                    "PASSWORD_CHANGE"
                                ],
                                mailing.schemas.EmailTemplateFileNames[
                                    "PASSWORD_CHANGE"
                                ],
                            ),
                            (
                                mailing.schemas.EmailTemplateFileNames[
                                    "PREMIUM_EXPIRED"
                                ],
                                mailing.schemas.EmailTemplateFileNames[
                                    "PREMIUM_EXPIRED"
                                ],
                            ),
                            (
                                mailing.schemas.EmailTemplateFileNames[
                                    "REFERRAL_REWARD_REFERRED"
                                ],
                                mailing.schemas.EmailTemplateFileNames[
                                    "REFERRAL_REWARD_REFERRED"
                                ],
                            ),
                            (
                                mailing.schemas.EmailTemplateFileNames[
                                    "REFERRAL_REWARD_REFERRER_1"
                                ],
                                mailing.schemas.EmailTemplateFileNames[
                                    "REFERRAL_REWARD_REFERRER_1"
                                ],
                            ),
                            (
                                mailing.schemas.EmailTemplateFileNames[
                                    "REFERRAL_REWARD_REFERRER_3"
                                ],
                                mailing.schemas.EmailTemplateFileNames[
                                    "REFERRAL_REWARD_REFERRER_3"
                                ],
                            ),
                            (
                                mailing.schemas.EmailTemplateFileNames[
                                    "REFERRAL_REWARD_REFERRER_5"
                                ],
                                mailing.schemas.EmailTemplateFileNames[
                                    "REFERRAL_REWARD_REFERRER_5"
                                ],
                            ),
                            (
                                mailing.schemas.EmailTemplateFileNames[
                                    "REFERRAL_REWARD_REFERRER_15"
                                ],
                                mailing.schemas.EmailTemplateFileNames[
                                    "REFERRAL_REWARD_REFERRER_15"
                                ],
                            ),
                            (
                                mailing.schemas.EmailTemplateFileNames[
                                    "ACCEPTED_INQUIRY"
                                ],
                                mailing.schemas.EmailTemplateFileNames[
                                    "ACCEPTED_INQUIRY"
                                ],
                            ),
                            (
                                mailing.schemas.EmailTemplateFileNames[
                                    "REJECTED_INQUIRY"
                                ],
                                mailing.schemas.EmailTemplateFileNames[
                                    "REJECTED_INQUIRY"
                                ],
                            ),
                            (
                                mailing.schemas.EmailTemplateFileNames["NEW_INQUIRY"],
                                mailing.schemas.EmailTemplateFileNames["NEW_INQUIRY"],
                            ),
                            (
                                mailing.schemas.EmailTemplateFileNames[
                                    "OUTDATED_INQUIRY"
                                ],
                                mailing.schemas.EmailTemplateFileNames[
                                    "OUTDATED_INQUIRY"
                                ],
                            ),
                            (
                                mailing.schemas.EmailTemplateFileNames[
                                    "OUTDATED_REMINDER"
                                ],
                                mailing.schemas.EmailTemplateFileNames[
                                    "OUTDATED_REMINDER"
                                ],
                            ),
                            (
                                mailing.schemas.EmailTemplateFileNames["SYSTEM_ERROR"],
                                mailing.schemas.EmailTemplateFileNames["SYSTEM_ERROR"],
                            ),
                            (
                                mailing.schemas.EmailTemplateFileNames["TEST"],
                                mailing.schemas.EmailTemplateFileNames["TEST"],
                            ),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SENT", "SENT"),
                            ("FAILED", "FAILED"),
                            ("PENDING", "PENDING"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailbox",
                        to="mailing.mailing",
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            create_mailing_for_existing_users, reverse_code=migrations.RunPython.noop
        ),
    ]
