# Generated by Django 3.2.25 on 2025-09-25 21:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


def create_initial_preferences(apps, schema_editor):
    User = apps.get_model("users", "User")
    MailingPreferences = apps.get_model("mailing", "MailingPreferences")
    Mailing = apps.get_model("mailing", "Mailing")

    for user in User.objects.all():
        if not (mailing := user.mailing):
            mailing = Mailing.objects.create(user=user)

        if not mailing.preferences:
            mailing.preferences = MailingPreferences.objects.create()
            mailing.save()


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0010_alter_maillog_mail_template"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailingpreferences",
            name="id",
        ),
        migrations.AddField(
            model_name="mailingpreferences",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="preferences",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mailing.mailingpreferences",
            ),
        ),
        migrations.RunPython(
            create_initial_preferences, reverse_code=migrations.RunPython.noop
        ),
        migrations.AddField(
            model_name="mailingpreferences",
            name="marketing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="mailingpreferences",
            name="system",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="preferences",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                blank=False,
                null=False,
                to="mailing.mailingpreferences",
            ),
        ),
    ]
