# Generated by Django 3.2.25 on 2025-10-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0012_alter_maillog_mail_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maillog',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='maillog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
