PLAYER_SHORT, PLAYER_FULL = 'P', 'Piłkarz'
COACH_SHORT, COACH_FULL = 'T', 'Trener'
CLUB_SHORT, CLUB_FULL = 'C', 'Klub / Szkółka piłkarska'
MANAGER_SHORT, MANAGER_FULL = 'M', 'Agent piłkarski'
SCOUT_SHORT, SCOUT_FULL = 'S', 'Skaut'
PARENT_SHORT, PARENT_FULL = 'R', 'Rodzic małego piłkarza'
GUEST_SHORT, GUEST_FULL = 'G', 'Kibic'


PROFILE_TYPE_PLAYER = 'player'
PROFILE_TYPE_COACH = 'coach'
PROFILE_TYPE_CLUB = 'club'
PROFILE_TYPE_PARENT = 'parent'
PROFILE_TYPE_GUEST = 'guest'
PROFILE_TYPE_SCOUT = 'scout'
PROFILE_TYPE_MANAGER = 'manager'

PROFILE_TYPE_SHORT_MAP = {
        PROFILE_TYPE_PLAYER: PLAYER_SHORT,
        PROFILE_TYPE_COACH: COACH_SHORT,
        PROFILE_TYPE_CLUB: CLUB_SHORT,
        PROFILE_TYPE_PARENT: PARENT_SHORT,
        PROFILE_TYPE_GUEST: GUEST_SHORT,
        PROFILE_TYPE_SCOUT: SCOUT_SHORT,
        PROFILE_TYPE_MANAGER: MANAGER_SHORT,
}

ACCOUNT_ROLES = (
        (PLAYER_SHORT, PLAYER_FULL),
        (COACH_SHORT, COACH_FULL),
        (CLUB_SHORT, CLUB_FULL),
        (MANAGER_SHORT, MANAGER_FULL),
        (SCOUT_SHORT, SCOUT_FULL),
        (PARENT_SHORT, PARENT_FULL),
        (GUEST_SHORT, GUEST_FULL),
)
