PLAYER_SHORT, PLAYER_FULL = "P", "Piłkarz"
COACH_SHORT, COACH_FULL = "T", "Trener"
CLUB_SHORT, CLUB_FULL = "C", "Działacz klubu"
MANAGER_SHORT, MANAGER_FULL = "M", "Menadżer"
SCOUT_SHORT, SCOUT_FULL = "S", "Skaut"
PARENT_SHORT, PARENT_FULL = "R", "Rodzic małego piłkarza"
GUEST_SHORT, GUEST_FULL = "G", "Kibic"
OTHER_SHORT, OTHER_FULL = "O", "Inne"
REFEREE_SHORT, REFEREE_FULL = "A", "Sędzia"


PROFILE_TYPE_PLAYER = "player"
PROFILE_TYPE_COACH = "coach"
PROFILE_TYPE_CLUB = "club"
PROFILE_TYPE_PARENT = "parent"
PROFILE_TYPE_GUEST = "guest"
PROFILE_TYPE_SCOUT = "scout"
PROFILE_TYPE_MANAGER = "manager"
PROFILE_TYPE_OTHER = "other"
PROFILE_TYPE_REFEREE = "referee"


PROFILE_TYPE_SHORT_MAP = {
    PROFILE_TYPE_PLAYER: PLAYER_SHORT,
    PROFILE_TYPE_COACH: COACH_SHORT,
    PROFILE_TYPE_CLUB: CLUB_SHORT,
    PROFILE_TYPE_PARENT: PARENT_SHORT,
    PROFILE_TYPE_GUEST: GUEST_SHORT,
    PROFILE_TYPE_SCOUT: SCOUT_SHORT,
    PROFILE_TYPE_MANAGER: MANAGER_SHORT,
    PROFILE_TYPE_OTHER: OTHER_SHORT,
    PROFILE_TYPE_REFEREE: REFEREE_SHORT,
}

ACCOUNT_ROLES = (
    (PLAYER_SHORT, PLAYER_FULL),
    (COACH_SHORT, COACH_FULL),
    (CLUB_SHORT, CLUB_FULL),
    (MANAGER_SHORT, MANAGER_FULL),
    (SCOUT_SHORT, SCOUT_FULL),
    (PARENT_SHORT, PARENT_FULL),
    (GUEST_SHORT, GUEST_FULL),
    (OTHER_SHORT, OTHER_FULL),
    (REFEREE_SHORT, REFEREE_FULL),
)

CLUB_ROLE_PRESES = "Prezes"
CLUB_ROLE_BOARD_MEMBER = "Dyrektor sportowy"
CLUB_ROLE_SPORT_DIRECTOR = "Członek zarządu"
CLUB_ROLE_SCOUT_DIRECTOR = "Dyrektor skautingu"
CLUB_ROLE_TEAM_LEADER = "Kierownik drużyny"
CLUB_ROLE_OTHERS = "Inne"

CLUB_ROLES = (
    ("P", CLUB_ROLE_PRESES),
    ("DSp", CLUB_ROLE_BOARD_MEMBER),
    ("CZ", CLUB_ROLE_SPORT_DIRECTOR),
    ("DSk", CLUB_ROLE_SCOUT_DIRECTOR),
    ("KD", CLUB_ROLE_TEAM_LEADER),
    ("O", CLUB_ROLE_OTHERS),
)
