# Generated by Django 3.2 on 2022-07-08 09:14

import address.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import django_countries.fields
import django_fsm


class Migration(migrations.Migration):

    replaces = [('marketplace', '0001_initial'), ('marketplace', '0002_auto_20201222_1246'), ('marketplace', '0003_auto_20201222_1342'), ('marketplace', '0004_announcement_club'), ('marketplace', '0005_announcement_address'), ('marketplace', '0006_announcement_positions'), ('marketplace', '0007_auto_20201223_1201'), ('marketplace', '0008_auto_20201227_1557'), ('marketplace', '0009_announcement_disabled'), ('marketplace', '0010_announcement_expire'), ('marketplace', '0011_auto_20201229_1646'), ('marketplace', '0012_playerforclubannouncement'), ('marketplace', '0013_auto_20211125_0353'), ('marketplace', '0014_auto_20211125_0354'), ('marketplace', '0015_auto_20211125_0356'), ('marketplace', '0016_auto_20211125_1900'), ('marketplace', '0017_auto_20211126_0029'), ('marketplace', '0018_clubforcoachannouncement_coachforclubannouncement'), ('marketplace', '0019_auto_20211215_0115'), ('marketplace', '0020_auto_20211215_2355'), ('marketplace', '0021_playerforclubannouncement_league'), ('marketplace', '0022_auto_20220118_0119'), ('marketplace', '0023_auto_20220118_0143'), ('marketplace', '0024_auto_20220524_1236')]

    initial = True

    dependencies = [
        ('users', '0005_auto_20201128_1256'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0016_auto_20201210_1851'),
        ('profiles', '0057_coachprofile_data'),
        ('clubs', '0044_auto_20211024_2228'),
        ('address', '0003_auto_20200830_1851'),
        ('clubs', '0066_team_full_name'),
        ('profiles', '0041_playerposition'),
        ('clubs', '0045_auto_20211108_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Plan name', max_length=255, verbose_name='Plan Name')),
                ('limit', models.PositiveIntegerField(help_text='Limit how many actions are allowed', verbose_name='Plan limit')),
                ('sort', models.PositiveIntegerField(default=0, help_text='Used to sort plans low numbers threaded as lowest plans. Default=0 which means this is not set.', verbose_name='Soring')),
                ('description', models.TextField(blank=True, help_text='Short description what is rationale behind plan. Used only for internal purpose.', null=True, verbose_name='Description')),
                ('default', models.BooleanField(default=False, help_text='Defines if this is default plan selected during account creation.', verbose_name='Default Plan')),
                ('days', models.DurationField(blank=True, default=datetime.timedelta, help_text='Number of days to set after which plan expires. Can be null which means is not activated.', null=True)),
            ],
            options={
                'unique_together': {('name', 'limit')},
            },
        ),
        migrations.CreateModel(
            name='AnnouncementUserQuota',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('counter', models.PositiveIntegerField(default=0, help_text='Current number of used inquiries.', verbose_name='Obecna ilość ogłoszeń')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.announcementplan')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default=1)),
                ('status', django_fsm.FSMField(choices=[('NOWE', 'NOWE'), ('WYSŁANO', 'WYSŁANO'), ('PRZECZYTANE', 'PRZECZYTANE'), ('ZAAKCEPTOWANE', 'ZAAKCEPTOWANE'), ('ODRZUCONE', 'ODRZUCONE')], default='NOWE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_creator', to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clubs.league')),
                ('seniority', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clubs.seniority')),
                ('voivodeship', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clubs.voivodeship')),
                ('country', django_countries.fields.CountryField(default='PL', max_length=2, null=True, verbose_name='Country')),
                ('gender', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clubs.gender')),
                ('www', models.URLField(blank=True, null=True)),
                ('club', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('address', address.models.AddressField(blank=True, help_text='Adres', null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
                ('positions', models.ManyToManyField(to='profiles.PlayerPosition')),
            ],
        ),
        migrations.AlterModelManagers(
            name='announcement',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='expire',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='year_from',
            field=models.PositiveIntegerField(default=1900, help_text='Rocznik piłkarza od.. np. 1986'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='year_to',
            field=models.PositiveIntegerField(default=1900, help_text='Rocznik piłkarza ..do np. 1986'),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='Announcement',
            new_name='ClubForPlayerAnnouncement',
        ),
        migrations.CreateModel(
            name='PlayerForClubAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMField(choices=[('NOWE', 'NOWE'), ('WYSŁANO', 'WYSŁANO'), ('PRZECZYTANE', 'PRZECZYTANE'), ('ZAAKCEPTOWANE', 'ZAAKCEPTOWANE'), ('ODRZUCONE', 'ODRZUCONE')], default='NOWE', max_length=50)),
                ('disabled', models.BooleanField(default=False)),
                ('expire', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('practice_distance', models.CharField(max_length=3)),
                ('body', models.TextField()),
                ('address', address.models.AddressField(blank=True, help_text='Adres', null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_for_club_announcement_creator', to=settings.AUTH_USER_MODEL)),
                ('target_league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.league')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.playerposition')),
                ('subscribers', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
                ('voivodeship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.voivodeship')),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_for_club_announcement_league', to='clubs.league')),
            ],
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CoachForClubAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMField(choices=[('NOWE', 'NOWE'), ('WYSŁANO', 'WYSŁANO'), ('PRZECZYTANE', 'PRZECZYTANE'), ('ZAAKCEPTOWANE', 'ZAAKCEPTOWANE'), ('ODRZUCONE', 'ODRZUCONE')], default='NOWE', max_length=50)),
                ('disabled', models.BooleanField(default=False)),
                ('expire', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lic_type', models.IntegerField(blank=True, choices=[(1, 'UEFA PRO'), (2, 'UEFA A'), (3, 'UEFA EY A'), (4, 'UEFA B'), (5, 'UEFA C'), (6, 'GRASS C'), (7, 'GRASS D'), (8, 'UEFA Futsal B'), (9, 'PZPN A'), (10, 'PZPN B'), (11, 'W trakcie kursu')], null=True, verbose_name='Licencja')),
                ('practice_distance', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{1,3}$')])),
                ('body', models.TextField()),
                ('address', address.models.AddressField(blank=True, help_text='Adres', null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_for_club_announcement_creator', to=settings.AUTH_USER_MODEL)),
                ('subscribers', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
                ('target_league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.league')),
                ('voivodeship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.voivodeship')),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_for_club_announcement_league', to='clubs.league')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClubForCoachAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMField(choices=[('NOWE', 'NOWE'), ('WYSŁANO', 'WYSŁANO'), ('PRZECZYTANE', 'PRZECZYTANE'), ('ZAAKCEPTOWANE', 'ZAAKCEPTOWANE'), ('ODRZUCONE', 'ODRZUCONE')], default='NOWE', max_length=50)),
                ('disabled', models.BooleanField(default=False)),
                ('expire', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lic_type', models.IntegerField(blank=True, choices=[(1, 'UEFA PRO'), (2, 'UEFA A'), (3, 'UEFA EY A'), (4, 'UEFA B'), (5, 'UEFA C'), (6, 'GRASS C'), (7, 'GRASS D'), (8, 'UEFA Futsal B'), (9, 'PZPN A'), (10, 'PZPN B'), (11, 'W trakcie kursu')], null=True, verbose_name='Licencja')),
                ('body', models.TextField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_for_coach_announcement_creator', to=settings.AUTH_USER_MODEL)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.gender')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_for_coach_announcement_league', to='clubs.league')),
                ('seniority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.seniority')),
                ('subscribers', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
                ('voivodeship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.voivodeship')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='clubforplayerannouncement',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.gender'),
        ),
        migrations.AlterField(
            model_name='clubforplayerannouncement',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.league'),
        ),
        migrations.AlterField(
            model_name='clubforplayerannouncement',
            name='seniority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.seniority'),
        ),
    ]
