# Generated by Django 3.1.2 on 2020-12-22 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0016_auto_20201210_1851"),
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="league",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="clubs.league",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="announcement",
            name="seniority",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="clubs.seniority",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="announcement",
            name="voivodeship",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="clubs.voivodeship",
            ),
            preserve_default=False,
        ),
    ]
