# Generated by Django 3.2 on 2022-07-12 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0069_merge_20220713_0002'),
        ('voivodeships', '0001_initial'),
        ('marketplace', '0002_auto_20220708_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubforcoachannouncement',
            name='new_voivodeship',
            field=models.ForeignKey(blank=True, help_text='Wybierz województwo. Nowe pole', null=True, on_delete=django.db.models.deletion.CASCADE, to='voivodeships.voivodeships', verbose_name='Województwo'),
        ),
        migrations.AddField(
            model_name='clubforplayerannouncement',
            name='new_voivodeship',
            field=models.ForeignKey(blank=True, help_text='Wybierz województwo. Nowe pole', null=True, on_delete=django.db.models.deletion.CASCADE, to='voivodeships.voivodeships', verbose_name='Województwo'),
        ),
        migrations.AddField(
            model_name='coachforclubannouncement',
            name='new_voivodeship',
            field=models.ForeignKey(blank=True, help_text='Wybierz województwo. Nowe pole', null=True, on_delete=django.db.models.deletion.CASCADE, to='voivodeships.voivodeships', verbose_name='Województwo'),
        ),
        migrations.AddField(
            model_name='playerforclubannouncement',
            name='new_voivodeship',
            field=models.ForeignKey(blank=True, help_text='Wybierz województwo. Nowe pole', null=True, on_delete=django.db.models.deletion.CASCADE, to='voivodeships.voivodeships', verbose_name='Województwo'),
        ),
        migrations.AlterField(
            model_name='clubforcoachannouncement',
            name='voivodeship',
            field=models.ForeignKey(help_text='Wybierz województwo. Stare pole, gotowe do migracji', on_delete=django.db.models.deletion.CASCADE, to='clubs.voivodeship', verbose_name='Województwo'),
        ),
        migrations.AlterField(
            model_name='clubforplayerannouncement',
            name='voivodeship',
            field=models.ForeignKey(help_text='Wybierz województwo. Stare pole, gotowe do migracji', on_delete=django.db.models.deletion.CASCADE, to='clubs.voivodeship', verbose_name='Województwo'),
        ),
        migrations.AlterField(
            model_name='coachforclubannouncement',
            name='voivodeship',
            field=models.ForeignKey(help_text='Wybierz województwo. Stare pole, gotowe do migracji', on_delete=django.db.models.deletion.CASCADE, to='clubs.voivodeship', verbose_name='Województwo'),
        ),
        migrations.AlterField(
            model_name='playerforclubannouncement',
            name='voivodeship',
            field=models.ForeignKey(help_text='Wybierz województwo. Stare pole, gotowe do migracji', on_delete=django.db.models.deletion.CASCADE, to='clubs.voivodeship', verbose_name='Województwo'),
        ),
    ]
