# Generated by Django 3.2 on 2022-07-16 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voivodeships', '0003_auto_20220715_1633'),
        ('clubs', '0069_auto_20220716_1048'),
        ('marketplace', '0002_auto_20220708_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubforcoachannouncement',
            name='voivodeship_obj',
            field=models.ForeignKey(blank=True, help_text='Wybierz województwo. Nowe pole', null=True, on_delete=django.db.models.deletion.SET_NULL, to='voivodeships.voivodeships', verbose_name='Województwo'),
        ),
        migrations.AddField(
            model_name='clubforplayerannouncement',
            name='voivodeship_obj',
            field=models.ForeignKey(blank=True, help_text='Wybierz województwo. Nowe pole', null=True, on_delete=django.db.models.deletion.SET_NULL, to='voivodeships.voivodeships', verbose_name='Województwo'),
        ),
        migrations.AddField(
            model_name='coachforclubannouncement',
            name='voivodeship_obj',
            field=models.ForeignKey(blank=True, help_text='Wybierz województwo. Nowe pole', null=True, on_delete=django.db.models.deletion.SET_NULL, to='voivodeships.voivodeships', verbose_name='Województwo'),
        ),
        migrations.AddField(
            model_name='playerforclubannouncement',
            name='voivodeship_obj',
            field=models.ForeignKey(blank=True, help_text='Wybierz województwo. Nowe pole', null=True, on_delete=django.db.models.deletion.SET_NULL, to='voivodeships.voivodeships', verbose_name='Województwo'),
        ),
        migrations.AlterField(
            model_name='clubforcoachannouncement',
            name='voivodeship',
            field=models.ForeignKey(blank=True, help_text='Wybierz województwo. Stare pole, gotowe do migracji', null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.voivodeship', verbose_name='Województwo'),
        ),
        migrations.AlterField(
            model_name='clubforplayerannouncement',
            name='voivodeship',
            field=models.ForeignKey(blank=True, help_text='Wybierz województwo. Stare pole, gotowe do migracji', null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.voivodeship', verbose_name='Województwo'),
        ),
        migrations.AlterField(
            model_name='coachforclubannouncement',
            name='voivodeship',
            field=models.ForeignKey(blank=True, help_text='Wybierz województwo. Stare pole, gotowe do migracji', null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.voivodeship', verbose_name='Województwo'),
        ),
        migrations.AlterField(
            model_name='playerforclubannouncement',
            name='voivodeship',
            field=models.ForeignKey(blank=True, help_text='Wybierz województwo. Stare pole, gotowe do migracji', null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.voivodeship', verbose_name='Województwo'),
        ),
    ]
