# Generated by Django 3.2 on 2022-07-13 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0069_merge_20220713_0002'),
        ('marketplace', '0003_auto_20220713_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubforcoachannouncement',
            name='voivodeship',
            field=models.ForeignKey(blank=True, help_text='Wybierz województwo. Stare pole, gotowe do migracji', null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.voivodeship', verbose_name='Województwo'),
        ),
        migrations.AlterField(
            model_name='clubforplayerannouncement',
            name='voivodeship',
            field=models.ForeignKey(blank=True, help_text='Wybierz województwo. Stare pole, gotowe do migracji', null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.voivodeship', verbose_name='Województwo'),
        ),
        migrations.AlterField(
            model_name='coachforclubannouncement',
            name='voivodeship',
            field=models.ForeignKey(blank=True, help_text='Wybierz województwo. Stare pole, gotowe do migracji', null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.voivodeship', verbose_name='Województwo'),
        ),
        migrations.AlterField(
            model_name='playerforclubannouncement',
            name='voivodeship',
            field=models.ForeignKey(blank=True, help_text='Wybierz województwo. Stare pole, gotowe do migracji', null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.voivodeship', verbose_name='Województwo'),
        ),
    ]
