# Generated by Django 3.1.2 on 2020-12-22 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0016_auto_20201210_1851"),
        ("marketplace", "0003_auto_20201222_1342"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="club",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="clubs.club"
            ),
            preserve_default=False,
        ),
    ]
