# Generated by Django 3.2 on 2022-07-16 08:49

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations

from voivodeships.services import VoivodeshipService


def map_vivos(apps, schema_editor):

    vivos_manager = VoivodeshipService()
    from django.apps import apps

    announcements = [
        'ClubForPlayerAnnouncement', 'PlayerForClubAnnouncement', 'CoachForClubAnnouncement', 'ClubForCoachAnnouncement'
    ]

    for announcement in announcements:

        model = apps.get_model('marketplace', announcement)

        for ann in model.objects.all():

            try:
                get_voivo = vivos_manager.get_voivodeship_by_name(ann.voivodeship.name)
                if get_voivo.exists():

                    vivo = apps.get_model('voivodeships', 'Voivodeships')
                    vivo = vivo.objects.get(id=get_voivo[0].id)

                    ann.voivodeship_obj = vivo
                    ann.save()
            except (ObjectDoesNotExist, AttributeError):
                print(f'Something went wrong with {ann}')


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20220716_1048'),
    ]

    operations = [
        migrations.RunPython(map_vivos),
    ]
