# Generated by Django 3.1.2 on 2020-12-22 14:26

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('marketplace', '0004_announcement_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='address',
            field=address.models.AddressField(blank=True, help_text='Adres', null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
    ]
