# Generated by Django 3.1.2 on 2020-12-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0041_playerposition'),
        ('marketplace', '0005_announcement_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='positions',
            field=models.ManyToManyField(to='profiles.PlayerPosition'),
        ),
    ]
