# Generated by Django 3.1.2 on 2020-12-27 14:57

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("marketplace", "0007_auto_20201223_1201"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="announcementplan",
            name="days",
            field=models.DurationField(
                blank=True,
                default=datetime.timedelta,
                help_text="Number of days to set after which plan expires. Can be null which means is not activated.",
                null=True,
            ),
        ),
    ]
