# Generated by Django 3.1.2 on 2020-12-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_auto_20201227_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
