# Generated by Django 3.1.2 on 2020-12-27 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0009_announcement_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="expire",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
