# Generated by Django 3.1.2 on 2020-12-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0010_announcement_expire"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="year_from",
            field=models.PositiveIntegerField(
                default=1900, help_text="Rocznik piłkarza od.. np. 1986"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="announcement",
            name="year_to",
            field=models.PositiveIntegerField(
                default=1900, help_text="Rocznik piłkarza ..do np. 1986"
            ),
            preserve_default=False,
        ),
    ]
