# Generated by Django 3.1.13 on 2021-11-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0012_playerforclubannouncement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerforclubannouncement",
            name="practice_distance",
            field=models.TextField(max_length=500),
        ),
    ]
