# Generated by Django 3.1.13 on 2021-11-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0013_auto_20211125_0353"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerforclubannouncement",
            name="practice_distance",
            field=models.TextField(max_length=3),
        ),
    ]
