# Generated by Django 3.1.13 on 2021-11-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_auto_20211125_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerforclubannouncement',
            name='practice_distance',
            field=models.CharField(max_length=3),
        ),
    ]
