# Generated by Django 3.1.13 on 2021-11-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0015_auto_20211125_0356"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playerforclubannouncement",
            old_name="looking_for",
            new_name="target_league",
        ),
    ]
