# Generated by Django 3.1.13 on 2021-11-25 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.manager
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("address", "0003_auto_20200830_1851"),
        ("profiles", "0057_coachprofile_data"),
        ("clubs", "0045_auto_20211108_2309"),
        ("marketplace", "0016_auto_20211125_1900"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Announcement",
            new_name="ClubForPlayerAnnouncement",
        ),
    ]
