# Generated by Django 3.1.13 on 2021-12-15 00:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0045_auto_20211108_2309"),
        ("marketplace", "0018_clubforcoachannouncement_coachforclubannouncement"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachforclubannouncement",
            name="league",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coach_for_club_announcement_league",
                to="clubs.league",
            ),
        ),
        migrations.AlterField(
            model_name="coachforclubannouncement",
            name="practice_distance",
            field=models.CharField(
                max_length=3,
                validators=[django.core.validators.RegexValidator("^\\d{1,3}$")],
            ),
        ),
    ]
