# Generated by Django 3.1.13 on 2021-12-15 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_auto_20211215_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubforcoachannouncement',
            name='country',
        ),
        migrations.RemoveField(
            model_name='clubforcoachannouncement',
            name='target_league',
        ),
    ]
