# Generated by Django 3.1.2 on 2020-11-12 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "PlayMaker Main Page"},
        ),
    ]
