# Generated by Django 3.1.2 on 2020-11-25 18:17

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations

import streams.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("flex", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flexpage",
            name="content",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "title_and_text",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Add your title", required=True
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="Add additional text", required=True
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("full_richtext", streams.blocks.RichtextBlock()),
                    ("simple_richtext", streams.blocks.SimpleRichtextBlock()),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
