# Generated by Django 3.2.25 on 2025-06-08 01:16

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


def migrate_data(apps, schema_editor):
    """
    Migrate data from the old transfer request and status fields to the new ones.
    This function is called during the migration process.
    """
    ProfileTransferRequestOld = apps.get_model("profiles", "ProfileTransferRequest")
    ProfileTransferStatusOld = apps.get_model("profiles", "ProfileTransferStatus")
    ProfileTransferRequest = apps.get_model("transfers", "ProfileTransferRequest")
    ProfileTransferStatus = apps.get_model("transfers", "ProfileTransferStatus")

    for obj in ProfileTransferRequestOld.objects.all():
        if hasattr(obj, "content_object") and obj.content_object:
            content_object = obj.content_object
        else:
            content_object = apps.get_model(
                obj.content_type.app_label, obj.content_type.model
            ).objects.get(pk=obj.object_id)
        last = ProfileTransferRequest.objects.create(
            pk=obj.pk,
            meta=content_object.meta,
            requesting_team=obj.requesting_team,
            status=obj.status,
            salary=obj.salary,
            benefits=obj.benefits,
            number_of_trainings=obj.number_of_trainings,
            gender=obj.gender,
            league=obj.league,
            voivodeship=obj.voivodeship,
            created_at=obj.created_at,
            updated_at=obj.updated_at,
        )
        for position in obj.position.all():
            last.position.add(position)

    for obj in ProfileTransferStatusOld.objects.all():
        if hasattr(obj, "content_object") and obj.content_object:
            content_object = obj.content_object
        else:
            content_object = apps.get_model(
                obj.content_type.app_label, obj.content_type.model
            ).objects.get(pk=obj.object_id)
        last = ProfileTransferStatus.objects.create(
            pk=obj.pk,
            meta=content_object.meta,
            salary=obj.salary,
            benefits=obj.benefits,
            number_of_trainings=obj.number_of_trainings,
            created_at=obj.created_at,
            updated_at=obj.updated_at,
            status=obj.status,
            additional_info=obj.additional_info,
        )
        for league in obj.league.all():
            last.league.add(league)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profiles", "0174_auto_20250608_0316"),
        ("clubs", "0097_club_visible"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileTransferStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salary",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "0 - 499 zł"),
                            ("2", "500 - 999 zł"),
                            ("3", "1000 - 1999 zł"),
                            ("4", "2000 - 3999 zł"),
                            ("5", "4000+ zł"),
                        ],
                        default=None,
                        help_text="Define salary",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "benefits",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("1", "Zwrot lub organizacja transportu"),
                                ("2", "Zwrot za buty lub rękawice"),
                                ("3", "Sprzęt treningowy"),
                                ("4", "Dobre zaplecze treningowe"),
                                ("5", "Premie za wygrane"),
                                ("6", "Fizjoterapeuta w sztabie"),
                                ("7", "Siłownia do dyspozycji"),
                                ("8", "Walka o awans"),
                                ("9", "Doświadczony trener"),
                            ],
                            help_text="Additional information about the transfer.",
                            max_length=255,
                            null=True,
                        ),
                        blank=True,
                        help_text="Benefits defines as integers with comma. Example: 1,2",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "number_of_trainings",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "1-2 treningi tygodniowo"),
                            ("2", "3-4 treningi tygodniowo"),
                            ("3", "5+ treningów tygodniowo"),
                        ],
                        default=None,
                        help_text="Define number of trainings per week",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1", "Szukam klubu"),
                            ("2", "Rozważę propozycje"),
                            ("3", "Nie szukam klubu"),
                            ("4", "Piłkarska emerytura"),
                        ],
                        help_text="Defines a status of the transfer for the profile.",
                        max_length=255,
                    ),
                ),
                (
                    "additional_info",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("1", "Dostępny od zaraz"),
                                ("2", "Wracam po kontuzji"),
                                ("3", "Możliwe wypożyczenie"),
                                ("4", "Po przeprowadzce"),
                                ("5", "Studiuje zaoczne"),
                                ("6", "Pracuje w nieregularnym trybie pracy"),
                            ],
                            help_text="Additional information about the transfer.",
                            max_length=10,
                        ),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "league",
                    models.ManyToManyField(
                        related_name="transfer_status", to="clubs.League"
                    ),
                ),
                (
                    "meta",
                    models.ForeignKey(
                        help_text="The profile meta that this transfer status belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_status",
                        to="profiles.profilemeta",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProfileTransferRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salary",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "0 - 499 zł"),
                            ("2", "500 - 999 zł"),
                            ("3", "1000 - 1999 zł"),
                            ("4", "2000 - 3999 zł"),
                            ("5", "4000+ zł"),
                        ],
                        default=None,
                        help_text="Define salary",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "benefits",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("1", "Zwrot lub organizacja transportu"),
                                ("2", "Zwrot za buty lub rękawice"),
                                ("3", "Sprzęt treningowy"),
                                ("4", "Dobre zaplecze treningowe"),
                                ("5", "Premie za wygrane"),
                                ("6", "Fizjoterapeuta w sztabie"),
                                ("7", "Siłownia do dyspozycji"),
                                ("8", "Walka o awans"),
                                ("9", "Doświadczony trener"),
                            ],
                            help_text="Additional information about the transfer.",
                            max_length=255,
                            null=True,
                        ),
                        blank=True,
                        help_text="Benefits defines as integers with comma. Example: 1,2",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "number_of_trainings",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "1-2 treningi tygodniowo"),
                            ("2", "3-4 treningi tygodniowo"),
                            ("3", "5+ treningów tygodniowo"),
                        ],
                        default=None,
                        help_text="Define number of trainings per week",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "M"), ("F", "F")],
                        help_text="Define team gender",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Nieznany"),
                            ("2", "Szukam piłkarzy"),
                            ("3", "Nie szukam piłkarzy"),
                        ],
                        help_text="Defines a status of the transfer for the profile.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "league",
                    models.CharField(
                        blank=True,
                        help_text="League name filled automatically from team.club.voivodeship_obj",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "voivodeship",
                    models.CharField(
                        blank=True,
                        help_text="Voivodeship name filled automatically from team.club.voivodeship_obj",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "meta",
                    models.ForeignKey(
                        help_text="The profile meta that this transfer request belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_requests",
                        to="profiles.profilemeta",
                    ),
                ),
                (
                    "position",
                    models.ManyToManyField(
                        help_text="The position that the team is requesting.",
                        related_name="transfer_requests",
                        to="profiles.PlayerPosition",
                    ),
                ),
                (
                    "requesting_team",
                    models.ForeignKey(
                        help_text="The team that is requesting the transfer.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_requests",
                        to="profiles.teamcontributor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(migrate_data, migrations.RunPython.noop),
    ]
