# Generated by Django 3.2.25 on 2025-06-19 21:07

import uuid

import django.db.models.deletion
from django.db import migrations, models


def create_uuid(apps, schema_editor):
    ProfileTransferRequest = apps.get_model("transfers", "ProfileTransferRequest")
    ProfileTransferStatus = apps.get_model("transfers", "ProfileTransferStatus")

    for request in ProfileTransferRequest.objects.all():
        request.anonymous_uuid = uuid.uuid4()
        request.save()

    for status in ProfileTransferStatus.objects.all():
        status.anonymous_uuid = uuid.uuid4()
        status.save()


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0175_auto_20250608_0350"),
        ("transfers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiletransferrequest",
            name="anonymous_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profiletransferstatus",
            name="anonymous_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(create_uuid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="profiletransferrequest",
            name="anonymous_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="profiletransferstatus",
            name="anonymous_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="profiletransferrequest",
            name="is_anonymous",
            field=models.BooleanField(
                default=False,
                help_text="If true, the transfer object will be anonymous.",
            ),
        ),
        migrations.AddField(
            model_name="profiletransferstatus",
            name="is_anonymous",
            field=models.BooleanField(
                default=False,
                help_text="If true, the transfer object will be anonymous.",
            ),
        ),
        migrations.AlterField(
            model_name="profiletransferrequest",
            name="meta",
            field=models.OneToOneField(
                help_text="The profile meta that this transfer request belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfer_request",
                to="profiles.profilemeta",
            ),
        ),
        migrations.AlterField(
            model_name="profiletransferstatus",
            name="meta",
            field=models.OneToOneField(
                help_text="The profile meta that this transfer status belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfer_status",
                to="profiles.profilemeta",
            ),
        ),
    ]
