# Generated by Django 3.2.25 on 2025-10-04 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0178_alter_profilemeta_user'),
        ('transfers', '0002_auto_20250619_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletransferrequest',
            name='requesting_team',
            field=models.ForeignKey(blank=True, help_text='The team that is requesting the transfer.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='profiles.teamcontributor'),
        ),
    ]
