# Generated by Django 3.2 on 2022-11-28 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0078_alter_season_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Cel',
                'verbose_name_plural': 'Cele rozmów',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_method', models.CharField(blank=True, choices=[('Phone call', 'Phone call'), ('Live', 'Live'), ('Mail', 'Mail'), ('Twitter', 'Twitter'), ('Facebook', 'Facebook'), ('LinkedIn', 'LinkedIn'), ('Instagram', 'Instagram'), ('Website', 'Website')], max_length=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('todo', models.TextField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('reminding_contact', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('financial_conditions_from', models.PositiveIntegerField(blank=True, null=True)),
                ('financial_conditions_to', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='Miasto')),
                ('range', models.PositiveIntegerField(blank=True, null=True, verbose_name='Promień odległości w kilometrach')),
                ('by_who', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_user', to=settings.AUTH_USER_MODEL, verbose_name='Responsible user')),
                ('contact_purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_method', to='crm.contactpurpose')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rozmowe',
                'verbose_name_plural': 'Rozmowy',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Rola',
                'verbose_name_plural': 'Role',
            },
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Facebook')),
                ('twitter_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Twitter')),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Linkedin')),
                ('instagram_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Instagram')),
                ('website_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Website')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('data_mapper_id', models.PositiveIntegerField(blank=True, help_text='ID of object placed in data_ database. It should alwayes reflect scheme which represents.', null=True)),
                ('is_actual', models.BooleanField(default=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_club', to='clubs.club')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_creator', to=settings.AUTH_USER_MODEL)),
                ('previous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='crm.leadstatus')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_team', to='clubs.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_updater', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to=settings.AUTH_USER_MODEL)),
                ('user_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_role', to='crm.role')),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontakty',
                'ordering': ['-is_actual'],
            },
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, choices=[(1, 'Bramkarz'), (2, 'Obrońca Lewy'), (3, 'Obrońca Prawy'), (4, 'Obrońca Środkowy'), (5, 'Pomocnik defensywny'), (6, 'Pomocnik środkowy'), (7, 'Pomocnik ofensywny'), (8, 'Skrzydłowy'), (9, 'Napastnik')], null=True, verbose_name='Pozycja')),
                ('is_junior', models.BooleanField(default=False, verbose_name='Młodzieżówka')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.conversation')),
                ('league', models.ManyToManyField(blank=True, null=True, to='clubs.League', verbose_name='Poziom rozgrywkowy')),
            ],
            options={
                'verbose_name': 'Zapotrzebowanie',
                'verbose_name_plural': 'Zapotrzebowanie',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='crm.leadstatus'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
