# Generated by Django 3.2 on 2022-07-26 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0068_alter_team_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Facebook')),
                ('twitter_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Twitter')),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Linkedin')),
                ('instagram_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Instagram')),
                ('website_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Website')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('data_mapper_id', models.PositiveIntegerField(blank=True, help_text='ID of object placed in data_ database. It should alwayes reflect scheme which represents.', null=True)),
                ('is_actual', models.BooleanField(default=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_club', to='clubs.club')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_creator', to=settings.AUTH_USER_MODEL)),
                ('next', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_version', to='crm.leadstatus')),
                ('previous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_version', to='crm.leadstatus')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_team', to='clubs.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_updater', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
