# Generated by Django 3.2 on 2022-07-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20220727_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
