# Generated by Django 3.2 on 2022-07-31 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0068_alter_team_full_name'),
        ('crm', '0004_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Miasto'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='financial_conditions_from',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='financial_conditions_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='range',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Promień odległości w kilometrach'),
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, choices=[(1, 'Bramkarz'), (2, 'Obrońca Lewy'), (3, 'Obrońca Prawy'), (4, 'Obrońca Środkowy'), (5, 'Pomocnik defensywny (6)'), (6, 'Pomocnik środkowy (8)'), (7, 'Pomocnik ofensywny (10)'), (8, 'Skrzydłowy'), (9, 'Napastnik')], null=True, verbose_name='Pozycja')),
                ('is_junior', models.BooleanField(default=False, verbose_name='Młodzieżówka')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.conversation')),
                ('league', models.ManyToManyField(blank=True, null=True, to='clubs.League', verbose_name='Poziom rozgrywkowy')),
            ],
        ),
    ]
