# Generated by Django 3.2 on 2022-08-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20220731_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='position',
            field=models.IntegerField(blank=True, choices=[(1, 'Bramkarz'), (2, 'Obrońca Lewy'), (3, 'Obrońca Prawy'), (4, 'Obrońca Środkowy'), (5, 'Pomocnik defensywny'), (6, 'Pomocnik środkowy'), (7, 'Pomocnik ofensywny'), (8, 'Skrzydłowy'), (9, 'Napastnik')], null=True, verbose_name='Pozycja'),
        ),
        migrations.AlterField(
            model_name='leadstatus',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
