# Generated by Django 3.1.2 on 2020-11-07 16:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(help_text='Displayed Name of club', max_length=255, verbose_name='Club name')),
            ],
        ),
    ]
