# Generated by Django 3.1.2 on 2020-11-08 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="editors",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
