# Generated by Django 3.1.2 on 2020-11-25 22:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0002_club_editors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="club",
            options={"verbose_name": "Klub", "verbose_name_plural": "Kluby"},
        ),
        migrations.AddField(
            model_name="team",
            name="slug",
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
    ]
