# Generated by Django 3.1.2 on 2020-11-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0005_auto_20201126_0020"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(
                help_text="Displayed Name of team",
                max_length=255,
                verbose_name="Team name",
            ),
        ),
    ]
