# Generated by Django 3.1.2 on 2020-11-30 23:24

import address.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_auto_20200830_1851"),
        ("clubs", "0006_auto_20201126_0249"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="club_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="club_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Telefon",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="practice_stadion_address",
            field=address.models.AddressField(
                blank=True,
                help_text="Adres",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coach_practice_stadion_address",
                to="address.address",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="stadion_address",
            field=address.models.AddressField(
                blank=True,
                help_text="Adres",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coach_stadion_address",
                to="address.address",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="diet_suplements",
            field=models.BooleanField(default=False, help_text="diet_suplements"),
        ),
        migrations.AddField(
            model_name="team",
            name="fizo",
            field=models.BooleanField(default=False, help_text="fizo"),
        ),
        migrations.AddField(
            model_name="team",
            name="game_bonus",
            field=models.BooleanField(default=False, help_text="game_bonus"),
        ),
        migrations.AddField(
            model_name="team",
            name="gloves_shoes_refunds",
            field=models.BooleanField(default=False, help_text="gloves_shoes_refunds"),
        ),
        migrations.AddField(
            model_name="team",
            name="regular_gear",
            field=models.BooleanField(default=False, help_text="regular_gear"),
        ),
        migrations.AddField(
            model_name="team",
            name="scolarships",
            field=models.BooleanField(default=False, help_text="scolarships"),
        ),
        migrations.AddField(
            model_name="team",
            name="secondary_trainer",
            field=models.BooleanField(default=False, help_text="secondary_trainer"),
        ),
        migrations.AddField(
            model_name="team",
            name="traning_gear",
            field=models.BooleanField(default=False, help_text="traning_gear"),
        ),
        migrations.AddField(
            model_name="team",
            name="travel_refunds",
            field=models.BooleanField(default=False, help_text="travel_refunds"),
        ),
    ]
