# Generated by Django 3.1.2 on 2020-12-02 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clubs", "0007_auto_20201201_0024"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="editors",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
