# Generated by Django 3.1.2 on 2020-12-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_auto_20201207_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club',
            field=models.CharField(blank=True, help_text='Klub w którym obecnie reprezentuejsz', max_length=255, null=True, verbose_name='Klub'),
        ),
        migrations.AddField(
            model_name='club',
            name='club_raw',
            field=models.CharField(blank=True, help_text='Klub w którym deklarujesz że obecnie reprezentuejsz', max_length=255, null=True, verbose_name='Deklarowany Klub'),
        ),
        migrations.AddField(
            model_name='club',
            name='league',
            field=models.CharField(blank=True, help_text='Poziom rozgrywkowy', max_length=255, null=True, verbose_name='Rozgrywki'),
        ),
        migrations.AddField(
            model_name='club',
            name='league_raw',
            field=models.CharField(blank=True, help_text='Poziom rozgrywkowy który deklarujesz że grasz.', max_length=255, null=True, verbose_name='Rozgrywki'),
        ),
        migrations.AddField(
            model_name='club',
            name='team',
            field=models.CharField(blank=True, help_text='Drużyna w której obecnie grasz', max_length=255, null=True, verbose_name='Drużyna'),
        ),
        migrations.AddField(
            model_name='club',
            name='team_raw',
            field=models.CharField(blank=True, help_text='Drużyna w której deklarujesz że obecnie grasz', max_length=255, null=True, verbose_name='Deklarowana Drużyna'),
        ),
        migrations.AddField(
            model_name='club',
            name='voivodeship',
            field=models.CharField(blank=True, help_text='Wojewódźtwo', max_length=255, null=True, verbose_name='Wojewódźtwo'),
        ),
        migrations.AddField(
            model_name='club',
            name='voivodeship_raw',
            field=models.CharField(blank=True, help_text='Wojewódźtwo w którym grasz.', max_length=255, null=True, verbose_name='Wojewódźtwo'),
        ),
    ]
