# Generated by Django 3.1.2 on 2020-12-10 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0015_auto_20201210_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='club_managers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='teammanagers', to=settings.AUTH_USER_MODEL),
        ),
    ]
