# Generated by Django 3.1.2 on 2021-01-04 21:55

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0016_auto_20201210_1851"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="country",
            field=django_countries.fields.CountryField(
                default="PL", max_length=2, null=True, verbose_name="Kraj"
            ),
        ),
    ]
