# Generated by Django 3.1.2 on 2021-01-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0018_auto_20210117_1515"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="visible",
            field=models.BooleanField(default=True, help_text="Visible on database"),
        ),
    ]
