# Generated by Django 3.1.2 on 2021-02-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0022_auto_20210131_2115"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="code",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="league_code"
            ),
        ),
    ]
