# Generated by Django 3.1.2 on 2021-02-03 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0023_league_code"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("name", "club", "seniority", "league")},
        ),
    ]
