# Generated by Django 3.1.2 on 2021-02-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0027_auto_20210207_1326"),
    ]

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="seniority",
            name="is_senior",
            field=models.BooleanField(default=True),
        ),
    ]
