# Generated by Django 3.1.2 on 2021-07-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0029_league_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="slug",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
