# Generated by Django 3.1.2 on 2021-08-02 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0030_league_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="index",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="league",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clubs.league",
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="zpn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="league",
            name="zpn_mapped",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
