# Generated by Django 3.1.2 on 2021-08-08 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0033_leaguehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguehistory',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical', to='clubs.league'),
        ),
    ]
