# Generated by Django 3.1.2 on 2021-08-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0034_auto_20210808_2117"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaguehistory",
            name="is_matches_data",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leaguehistory",
            name="is_table_data",
            field=models.BooleanField(default=False),
        ),
    ]
