# Generated by Django 3.1.2 on 2021-08-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0035_auto_20210808_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguehistory',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaguehistory',
            name='data_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
