# Generated by Django 3.1.2 on 2021-08-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0036_auto_20210810_2044"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="visible",
            field=models.BooleanField(default=False),
        ),
    ]
