# Generated by Django 3.1.2 on 2021-08-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0037_league_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
