# Generated by Django 3.1.2 on 2021-09-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0038_league_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaguehistory",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
