# Generated by Django 3.1.2 on 2021-09-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0039_leaguehistory_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="isparent",
            field=models.BooleanField(default=False),
        ),
    ]
