# Generated by Django 3.1.2 on 2021-09-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0040_league_isparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='mapping',
            field=models.TextField(blank=True, help_text='!Always keep double commna at the end of each name!!!. Mapping names comma separated. eg "name X,,name Xi,,"', null=True),
        ),
    ]
