# Generated by Django 3.1.2 on 2021-10-13 19:12

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0041_auto_20210925_0839"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="country",
            field=django_countries.fields.CountryField(
                default="PL", max_length=2, null=True, verbose_name="Kraj"
            ),
        ),
    ]
