# Generated by Django 3.1.2 on 2021-10-13 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0042_league_country"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="league",
            unique_together={("name", "country")},
        ),
    ]
