# Generated by Django 3.1.2 on 2021-11-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0044_auto_20211024_2228"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="name",
            field=models.CharField(max_length=355),
        ),
    ]
