# Generated by Django 3.1.13 on 2021-12-26 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0046_auto_20211226_1832"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="leaguegroup",
            name="level",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="league",
            name="city_name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="league",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clubs.region",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="league",
            unique_together={("name", "country", "group", "region", "zpn")},
        ),
    ]
