# Generated by Django 3.1.13 on 2022-01-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0049_auto_20220103_2228"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="virtual",
            field=models.BooleanField(default=False),
        ),
    ]
