# Generated by Django 3.1.13 on 2022-01-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0050_league_virtual"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="data_seasons",
            field=models.ManyToManyField(to="clubs.Season"),
        ),
    ]
