# Generated by Django 3.1.13 on 2022-01-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0051_league_data_seasons"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="data_seasons",
            field=models.ManyToManyField(blank=True, null=True, to="clubs.Season"),
        ),
    ]
