# Generated by Django 3.1.13 on 2022-01-08 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0052_auto_20220108_1535"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="league",
            unique_together={("name", "country", "group", "region", "zpn", "parent")},
        ),
    ]
