# Generated by Django 3.1.13 on 2022-01-25 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0055_auto_20220108_2011'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='league',
            unique_together={('name', 'country', 'zpn', 'parent')},
        ),
    ]
