# Generated by Django 3.1.13 on 2022-01-30 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0056_auto_20220125_2146"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="league",
            unique_together={("name", "zpn", "parent")},
        ),
    ]
