# Generated by Django 3.1.13 on 2022-01-30 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0057_auto_20220130_1818"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="league",
            unique_together={("name", "country", "parent")},
        ),
    ]
