# Generated by Django 3.1.13 on 2022-01-30 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0059_league_top_parent_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="league",
            name="top_parent_id",
        ),
        migrations.AddField(
            model_name="league",
            name="top_parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clubs.league",
            ),
        ),
    ]
