# Generated by Django 3.1.13 on 2022-01-31 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0061_auto_20220131_1432"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="league",
            name="highest_parent",
        ),
    ]
