# Generated by Django 3.1.13 on 2022-01-31 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0062_remove_league_highest_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="highest_parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clubs.league",
            ),
        ),
    ]
