# Generated by Django 3.1.13 on 2022-03-18 10:41

import clubs.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0063_league_highest_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_club', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=clubs.models.Club.get_file_path, verbose_name='Herb klubu'),
        ),
    ]
