# Generated by Django 3.2 on 2022-07-12 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voivodeships', '0001_initial'),
        ('clubs', '0067_alter_club_voivodeship_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='new_voivodeship',
            field=models.ForeignKey(blank=True, help_text='Wybierz województwo. Nowe pole.', max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voivodeships.voivodeships', verbose_name='Województwo'),
        ),
        migrations.AlterField(
            model_name='club',
            name='voivodeship',
            field=models.ForeignKey(blank=True, help_text='Wybierz województwo. Stare pole, czeka na migracje', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.voivodeship', verbose_name='Województwo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pełna nazwa drużyny'),
        ),
    ]
