<<<<<<< HEAD
# Generated by Django 3.2 on 2022-07-08 19:26
=======
# Generated by Django 3.2 on 2022-07-20 00:12
>>>>>>> 35707ff... model for player videos, migrating previous data and view for video management

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("clubs", "0067_alter_club_voivodeship_raw"),
=======
        ('clubs', '0067_alter_club_voivodeship_raw'),
>>>>>>> 35707ff... model for player videos, migrating previous data and view for video management
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name="team",
            name="full_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Pełna nazwa drużyny",
            ),
=======
            model_name='team',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pełna nazwa drużyny'),
>>>>>>> 35707ff... model for player videos, migrating previous data and view for video management
        ),
    ]
