# Generated by Django 3.2 on 2022-07-16 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voivodeships", "0003_auto_20220715_1633"),
        ("clubs", "0068_alter_team_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="voivodeship_obj",
            field=models.ForeignKey(
                blank=True,
                help_text="Wybierz województwo.",
                max_length=20,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="voivodeships.voivodeships",
                verbose_name="Województwo",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="voivodeship",
            field=models.ForeignKey(
                blank=True,
                help_text="Wybierz województwo. Stare pole, czeka na migracje",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clubs.voivodeship",
                verbose_name="Województwo",
            ),
        ),
    ]
