# Generated by Django 3.2 on 2022-08-07 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0068_alter_team_full_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_mapper_id",
                    models.PositiveIntegerField(
                        help_text="ID of object placed in data_ database. It should alwayes reflect scheme which represents."
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
                ("data", models.JSONField(blank=True, null=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_historical",
                        to="clubs.league",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clubs.season",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clubs.team"
                    ),
                ),
            ],
        ),
    ]
