# Generated by Django 3.2 on 2022-07-12 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0068_alter_team_full_name'),
        ('clubs', '0068_auto_20220712_2252'),
    ]

    operations = [
    ]
