# Generated by Django 3.2 on 2022-08-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0069_teamhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamhistory",
            name="autocreated",
            field=models.BooleanField(default=False, help_text="Autocreated"),
        ),
    ]
