# Generated by Django 3.2 on 2022-08-07 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0070_teamhistory_autocreated"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teamhistory",
            unique_together={("team", "season")},
        ),
    ]
