# Generated by Django 3.2 on 2022-08-07 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0071_alter_teamhistory_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamhistory",
            name="league",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_historical",
                to="clubs.league",
            ),
        ),
    ]
