# Generated by Django 3.2 on 2022-08-08 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0072_alter_teamhistory_league"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamhistory",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historical",
                to="clubs.team",
            ),
        ),
    ]
