# Generated by Django 3.2 on 2022-08-13 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0073_alter_teamhistory_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamhistory',
            name='league_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='league_history', to='clubs.leaguehistory'),
        ),
    ]
