# Generated by Django 3.2 on 2022-09-28 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0070_auto_20220716_1049"),
        ("clubs", "0073_alter_teamhistory_team"),
    ]

    operations = []
