# Generated by Django 3.2 on 2022-08-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0074_teamhistory_league_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="is_current",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="season",
            name="is_in_verify_form",
            field=models.BooleanField(default=True),
        ),
    ]
