# Generated by Django 3.2 on 2022-10-04 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0074_merge_20220928_1427"),
        ("clubs", "0074_teamhistory_league_history"),
    ]

    operations = []
