# Generated by Django 3.2 on 2022-10-21 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0075_merge_20221004_1646"),
        ("clubs", "0075_season_is_current"),
    ]

    operations = []
