# Generated by Django 3.2 on 2022-12-18 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0001_initial'),
        ('clubs', '0077_merge_20221026_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ('-is_current',)},
        ),
        migrations.AddField(
            model_name='club',
            name='mapper',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapper.mapper'),
        ),
        migrations.AddField(
            model_name='leaguehistory',
            name='mapper',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapper.mapper'),
        ),
        migrations.AddField(
            model_name='team',
            name='mapper',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapper.mapper'),
        ),
        migrations.AddField(
            model_name='teamhistory',
            name='mapper',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapper.mapper'),
        ),
    ]
