# Generated by Django 3.2 on 2022-11-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0077_merge_20221026_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ('-is_current',)},
        ),
        migrations.RemoveField(
            model_name='club',
            name='club_raw',
        ),
        migrations.RemoveField(
            model_name='team',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='picture',
        ),
        migrations.AddField(
            model_name='club',
            name='scrapper_autocreated',
            field=models.BooleanField(default=False, help_text='Autocreated from new scrapper'),
        ),
        migrations.AddField(
            model_name='club',
            name='scrapper_uuid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='league',
            name='scrapper_autocreated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaguehistory',
            name='scrapper_obj_name',
            field=models.CharField(blank=True, help_text='League(play) name straight from scrapped object', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leaguehistory',
            name='scrapper_parent_uuid',
            field=models.CharField(blank=True, help_text='Parent league uuid, important for higher leagues like Eklstraklasa, 1 Liga etc.', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='leaguehistory',
            name='scrapper_uuid',
            field=models.CharField(blank=True, help_text='League(play) uuid of an object from mongodb', max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='scrapper_autocreated',
            field=models.BooleanField(default=False, help_text='Autocreated from new scrapper'),
        ),
        migrations.AddField(
            model_name='team',
            name='scrapper_teamhistory_id',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teamhistory',
            name='scrapper_team_uuid',
            field=models.CharField(blank=True, help_text='Team uuid from scrapper.', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='teamhistory',
            name='team_name_raw',
            field=models.CharField(blank=True, help_text='Team name from scrapper.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='teamhistory',
            name='data_mapper_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of object placed in data_ database. It should alwayes reflect scheme which represents.', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='teamhistory',
            unique_together={('scrapper_team_uuid', 'league_history')},
        ),
    ]
