# Generated by Django 3.2 on 2022-12-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0078_auto_20221218_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamhistory',
            name='league',
        ),
        migrations.RemoveField(
            model_name='teamhistory',
            name='season',
        ),
    ]
