# Generated by Django 3.2 on 2023-01-05 18:50

from django.db import migrations, models
import django.db.models.deletion


def init_groups(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    model = apps.get_model("clubs", "JuniorAgeGroup")
    model.objects.using(db_alias).get_or_create(name="u19")
    model.objects.using(db_alias).get_or_create(name="u18")
    model.objects.using(db_alias).get_or_create(name="u17")
    model.objects.using(db_alias).get_or_create(name="u16")
    model.objects.using(db_alias).get_or_create(name="u15")
    model.objects.using(db_alias).get_or_create(name="u14")


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0079_auto_20221228_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuniorAgeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='junior_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.junioragegroup'),
        ),
        migrations.RunPython(init_groups)
    ]
