# Generated by Django 3.2 on 2023-03-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0082_auto_20230216_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Skrócona nazwa klubu'),
        ),
    ]
