# Generated by Django 3.2 on 2023-03-17 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('external_links', '0002_alter_externallinksentity_related_type'),
        ('clubs', '0082_auto_20230216_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='external_links',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='external_links.externallinks'),
        ),
        migrations.AddField(
            model_name='leaguehistory',
            name='external_links',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='external_links.externallinks'),
        ),
        migrations.AddField(
            model_name='team',
            name='external_links',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='external_links.externallinks'),
        ),
    ]
