# Generated by Django 3.2 on 2023-08-18 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_season_from_leaguehistory(apps, schema_editor) -> None:
    """
    Populate the 'season' field in TeamHistory instances using related LeagueHistory.

    For each TeamHistory object, if there's an associated LeagueHistory with a defined season,
    copy that season value to the TeamHistory's 'season' field.
    """
    TeamHistory = apps.get_model("clubs", "TeamHistory")
    for team_history in TeamHistory.objects.all():
        if team_history.league_history and team_history.league_history.season:
            team_history.season = team_history.league_history.season
            team_history.save()


def populate_team_managers(apps, schema_editor) -> None:
    """
    Populate the TeamManagers model based on 'manager' and 'editors' fields of the Team model.

    For each Team object:
    1. If there's a manager assigned, create a TeamManagers entry linking that manager to the team.
    2. For each editor associated with the team, create a TeamManagers entry linking that editor to the team.
    """
    Team = apps.get_model("clubs", "Team")
    TeamManagers = apps.get_model("clubs", "TeamManagers")
    for team in Team.objects.all():
        if team.manager:
            TeamManagers.objects.create(team=team, manager=team.manager)
        for editor in team.editors.all():
            TeamManagers.objects.create(team=team, manager=editor)


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0095_create_refereeprofile_and_update_refereelevel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clubs", "0083_auto_20230318_0028"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamhistory",
            name="coach",
            field=models.ForeignKey(
                blank=True,
                help_text="The coach who led the team during this season.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coached_team_histories",
                to="profiles.coachprofile",
            ),
        ),
        migrations.AddField(
            model_name="teamhistory",
            name="season",
            field=models.ForeignKey(
                blank=True,
                help_text="The season associated with this team history entry.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clubs.season",
            ),
        ),
        migrations.CreateModel(
            name="TeamManagers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        help_text="Reference to the user profile managing the team",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        help_text="Reference to the team with which this manager is associated. A team can have multiple managers.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managers",
                        to="clubs.team",
                    ),
                ),
            ],
        ),
        migrations.RunPython(populate_season_from_leaguehistory),
        migrations.RunPython(populate_team_managers),
    ]
