# Generated by Django 3.2 on 2023-07-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0083_auto_20230318_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Skrócona nazwa klubu'),
        ),
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Skrócona nazwa drużyny'),
        ),
    ]
