# Generated by Django 3.2 on 2023-09-05 17:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0084_auto_20230818_2033"),
        ("clubs", "0084_auto_20230831_1833"),
    ]

    operations = []
