# Generated by Django 3.2.21 on 2023-09-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0086_auto_20230920_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ('-is_current', '-name')},
        ),
    ]
