# Generated by Django 3.2 on 2023-09-30 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0087_alter_season_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who manually defined this record. This field is populated only when a user creates or defines the League by themselves.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='league',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Flag indicating whether the league should be displayed in the API.'),
        ),
        migrations.AddField(
            model_name='league',
            name='status',
            field=models.CharField(choices=[('ver', 'Verified'), ('not-ver', 'Not Verified')], default='not-ver', help_text='Verification status of the league.', max_length=10),
        ),
        migrations.AddField(
            model_name='leaguehistory',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who manually defined this record. This field is populated only when a user defines the League by themselves.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaguehistory',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Flag indicating whether the league history should be displayed in the API.'),
        ),
        migrations.AddField(
            model_name='leaguehistory',
            name='status',
            field=models.CharField(choices=[('ver', 'Verified'), ('not-ver', 'Not Verified')], default='not-ver', help_text='Verification status of the league history.', max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who manually defined this record. This field is populated only when a user creates or defines the Team by themselves.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Flag indicating whether the team should be displayed in the API.'),
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('ver', 'Verified'), ('not-ver', 'Not Verified')], default='not-ver', help_text='Verification status of the team.', max_length=10),
        ),
        migrations.AddField(
            model_name='teamhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who manually defined this record. This field is populated only when a user creates or defines the Team by themselves.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamhistory',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Flag indicating whether the team history should be displayed in the API.'),
        ),
        migrations.AddField(
            model_name='teamhistory',
            name='status',
            field=models.CharField(choices=[('ver', 'Verified'), ('not-ver', 'Not Verified')], default='not-ver', help_text='Verification status of the team history.', max_length=10),
        ),
    ]
