# Generated by Django 3.2 on 2023-10-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0088_auto_20230930_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguehistory',
            name='year',
            field=models.IntegerField(blank=True, help_text='Year the league history represents.', null=True),
        ),
    ]
