# Generated by Django 3.2 on 2023-12-31 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0089_leaguehistory_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='voivodeship_raw',
        ),
    ]
