# Generated by Django 3.2 on 2023-12-26 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voivodeships', '0003_auto_20220715_1633'),
        ('clubs', '0089_leaguehistory_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='highest_parent',
        ),
        migrations.RemoveField(
            model_name='league',
            name='isparent',
        ),
        migrations.AddField(
            model_name='league',
            name='league_type',
            field=models.CharField(choices=[('CUP', 'Cup'), ('LEAGUE', 'League')], default='LEAGUE', help_text='Type of the league (e.g., Cup, League)', max_length=10),
        ),
        migrations.AddField(
            model_name='leaguehistory',
            name='name',
            field=models.CharField(help_text='Displayed Name of plays', max_length=255, null=True, verbose_name='Plays name'),
        ),
        migrations.AddField(
            model_name='leaguehistory',
            name='voivodeship_obj',
            field=models.ForeignKey(blank=True, help_text='Wybierz województwo.', max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voivodeships.voivodeships', verbose_name='Województwo'),
        ),
        migrations.AddField(
            model_name='team',
            name='age_category',
            field=models.CharField(blank=True, choices=[('U19', 'U19'), ('U17', 'U17'), ('U16', 'U16'), ('U15', 'U15'), ('U14', 'U14'), ('U13', 'U13'), ('U12', 'U12'), ('U11', 'U11'), ('U10', 'U10'), ('U9', 'U9'), ('U8', 'U8'), ('U7', 'U7'), ('U6', 'U6')], help_text='Age category of the team.', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='league_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_league_history', to='clubs.leaguehistory'),
        ),
        migrations.AlterField(
            model_name='league',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Deprecated: This field is no longer used due to database schema changes. Refer to PM20-792.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childs', to='clubs.league'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_league', to='clubs.league'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'club', 'seniority', 'league_history')},
        ),
    ]