# Generated by Django 3.2 on 2023-12-26 22:35

from django.db import migrations, transaction


def clear_data(apps, schema_editor) -> None:
    """
    This function is designed to clear all data from the Club, Team, TeamHistory,
    League, and LeagueHistory tables. It retrieves the historical versions of these
    models and deletes all records from each table within a single atomic transaction
    to maintain database integrity.
    """
    # Get historical models
    Club = apps.get_model("clubs", "Club")
    Team = apps.get_model("clubs", "Team")
    TeamHistory = apps.get_model("clubs", "TeamHistory")
    League = apps.get_model("clubs", "League")
    LeagueHistory = apps.get_model("clubs", "LeagueHistory")

    with transaction.atomic():
        # Deleting records from each table
        Club.objects.all().delete()
        Team.objects.all().delete()
        TeamHistory.objects.all().delete()
        League.objects.all().delete()
        LeagueHistory.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0090_auto_20231226_2335"),
    ]

    operations = [migrations.RunPython(clear_data)]
