# Generated by Django 3.2 on 2023-12-26 22:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0091_clear_data"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="league",
            unique_together={("name", "country")},
        ),
        migrations.RemoveField(
            model_name="league",
            name="parent",
        ),
    ]
