# Generated by Django 3.2.23 on 2023-12-28 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0007_auto_20230216_0029'),
        ('clubs', '0092_auto_20231226_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='mapper',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapper.mapper'),
        ),
    ]
