# Generated by Django 3.2.23 on 2023-12-30 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0093_league_mapper'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='league',
            unique_together=set(),
        ),
    ]
