# Generated by Django 3.2 on 2024-01-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0090_remove_club_voivodeship_raw'),
        ('clubs', '0094_alter_league_unique_together'),
    ]

    operations = [
    ]
