# Generated by Django 3.2 on 2024-01-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0095_merge_20240103_1729"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="age_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("U19", "U19"),
                    ("U17", "U17"),
                    ("U16", "U16"),
                    ("U15", "U15"),
                    ("U14", "U14"),
                    ("U13", "U13"),
                    ("U12", "U12"),
                    ("U11", "U11"),
                    ("U10", "U10"),
                    ("U9", "U9"),
                    ("U8", "U8"),
                    ("U7", "U7"),
                    ("U6", "U6"),
                ],
                help_text="Age category of the team. Specified for the juniors",
                max_length=3,
                null=True,
            ),
        ),
    ]
