# Generated by Django 3.2 on 2024-01-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0096_alter_team_age_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='visible',
            field=models.BooleanField(default=True, help_text='Visible on database'),
        ),
    ]
