# Generated by Django 3.2.25 on 2025-07-07 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0097_club_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='data_mapper_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='data_mapper_id',
        ),
        migrations.RemoveField(
            model_name='teamhistory',
            name='data_mapper_id',
        ),
    ]
