# Generated by Django 3.2.21 on 2023-09-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="season_name",
            field=models.CharField(default="2018/2019", max_length=9),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="label",
            unique_together={("label_name", "season_name")},
        ),
    ]
