# Generated by Django 3.2.21 on 2023-09-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0002_auto_20230904_2114"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="label_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="label",
            name="label_name",
            field=models.CharField(max_length=25),
        ),
    ]
