# Generated by Django 3.2.21 on 2023-09-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0003_auto_20230904_2233"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="icon",
            field=models.CharField(default="blabla", max_length=200),
            preserve_default=False,
        ),
    ]
