# Generated by Django 3.2.21 on 2023-09-18 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0004_label_icon"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="label",
            unique_together={("object_id", "label_name", "season_name")},
        ),
    ]
