# Generated by Django 3.2.21 on 2023-09-18 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0005_alter_label_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="conditions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="label",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="label",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="label",
            name="visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="label",
            name="visible_on_base",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="label",
            name="visible_on_main_page",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="label",
            name="visible_on_profile",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="label",
            name="icon",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
