# Generated by Django 3.2.21 on 2023-09-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0006_auto_20230918_2245"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="label",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
