# Generated by Django 3.2 on 2023-11-28 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0007_auto_20230918_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=25, unique=True)),
                ('label_description', models.TextField(blank=True, null=True)),
                ('catalog_name', models.CharField(max_length=255, null=True)),
                ('icon', models.CharField(blank=True, max_length=200)),
                ('conditions', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='label',
            name='league',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='season_round',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='label_definition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='labels.labeldefinition'),
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('object_id', 'label_definition', 'season_name')},
        ),
        migrations.RemoveField(
            model_name='label',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='label',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='label',
            name='label_description',
        ),
        migrations.RemoveField(
            model_name='label',
            name='label_name',
        ),
    ]
