# Generated by Django 3.2 on 2023-12-01 23:57

from django.db import migrations


def populate_label_definitions(apps, schema_editor) -> None:
    """
    Populates the LabelDefinition model with predefined label data.
    """
    LabelDefinition = apps.get_model("labels", "LabelDefinition")

    labels = [
        {
            "label_name": "YOUTH",
            "label_description": "Młodzieżowiec",
            "catalog_name": "Młodzieżowcy",
            "icon": "YOUTH",
            "conditions": "profile player and age under 21 during the season",
        },
        {
            "label_name": "HIGH_KEEPER",
            "label_description": "Bramkarz 185+",
            "catalog_name": "Wysocy bramkarze",
            "icon": "KEEPER",
            "conditions": "profile player and position goalkeeper and height 185+",
        },
        {
            "label_name": "LICENCE_PRO",
            "label_description": "UEFA_PRO",
            "catalog_name": "Trenerzy profesjonalni",
            "icon": "LICENCE",
            "conditions": "coach profile and licence type UEFA PRO",
        },
        {
            "label_name": "LICENCE_A",
            "label_description": "UEFA_A",
            "catalog_name": "Trenerzy z UEFA A",
            "icon": "LICENCE",
            "conditions": "coach profile and licence type UEFA A",
        },
        {
            "label_name": "COACH_AGE_30",
            "label_description": "Trenerzy przed 30tka",
            "catalog_name": "Młodzi trenerzy",
            "icon": "AGE",
            "conditions": "coach profile and age under 30",
        },
        {
            "label_name": "COACH_AGE_40",
            "label_description": "Trenerzy przed 40tka",
            "catalog_name": "Młodzi trenerzy",
            "icon": "AGE",
            "conditions": "coach profile and age under 40",
        },
    ]

    for label in labels:
        LabelDefinition.objects.get_or_create(
            label_name=label["label_name"], defaults=label
        )


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0008_auto_20231128_2128"),
    ]

    operations = [
        migrations.RunPython(populate_label_definitions),
    ]
