# Generated by Django 3.2 on 2023-12-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0009_populate_label_definitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='season_name',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
