# Generated by Django 3.1.2 on 2020-11-02 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='followers.item'),
            preserve_default=False,
        ),
    ]
