# Generated by Django 3.1.2 on 2020-12-05 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0011_auto_20201205_1048'),
        ('followers', '0002_auto_20201108_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_team_set', to='clubs.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_team_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
