# Generated by Django 3.2 on 2023-12-27 09:39

from django.db import migrations


def clear_data(apps, schema_editor) -> None:
    """
    This function is designed to clear all data FollowTeam table. It retrieves the historical
    versions of this model and deletes all records from the table.
    """
    # Get historical models
    FollowTeam = apps.get_model("followers", "FollowTeam")
    # Deleting records from each table
    FollowTeam.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0003_followteam'),
    ]

    operations = [
        migrations.RunPython(clear_data)
    ]
