# Generated by Django 3.2.25 on 2025-05-10 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0005_genericfollow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followteam',
            name='target',
        ),
        migrations.RemoveField(
            model_name='followteam',
            name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='influencer',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='item',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='user',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='FollowTeam',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Pin',
        ),
    ]
