# Generated by Django 3.2 on 2022-12-18 20:30

from django.db import migrations, models
import django.db.models.deletion


def init_schema(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    model = apps.get_model("mapper", "MapperSource")
    model.objects.using(db_alias).get_or_create(name="OLD_LNP")
    model.objects.using(db_alias).get_or_create(name="NEW_LNP")
    model.objects.using(db_alias).get_or_create(name="NEW_ADDITIONAL_LNP")
    model.objects.using(db_alias).get_or_create(name="TRANSFERMARKT")
    model.objects.using(db_alias).get_or_create(name="90MINUT")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapperSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MapperEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapper_id', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapper.mappersource')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapper.mapper')),
            ],
            options={
                'unique_together': {('target', 'source')},
            },
        ),
        migrations.RunPython(init_schema)
    ]
