# Generated by Django 3.2 on 2023-01-15 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0003_alter_mapperentity_related_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mapperentity',
            unique_together={('target', 'related_type', 'database_source')},
        ),
    ]
