# Generated by Django 3.2 on 2023-01-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0004_alter_mapperentity_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapperentity',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
