# Generated by Django 3.2 on 2023-02-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0005_alter_mapperentity_related_type'),
        ('mapper', '0005_alter_mapperentity_url'),
    ]

    operations = [
    ]
