# Generated by Django 3.2 on 2023-02-15 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapper", "0006_merge_20230209_1716"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mapperentity",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mapper.mappersource",
            ),
        ),
        migrations.AlterField(
            model_name="mapperentity",
            name="target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mapper.mapper",
            ),
        ),
    ]
