# Generated by Django 3.2 on 2023-03-17 10:20

from django.db import migrations, models
import django.db.models.deletion

def init_schema(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    model = apps.get_model("external_links", "LinkSource")
    model.objects.using(db_alias).get_or_create(name="transfermarket")
    model.objects.using(db_alias).get_or_create(name="min90")
    model.objects.using(db_alias).get_or_create(name="laczynaspilka")
    model.objects.using(db_alias).get_or_create(name="scoutmaker")
    model.objects.using(db_alias).get_or_create(name="inStat")
    model.objects.using(db_alias).get_or_create(name="other")
    model.objects.using(db_alias).get_or_create(name="instagram")
    model.objects.using(db_alias).get_or_create(name="linkedIn")
    model.objects.using(db_alias).get_or_create(name="tikTok")
    model.objects.using(db_alias).get_or_create(name="facebook")
    model.objects.using(db_alias).get_or_create(name="twitter")
    model.objects.using(db_alias).get_or_create(name="website")
    model.objects.using(db_alias).get_or_create(name="other social")

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalLinksEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('related_type', models.CharField(choices=[('team', 'team'), ('player', 'player profile'), ('coach', 'coach profile'), ('club', 'club'), ('team history', 'team history'), ('league', 'league history highest parent'), ('play', 'league history')], max_length=100)),
                ('creator_type', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], max_length=100)),
                ('link_type', models.CharField(choices=[('statistics', 'statistics'), ('social', 'social')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='external_links.linksource')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='external_links.externallinks')),
            ],
            options={
                'unique_together': {('target', 'source')},
            },
        ),
        migrations.RunPython(init_schema)
    ]
