# Generated by Django 3.2 on 2023-08-23 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('external_links', '0003_alter_externallinksentity_related_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallinksentity',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='external_links.externallinks'),
        ),
    ]
