# Generated by Django 3.2.25 on 2025-01-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_links', '0004_alter_externallinksentity_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallinks',
            name='target_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
