# Generated by Django 3.2.25 on 2025-01-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_links', '0005_externallinks_target_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallinksentity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
