# Generated by Django 3.2.21 on 2024-11-19 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("premium", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalculatePMScoreProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("old_value", models.PositiveBigIntegerField()),
                ("new_value", models.PositiveBigIntegerField()),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PremiumInquiriesProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PremiumProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PremiumProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_since", models.DateTimeField(auto_now_add=True)),
                ("valid_until", models.DateTimeField()),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium",
                        to="premium.premiumproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromoteProfileProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("days_count", models.PositiveIntegerField()),
                ("valid_since", models.DateTimeField(auto_now_add=True)),
                ("valid_until", models.DateTimeField()),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion",
                        to="premium.premiumproduct",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PremiumRequest",
        ),
        migrations.AddField(
            model_name="premiuminquiriesproduct",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiries",
                to="premium.premiumproduct",
            ),
        ),
        migrations.AddField(
            model_name="calculatepmscoreproduct",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calculate_pm_score",
                to="premium.premiumproduct",
            ),
        ),
    ]
