# Generated by Django 3.2.21 on 2024-11-19 14:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from profiles.models import PROFILE_MODELS


def create_premium_product_for_each_profile(apps, schema_editor):
    PremiumProduct = apps.get_model("premium", "PremiumProduct")

    for profile_model_class in PROFILE_MODELS:
        profile_model = apps.get_model("profiles", profile_model_class.__name__)
        for profile in profile_model.objects.all():
            profile.premium_products = PremiumProduct.objects.create()
            profile.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("premium", "0002_auto_20241119_1422"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculatepmscoreproduct",
            name="awaiting_approval",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="premiuminquiriesproduct",
            name="valid_since",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="premiuminquiriesproduct",
            name="valid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="calculatepmscoreproduct",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="calculatepmscoreproduct",
            name="new_value",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="calculatepmscoreproduct",
            name="old_value",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="premiumprofile",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="premium",
                to="premium.premiumproduct",
            ),
        ),
        migrations.AlterField(
            model_name="promoteprofileproduct",
            name="days_count",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="promoteprofileproduct",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="promotion",
                to="premium.premiumproduct",
            ),
        ),
        migrations.RunPython(
            create_premium_product_for_each_profile,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
