# Generated by Django 3.2.21 on 2024-11-19 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0159_auto_20241119_1422"),
        ("premium", "0003_auto_20241119_1502"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculatepmscoreproduct",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.playerprofile",
            ),
        ),
    ]
