# Generated by Django 3.2.25 on 2024-11-19 17:16

from django.db import migrations, models


def import_old_model(apps, schema_editor):
    Product = apps.get_model("premium", "Product")
    TransactionType = apps.get_model("payments", "TransactionType")

    for ttype in TransactionType.objects.all():
        Product.objects.create(
            name=ttype.name,
            name_readable=ttype.name_readable,
            price=ttype.price,
            ref=ttype.ref,
            visible=ttype.visible,
        )


def create_premium_product(apps, schema_editor):
    Product = apps.get_model("premium", "Product")

    Product.objects.create(
        name="PREMIUM", name_readable="Profil Premium", price=49.99, ref="PREMIUM"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("premium", "0004_calculatepmscoreproduct_player"),
        ("payments", "0003_transaction_validation_errors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("name_readable", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "ref",
                    models.CharField(
                        choices=[("PREMIUM", "PREMIUM"), ("INQUIRIES", "INQUIRIES")],
                        max_length=30,
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
            ],
        ),
        migrations.RunPython(import_old_model, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(
            create_premium_product, reverse_code=migrations.RunPython.noop
        ),
    ]
