# Generated by Django 3.2.25 on 2024-11-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0005_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumproduct',
            name='profile_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
