# Generated by Django 3.2.25 on 2024-12-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0006_premiumproduct_profile_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumproduct',
            name='trial_tested',
            field=models.BooleanField(default=False, help_text='Trial already tested?'),
        ),
        migrations.AddField(
            model_name='premiumprofile',
            name='period',
            field=models.PositiveIntegerField(default=7, help_text='Period in days'),
        ),
        migrations.AlterField(
            model_name='promoteprofileproduct',
            name='days_count',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
