# Generated by Django 3.2.25 on 2024-12-17 19:12

from django.db import migrations, models


def deactivate_single_purchase_premium_product(apps, schema_editor):
    """
    Deactivate previous version of premium profile product.

    """
    Product = apps.get_model("premium", "Product")

    Product.objects.filter(name="PREMIUM").update(visible=False)


def create_new_premium_profile_products(apps, schema_editor):
    Product = apps.get_model("premium", "Product")

    # Premium profile player 1 month
    Product.objects.create(
        name="PLAYER_PREMIUM_PROFILE_MONTH",
        ref="PREMIUM",
        price=9.99,
        visible=True,
        name_readable="Monthly premium profile for player",
    )

    # Premium profile player 1 year
    Product.objects.create(
        name="PLAYER_PREMIUM_PROFILE_YEAR",
        ref="PREMIUM",
        price=99.99,
        visible=True,
        name_readable="Yearly premium profile for player",
    )

    # Premium profile others 1 month
    Product.objects.create(
        name="PREMIUM_PROFILE_MONTH",
        ref="PREMIUM",
        price=39.99,
        visible=True,
        name_readable="Monthly premium profile for profiles other than player",
    )

    # Premium profile others 1 year
    Product.objects.create(
        name="PREMIUM_PROFILE_YEAR",
        ref="PREMIUM",
        price=399.99,
        visible=True,
        name_readable="Yearly premium profile for profiles other than player",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("premium", "0007_auto_20241203_1355"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name_readable",
            field=models.CharField(max_length=100),
        ),
        migrations.RunPython(
            deactivate_single_purchase_premium_product,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            create_new_premium_profile_products, reverse_code=migrations.RunPython.noop
        ),
    ]
