# Generated by Django 3.2.25 on 2024-12-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0008_auto_20241217_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumprofile',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promoteprofileproduct',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
