# Generated by Django 3.2.25 on 2024-12-31 02:02

from django.db import migrations

from inquiries.schemas import InquiryPlanTypeRef

new_naming = {
    "PREMIUM_INQUIRIES_5": InquiryPlanTypeRef.PREMIUM_L,
    "PREMIUM_INQUIRIES_10": InquiryPlanTypeRef.PREMIUM_XL,
    "PREMIUM_INQUIRIES_25": InquiryPlanTypeRef.PREMIUM_XXL,
}


def change_inquiry_products(apps, schema_editor):
    Product = apps.get_model("premium", "Product")

    for product in Product.objects.filter(ref="INQUIRIES"):
        new_ref_obj = new_naming[product.name]
        product.name = new_ref_obj.value
        product.name_readable = f"{new_ref_obj.inquiry_count} zapytań"
        product.price = new_ref_obj.price
        product.save()


class Migration(migrations.Migration):
    dependencies = [
        ("premium", "0009_auto_20241217_2333"),
    ]

    operations = [
        migrations.RunPython(
            change_inquiry_products, reverse_code=migrations.RunPython.noop
        )
    ]
