# Generated by Django 3.2.25 on 2024-12-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0010_auto_20241231_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiuminquiriesproduct',
            name='counter_updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='premiuminquiriesproduct',
            name='current_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
