# Generated by Django 3.2.25 on 2025-01-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0011_auto_20241231_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumprofile',
            name='period',
            field=models.PositiveIntegerField(default=3, help_text='Period in days'),
        ),
        migrations.AlterField(
            model_name='promoteprofileproduct',
            name='days_count',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
