# Generated by Django 3.2.25 on 2025-01-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0012_auto_20250108_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumprofile',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
    ]
