# Generated by Django 3.2.25 on 2025-01-16 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_user(apps, schema_editor):
    PremiumProduct = apps.get_model("premium", "PremiumProduct")

    for product in PremiumProduct.objects.all():
        if product.user:
            continue
        for profile_type in [
            "playerprofile",
            "coachprofile",
            "clubprofile",
            "guestprofile",
            "managerprofile",
            "scoutprofile",
            "refereeprofile",
            "otherprofile",
        ]:
            if profile := getattr(product, profile_type, None):
                product.user = profile.user
                product.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("premium", "0013_premiumprofile_is_trial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="premiumproduct",
            name="profile_uuid",
        ),
        migrations.AddField(
            model_name="premiumproduct",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(set_user, reverse_code=migrations.RunPython.noop),
    ]
