# Generated by Django 3.2.25 on 2025-01-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0014_auto_20250116_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiuminquiriesproduct',
            name='counter_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='premiuminquiriesproduct',
            name='valid_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
