# Generated by Django 3.2.25 on 2025-01-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0015_auto_20250116_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoteprofileproduct',
            name='valid_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
