# Generated by Django 3.2.25 on 2025-01-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0016_alter_promoteprofileproduct_valid_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumprofile',
            name='valid_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
