# Generated by Django 3.2.25 on 2025-01-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0017_alter_premiumprofile_valid_since'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatepmscoreproduct',
            name='awaiting_approval',
        ),
    ]
