# Generated by Django 3.2.25 on 2025-02-01 10:00

from django.db import migrations


def set_user_for_premium_products(apps, schema_editor):
    PremiumProduct = apps.get_model("premium", "PremiumProduct")

    for pp in PremiumProduct.objects.filter(user__isnull=True):
        pp.save()


class Migration(migrations.Migration):
    dependencies = [
        ("premium", "0018_remove_calculatepmscoreproduct_awaiting_approval"),
    ]

    operations = [
        migrations.RunPython(
            set_user_for_premium_products, reverse_code=migrations.RunPython.noop
        )
    ]
