# Generated by Django 3.2.25 on 2025-11-19 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('premium', '0020_update_product_names_to_polish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatepmscoreproduct',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='premiumprofile',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium', to='premium.premiumproduct'),
        ),
        migrations.AlterField(
            model_name='promoteprofileproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='premium.premiumproduct'),
        ),
    ]
