# Generated by Django 3.2 on 2022-07-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voivodeships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voivodeships',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
