# Generated by Django 3.2 on 2022-07-15 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("voivodeships", "0002_alter_voivodeships_name"),
    ]

    operations = []
