# Generated by Django 3.2.25 on 2025-04-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20231205_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notificationsetting',
            name='user',
        ),
        migrations.DeleteModel(
            name='NotificationTemplate',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='NotificationSetting',
        ),
    ]
