# Generated by Django 3.2.25 on 2025-04-16 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0167_playerprofile_meta'),
        ('notifications', '0005_auto_20250416_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('href', models.CharField(max_length=255)),
                ('template_name', models.CharField(blank=True, max_length=100, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='profiles.profilemeta')),
            ],
            options={
                'verbose_name': 'Powiadomienia użytkownika',
                'verbose_name_plural': 'Powiadomienia użytkowników',
            },
        ),
    ]
