# Generated by Django 3.2.25 on 2025-04-23 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20250421_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='profile',
            new_name='target',
        ),
    ]
