# Generated by Django 3.2.25 on 2025-08-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_rename_profile_notification_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='template_params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
