# Generated by Django 3.2 on 2023-05-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_squashed_0010_product_extra_css"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="raw_slug",
            field=models.BooleanField(
                default=False,
                help_text="if so, slug will not include /products/... subdir",
            ),
        ),
    ]
