# Generated by Django 3.1.2 on 2021-02-19 17:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrequest',
            unique_together={('user', 'product', 'date')},
        ),
    ]
