# Generated by Django 3.2.25 on 2025-02-26 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_raw_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageDescription',
        ),
        migrations.AlterUniqueTogether(
            name='request',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='request',
            name='product',
        ),
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
