# Generated by Django 3.1.2 on 2021-02-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210224_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='product_pics/%Y-%m-%d/', verbose_name='Zdjęcie'),
        ),
    ]
