# Generated by Django 3.1.2 on 2021-02-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='html_body_footer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
