# Generated by Django 3.1.2 on 2021-03-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210228_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='html_first',
            field=models.TextField(blank=True, null=True),
        ),
    ]
