# Generated by Django 3.1.2 on 2021-03-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_html_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_css',
            field=models.TextField(blank=True, null=True),
        ),
    ]
